import type { Command } from 'commander';
import { AutomaxError } from '@automax/core';

type Shell = 'bash' | 'zsh' | 'fish';

interface Node {
  name: string;
  description: string;
  options: Array<{ flags: string[]; description: string }>;
  children: Node[];
}

/** Walk commander metadata into a plain tree (no actions executed). */
export function commandTree(cmd: Command): Node {
  return {
    name: cmd.name(),
    description: cmd.description(),
    options: cmd.options.map((o) => ({
      flags: [o.short, o.long].filter((f): f is string => Boolean(f)),
      description: o.description,
    })),
    children: cmd.commands
      .filter((c) => !c.name().startsWith('_'))
      .map((c) => commandTree(c))
      .sort((a, b) => a.name.localeCompare(b.name)),
  };
}

export function renderCompletion(shell: Shell, root: Node): string {
  switch (shell) {
    case 'bash':
      return bash(root);
    case 'zsh':
      return zsh(root);
    case 'fish':
      return fish(root);
  }
}

function q(s: string): string {
  return s.replace(/'/g, "'\\''");
}

function words(n: Node): string {
  return [...n.children.map((c) => c.name), ...n.options.flatMap((o) => o.flags)].join(' ');
}

function bash(root: Node): string {
  const cases = root.children
    .map((c) => {
      const sub = c.children.length
        ? c.children
            .map(
              (s) =>
                `        ${s.name}) COMPREPLY=( $(compgen -W '${q(words(s))} ${q(root.options.flatMap((o) => o.flags).join(' '))}' -- "$cur") ); return 0 ;;`,
            )
            .join('\n')
        : '';
      return `    ${c.name})
      case "\${COMP_WORDS[2]}" in
${sub}
        *) COMPREPLY=( $(compgen -W '${q(words(c))}' -- "$cur") ); return 0 ;;
      esac ;;`;
    })
    .join('\n');
  return `# bash completion for automax — generated by \`automax completion bash\`
# Install: automax completion bash > ~/.automax-completion.bash && echo 'source ~/.automax-completion.bash' >> ~/.bashrc
_automax() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W '${q(words(root))}' -- "$cur") ); return 0
  fi
  case "\${COMP_WORDS[1]}" in
${cases}
    *) COMPREPLY=( $(compgen -W '${q(root.options.flatMap((o) => o.flags).join(' '))}' -- "$cur") ) ;;
  esac
}
complete -F _automax automax
`;
}

function zsh(root: Node): string {
  const describe = (n: Node, indent: string) =>
    n.children.map((c) => `${indent}'${q(c.name)}:${q(c.description || c.name)}'`).join('\n');
  const optSpecs = (n: Node) =>
    n.options.flatMap((o) => o.flags.map((f) => `'${q(f)}[${q(o.description || f)}]'`)).join(' ');
  const level2 = root.children
    .map(
      (c) => `    ${c.name})
      if (( CURRENT == 3 )) && [[ -n "${c.children.length ? 'x' : ''}" ]]; then
        local -a subcmds; subcmds=(
${describe(c, '          ')}
        )
        _describe 'subcommand' subcmds
      else
        _arguments -s ${optSpecs(c)} ${optSpecs(root)} '*:file:_files'
      fi ;;`,
    )
    .join('\n');
  return `#compdef automax
# zsh completion for automax — generated by \`automax completion zsh\`
# Install: automax completion zsh > "\${fpath[1]}/_automax" && autoload -Uz compinit && compinit
_automax() {
  local -a cmds
  cmds=(
${describe(root, '    ')}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' cmds
    _arguments -s ${optSpecs(root)}
    return
  fi
  case "\${words[2]}" in
${level2}
    *) _arguments -s ${optSpecs(root)} ;;
  esac
}
_automax "$@"
`;
}

function fish(root: Node): string {
  const lines: string[] = [
    '# fish completion for automax — generated by `automax completion fish`',
    '# Install: automax completion fish > ~/.config/fish/completions/automax.fish',
    `complete -c automax -f`,
  ];
  for (const o of root.options) {
    for (const f of o.flags) {
      lines.push(
        `complete -c automax ${f.startsWith('--') ? `-l ${f.slice(2)}` : `-s ${f.slice(1)}`} -d '${q(o.description)}'`,
      );
    }
  }
  for (const c of root.children) {
    lines.push(
      `complete -c automax -n '__fish_use_subcommand' -a ${c.name} -d '${q(c.description)}'`,
    );
    for (const s of c.children) {
      lines.push(
        `complete -c automax -n '__fish_seen_subcommand_from ${c.name}' -a ${s.name} -d '${q(s.description)}'`,
      );
      for (const o of s.options) {
        for (const f of o.flags) {
          lines.push(
            `complete -c automax -n '__fish_seen_subcommand_from ${s.name}' ${f.startsWith('--') ? `-l ${f.slice(2)}` : `-s ${f.slice(1)}`} -d '${q(o.description)}'`,
          );
        }
      }
    }
    for (const o of c.options) {
      for (const f of o.flags) {
        lines.push(
          `complete -c automax -n '__fish_seen_subcommand_from ${c.name}' ${f.startsWith('--') ? `-l ${f.slice(2)}` : `-s ${f.slice(1)}`} -d '${q(o.description)}'`,
        );
      }
    }
  }
  return lines.join('\n') + '\n';
}

export function register(program: Command) {
  program
    .command('completion <shell>')
    .description('Print a shell completion script (bash | zsh | fish)')
    .action((shell: string) => {
      if (!['bash', 'zsh', 'fish'].includes(shell)) {
        throw new AutomaxError(
          'CONFIG_INVALID',
          `Unknown shell "${shell}". Use bash, zsh or fish.`,
          {
            exitCode: 2,
          },
        );
      }
      let root: Command = program;
      while (root.parent) root = root.parent;
      process.stdout.write(renderCompletion(shell as Shell, commandTree(root)));
    });
}
