// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import playwright from 'eslint-plugin-playwright';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/test/fixtures/apps/**',
      // Python virtualenvs (e.g. media/film/tts/.venv) ship vendored JS that is not ours to lint.
      '**/.venv/**',
      '**/dist/**',
      '**/node_modules/**',
      '**/.features-gen/**',
      '**/.sdods/**',
      'apps/docs/out/**',
      'apps/docs/.next/**',
      'apps/docs/.source/**',
      'apps/docs/next-env.d.ts',
      'apps/www/out/**',
      'apps/www/.next/**',
      'apps/www/next-env.d.ts',
      'apps/www/screenshots/**',
      'packages/web/dist/**',
      // Publish-time staging, generated by scripts/build-publish-assets.ts.
      'packages/server/web/**',
      'packages/cli/templates/**',
      '.publish-stage/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['projects/**/*.ts', 'packages/core/src/steps/**/*.ts'],
    ...playwright.configs['flat/recommended'],
    rules: {
      ...playwright.configs['flat/recommended'].rules,
      // Steps and page objects assert inside step functions / decorated methods, not test blocks.
      'playwright/expect-expect': 'off',
      'playwright/no-standalone-expect': 'off',
      'playwright/prefer-web-first-assertions': 'off',
      'playwright/no-wait-for-timeout': 'off',
      'playwright/no-conditional-in-test': 'off',
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/consistent-type-imports': 'error',
    },
  },
  prettier,
);
