// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import playwright from 'eslint-plugin-playwright';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/test/fixtures/apps/**',
      // Golden k6 scripts (k6 globals such as __ENV, byte-for-byte generator output).
      '**/test/fixtures/load/**',
      // Python virtualenvs (e.g. media/film/tts/.venv) ship vendored JS that is not ours to lint.
      '**/.venv/**',
      '**/dist/**',
      '**/node_modules/**',
      '**/.features-gen/**',
      '**/.sdods/**',
      'apps/docs/out/**',
      'apps/docs/.next/**',
      'apps/docs/.source/**',
      'apps/docs/next-env.d.ts',
      'apps/www/out/**',
      'apps/www/.next/**',
      'apps/www/next-env.d.ts',
      'apps/www/screenshots/**',
      // electron-vite build output and the staged Node runtime: generated, never ours to lint.
      'apps/desktop/out/**',
      'apps/desktop/release/**',
      'apps/desktop/resources/node/**',
      'packages/web/dist/**',
      // Publish-time staging, generated by scripts/build-publish-assets.ts.
      'packages/server/web/**',
      'packages/cli/templates/**',
      '.publish-stage/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['projects/**/*.ts', 'packages/core/src/steps/**/*.ts'],
    ...playwright.configs['flat/recommended'],
    rules: {
      ...playwright.configs['flat/recommended'].rules,
      // Steps and page objects assert inside step functions / decorated methods, not test blocks.
      'playwright/expect-expect': 'off',
      'playwright/no-standalone-expect': 'off',
      'playwright/prefer-web-first-assertions': 'off',
      'playwright/no-wait-for-timeout': 'off',
      'playwright/no-conditional-in-test': 'off',
    },
  },
  {
    // The platform stays vendor-neutral: Firebase is a deployment choice, wired in through ports
    // (community/maxi stores and verifiers, the sites' Identity). Its adapters live only in the
    // places below, which move to the private deployment package.
    files: ['packages/**/*.{ts,tsx}', 'apps/**/*.{ts,tsx}'],
    ignores: [
      'packages/community/src/firebase/**',
      'packages/community/src/main.ts',
      'packages/community/test/firebase.test.ts',
      'packages/maxi/src/firebase/**',
      'packages/maxi/src/main.ts',
      'packages/maxi/test/firebase.test.ts',
      'apps/www/lib/firebase-identity.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              regex: '^(firebase|firebase-admin|@firebase)(/|$)|/firebase(/|\\.js$|/index\\.js$)',
              message:
                'Firebase belongs in a deployment adapter (src/firebase/, lib/firebase-identity.ts), behind a port.',
            },
          ],
        },
      ],
    },
  },
  {
    // The electron-builder hooks are plain .mjs running in Node: js.configs.recommended declares
    // no Node globals, and TypeScript files get theirs from typescript-eslint. Scoped narrowly --
    // the Next.js configs import `process` themselves and a blanket rule collides with that.
    files: ['apps/desktop/scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        __dirname: 'readonly',
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/consistent-type-imports': 'error',
    },
  },
  prettier,
);
