import { spawnSync } from 'node:child_process';
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  realpathSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { ProjectConfigSchema } from '@sdods/contracts';
import { parseFeatureFile, scenariosOf } from '../src/lint/gherkin.js';
import { lintProject } from '../src/lint/index.js';
import {
  expandFeatureText,
  parseRolesMatrices,
  planMatrixExpansion,
  type RolesMatrix,
} from '../src/matrix/index.js';

/**
 * #118 — an actor × surface grid was hundreds of hand-written scenarios. `roles.matrix.yaml` holds
 * the grid; a `@matrix:<name>` outline is the template; the generator writes one Examples block per
 * role, tagged `@user:<role>`, between markers, and must be idempotent and leave hand-written rows
 * alone.
 */

const MATRIX_YAML = `matrices:
  admin-surfaces:
    roles: [owner, admin, member, viewer]
    default: denied
    outcomes: [allowed, denied]
    rows:
      - surface: /settings/billing
        expect: { owner: allowed, admin: allowed }
      - surface: /settings/profile
        expect: allowed
      - surface: /settings/team
        default: allowed
        expect: { viewer: denied }
`;

const TEMPLATE = `@ui @admin
Feature: Admin surfaces

  @regression @matrix:admin-surfaces
  Scenario Outline: Surface access by role
    Given I open the surface "<surface>"
    Then access should be "<expect>"

  @smoke
  Scenario: Unrelated
    Given I open the surface "/"
`;

const EXPANDED = `@ui @admin
Feature: Admin surfaces

  @regression @matrix:admin-surfaces
  Scenario Outline: Surface access by role
    Given I open the surface "<surface>"
    Then access should be "<expect>"

    # sdods:matrix:begin admin-surfaces (generated by \`sdods matrix expand\` from roles.matrix.yaml; edit the matrix, not these rows)
    # title-format: <role>: <surface> → <expect>
    @user:owner
    Examples: owner
      | role  | surface           | expect  |
      | owner | /settings/billing | allowed |
      | owner | /settings/profile | allowed |
      | owner | /settings/team    | allowed |

    # title-format: <role>: <surface> → <expect>
    @user:admin
    Examples: admin
      | role  | surface           | expect  |
      | admin | /settings/billing | allowed |
      | admin | /settings/profile | allowed |
      | admin | /settings/team    | allowed |

    # title-format: <role>: <surface> → <expect>
    @user:member
    Examples: member
      | role   | surface           | expect  |
      | member | /settings/billing | denied  |
      | member | /settings/profile | allowed |
      | member | /settings/team    | allowed |

    # title-format: <role>: <surface> → <expect>
    @user:viewer
    Examples: viewer
      | role   | surface           | expect  |
      | viewer | /settings/billing | denied  |
      | viewer | /settings/profile | allowed |
      | viewer | /settings/team    | denied  |
    # sdods:matrix:end admin-surfaces

  @smoke
  Scenario: Unrelated
    Given I open the surface "/"
`;

function matrices(yaml = MATRIX_YAML): Map<string, RolesMatrix> {
  const loaded = parseRolesMatrices(yaml);
  expect(loaded.problems).toEqual([]);
  return loaded.matrices;
}

const messages = (yaml: string) => parseRolesMatrices(yaml).problems.map((p) => p.message);

describe('roles.matrix.yaml validation', () => {
  it('accepts defaults and per-role overrides and resolves every role', () => {
    const m = matrices().get('admin-surfaces')!;
    expect(m.columns).toEqual(['surface']);
    expect(m.rows.map((r) => r.expect)).toEqual([
      { owner: 'allowed', admin: 'allowed', member: 'denied', viewer: 'denied' },
      { owner: 'allowed', admin: 'allowed', member: 'allowed', viewer: 'allowed' },
      { owner: 'allowed', admin: 'allowed', member: 'allowed', viewer: 'denied' },
    ]);
  });

  it('reports yaml syntax and schema errors without throwing', () => {
    expect(messages('matrices: [oops')[0]).toMatch(/Cannot parse YAML/);
    // A name that is not a valid regex source must still come back as a finding.
    expect(messages('matrices:\n  a(:\n    roles: [a]\n    rows: [{ x: 1, expect: y }]\n')).toEqual(
      [expect.stringContaining('lowercase letters, digits and dashes')],
    );
    expect(
      messages('matrices:\n  Bad Name:\n    roles: [a]\n    rows: [{ x: 1, expect: y }]\n'),
    ).toEqual([expect.stringContaining('lowercase letters, digits and dashes')]);
    expect(
      messages('matrices:\n  m:\n    roles: []\n    rows: [{ x: 1, expect: y }]\n')[0],
    ).toMatch(/^matrices\.m\.roles:/);
    expect(messages('matrices:\n  m:\n    roles: [a]\n    rowz: []\n')).toEqual(
      expect.arrayContaining([expect.stringContaining('rows')]),
    );
  });

  it('reports rows that cannot become an Examples table', () => {
    const problems = messages(`matrices:
  m:
    roles: [owner, viewer, owner]
    outcomes: [allowed, denied]
    rows:
      - surface: /a
        expect: { owner: allowed, admn: allowed }
      - surface: /b
        area: x
        expect: allowed
      - surface: /a
        expect: alowed
      - surface: /c
        role: owner
        default: denied
`);
    expect(problems).toEqual([
      'matrices.m: role listed twice: owner.',
      'matrices.m: rows[0].expect names admn, not in roles [owner, viewer, owner].',
      'matrices.m: rows[0] has no outcome for viewer; name them in expect or set a default.',
      'matrices.m: rows[1] has columns [surface, area]; every row needs the columns of rows[0] [surface].',
      'matrices.m: rows[2] repeats rows[0].',
      'matrices.m: rows[2]: outcome "alowed" for owner is not in outcomes [allowed, denied].',
      'matrices.m: rows[2]: outcome "alowed" for viewer is not in outcomes [allowed, denied].',
      'matrices.m: rows[2]: outcome "alowed" for owner is not in outcomes [allowed, denied].',
      'matrices.m: rows[3] has columns [surface, role]; every row needs the columns of rows[0] [surface].',
    ]);
    expect(
      parseRolesMatrices(
        MATRIX_YAML.replace('admin-surfaces:', 'admin-surfaces:\n    title: "<who>"'),
      ).problems[0]!.message,
    ).toMatch(/title uses <who>/);
  });
});

describe('expanding a @matrix outline', () => {
  it('writes one Examples block per role, tagged @user:<role> (golden)', () => {
    const r = expandFeatureText(TEMPLATE, matrices());
    expect(r.problems).toEqual([]);
    expect(r.examples).toBe(12);
    expect(r.changed).toBe(true);
    expect(r.text).toBe(EXPANDED);
  });

  it('is idempotent', () => {
    const r = expandFeatureText(EXPANDED, matrices());
    expect(r.changed).toBe(false);
    expect(r.text).toBe(EXPANDED);
  });

  it('refreshes only the generated block when the matrix changes, keeping hand-written Examples', () => {
    const withHand = EXPANDED.replace(
      '    Then access should be "<expect>"\n',
      '    Then access should be "<expect>"\n\n    @user:owner\n    Examples: hand-written\n      | role  | surface | expect  |\n      | owner | /legacy | allowed |\n',
    );
    const changed = matrices(MATRIX_YAML.replace('viewer: denied', 'viewer: allowed'));
    const r = expandFeatureText(withHand, changed);
    expect(r.changed).toBe(true);
    expect(r.text).toContain(
      'Examples: hand-written\n      | role  | surface | expect  |\n      | owner | /legacy | allowed |',
    );
    expect(r.text).toContain('      | viewer | /settings/team    | allowed |');
    // Exactly one line differs from the previous expansion.
    const before = withHand.split('\n');
    const after = r.text.split('\n');
    expect(after).toHaveLength(before.length);
    expect(after.filter((l, i) => l !== before[i])).toEqual([
      '      | viewer | /settings/team    | allowed |',
    ]);
    expect(expandFeatureText(r.text, changed).changed).toBe(false);
  });

  it('inserts after data tables, doc strings and hand-written Examples', () => {
    const text = `Feature: F

  @ui @regression @matrix:admin-surfaces
  Scenario Outline: With a table
    Given the payload
      """
      { "surface": "<surface>" }
      """
    Then the rows are
      | who    | result   |
      | <role> | <expect> |
`;
    const r = expandFeatureText(text, matrices());
    expect(r.problems).toEqual([]);
    const lines = r.text.split('\n');
    expect(lines[10]).toBe('      | <role> | <expect> |');
    expect(lines[11]).toBe('');
    expect(lines[12]).toMatch(/^ {4}# sdods:matrix:begin admin-surfaces/);
    expect(parseFeatureFile('f.feature', r.text).pickles).toHaveLength(12);
  });

  it('removes a generated block when its outline loses the @matrix tag, and restores the template', () => {
    const untagged = EXPANDED.replace(' @matrix:admin-surfaces', '');
    const r = expandFeatureText(untagged, matrices());
    expect(r.text).toBe(TEMPLATE.replace(' @matrix:admin-surfaces', ''));
  });

  it('escapes pipes, backslashes and newlines in cells', () => {
    const m = matrices(`matrices:
  q:
    roles: [a]
    rows:
      - query: "x|y\\\\z"
        expect: "line1\\nline2"
`);
    const text =
      'Feature: F\n\n  @ui @smoke @matrix:q\n  Scenario Outline: Q\n    Given "<query>" "<expect>"\n';
    const r = expandFeatureText(text, m);
    expect(r.text).toContain('| a    | x\\|y\\\\z | line1\\nline2 |');
    const parsed = parseFeatureFile('q.feature', r.text);
    expect(parsed.errors).toEqual([]);
    expect(parsed.pickles[0]!.steps[0]!.text).toBe('"x|y\\z" "line1\nline2"');
  });

  it('reports misplaced tags, a role tag on the template, unknown placeholders and broken markers', () => {
    const problems = (text: string) =>
      expandFeatureText(text, matrices()).problems.map((p) => `${p.rule}@${p.line}: ${p.message}`);
    expect(
      problems('@matrix:admin-surfaces\nFeature: F\n\n  @ui @smoke\n  Scenario: S\n    Given x\n'),
    ).toEqual([
      'matrix/template@1: @matrix:admin-surfaces belongs on the Scenario Outline, not the Feature.',
    ]);
    expect(
      problems(
        'Feature: F\n\n  @ui @smoke @user:owner @matrix:admin-surfaces\n  Scenario Outline: S\n    Given "<surface>" "<area>"\n',
      ),
    ).toEqual([
      'matrix/template@3: @user:owner on a @matrix outline would override every generated role; remove it.',
      'matrix/placeholder@4: <area> not provided by matrix "admin-surfaces" (columns: role, expect, surface).',
    ]);
    expect(
      problems(
        'Feature: F\n\n  @ui @smoke @matrix:admin-surfaces\n  Scenario Outline: S\n    Given x\n    # sdods:matrix:begin admin-surfaces\n',
      ),
    ).toEqual(['matrix/markers@6: "# sdods:matrix:begin" without a matching end.']);
  });
});

// ── project level: lint, pool, staleness ─────────────────────────────────────

function project(files: Record<string, string>, extra: Record<string, unknown> = {}) {
  const root = join(mkdtempSync(join(tmpdir(), 'sdods-matrix-')), 'projects', 'shop');
  for (const [rel, body] of Object.entries(files)) {
    mkdirSync(dirname(join(root, rel)), { recursive: true });
    writeFileSync(join(root, rel), body);
  }
  return {
    ...ProjectConfigSchema.parse({
      slug: 'shop',
      name: 'Shop',
      layers: ['ui'],
      browsers: ['chromium'],
      envs: { default: 'staging', available: ['local', 'staging'] },
      tags: { roles: ['owner', 'admin', 'member', 'viewer'] },
      data: {
        sources: { users: { type: 'csv', path: 'data/{env}/users.csv' } },
        userPool: { dataset: 'users' },
      },
      ...extra,
    }),
    root,
  };
}

const USERS =
  'id,username,password,role\n1,o,${PW},owner\n2,a,${PW},admin\n3,m,${PW},member\n4,v,${PW},viewer\n';
const STEPS = `import { createBdd } from 'playwright-bdd';
const { Given, Then } = createBdd();
Given('I open the surface {string}', async ({}, surface: string) => void surface);
Then('access should be {string}', async ({}, outcome: string) => void outcome);
`;
const rules = (list: Array<{ rule: string }>) =>
  list.map((f) => f.rule).filter((r) => /matrix/.test(r));

describe('lint: role matrices', () => {
  const seeded = {
    'roles.matrix.yaml': MATRIX_YAML,
    'data/staging/users.csv': USERS,
    'data/local/users.csv': USERS,
    'steps/admin.steps.ts': STEPS,
  };

  it('is clean for an expanded feature with every role seeded', async () => {
    const res = await lintProject({
      project: project({ ...seeded, 'features/admin.feature': EXPANDED }),
    });
    expect(rules(res.errors)).toEqual([]);
    expect(rules(res.warnings)).toEqual([]);
    expect(res.errors).toEqual([]);
  });

  it('warns when a matrix feature is out of date, and when it was never expanded', async () => {
    const stale = EXPANDED.replace(
      '| viewer | /settings/team    | denied  |',
      '| viewer | /settings/team    | allowed |',
    );
    const res = await lintProject({
      project: project({
        ...seeded,
        'features/admin.feature': stale,
        'features/new.feature': TEMPLATE,
      }),
    });
    expect(res.warnings.filter((w) => w.rule === 'matrix/stale').map((w) => w.file)).toEqual([
      'features/admin.feature',
      'features/new.feature',
    ]);
    expect(res.warnings.find((w) => w.rule === 'matrix/stale')!.message).toContain(
      'sdods matrix expand -p shop',
    );
  });

  it('errors on an unknown matrix name and a missing matrix file', async () => {
    const unknown = TEMPLATE.replace('@matrix:admin-surfaces', '@matrix:billing');
    let res = await lintProject({
      project: project({ ...seeded, 'features/admin.feature': unknown }),
    });
    expect(res.errors.filter((e) => e.rule === 'tags/matrix').map((e) => e.message)).toEqual([
      '@matrix:billing is not a matrix in roles.matrix.yaml (admin-surfaces).',
    ]);
    res = await lintProject({ project: project({ 'features/admin.feature': TEMPLATE }) });
    expect(res.errors.filter((e) => e.rule === 'tags/matrix').map((e) => e.message)).toEqual([
      '@matrix:admin-surfaces needs a roles.matrix.yaml in the project.',
    ]);
  });

  it('errors on a matrix role the project does not declare, and on an invalid matrix file', async () => {
    let res = await lintProject({
      project: project(
        { ...seeded, 'features/admin.feature': EXPANDED },
        { tags: { roles: ['owner', 'admin', 'member'] } },
      ),
    });
    const role = res.errors.find((e) => e.rule === 'matrix/role')!;
    expect(role.message).toBe(
      'matrices.admin-surfaces: viewer is not a declared role (tags.roles: owner, admin, member).',
    );
    expect(role.file).toBe('roles.matrix.yaml');
    expect(role.line).toBe(2);
    // The generated @user:viewer tag is caught by the existing rule too.
    expect(
      res.errors.some((e) => e.rule === 'tags/user' && e.message.startsWith('@user:viewer')),
    ).toBe(true);

    res = await lintProject({
      project: project({
        ...seeded,
        'roles.matrix.yaml': MATRIX_YAML.replace('expect: allowed', 'expect: [x]'),
        'features/admin.feature': EXPANDED,
      }),
    });
    expect(rules(res.errors)).toEqual(['matrix/config']);
    // An invalid matrix is not ALSO an unknown name, and its features are not rewritten from nothing.
    expect(res.warnings.filter((w) => w.rule === 'matrix/stale')).toEqual([]);
  });

  it('warns when a matrix role has no pool account in an environment', async () => {
    const res = await lintProject({
      project: project({
        ...seeded,
        'data/local/users.csv': 'id,username,password,role\n1,o,${PW},owner\n',
        'features/admin.feature': EXPANDED,
      }),
    });
    expect(
      res.warnings.filter((w) => w.rule === 'matrix/unseeded-role').map((w) => w.message),
    ).toEqual([
      'matrices.admin-surfaces: role "admin" has no account in pool dataset "users" for env local; its 3 generated example(s) will fail to lease there.',
      'matrices.admin-surfaces: role "member" has no account in pool dataset "users" for env local; its 3 generated example(s) will fail to lease there.',
      'matrices.admin-surfaces: role "viewer" has no account in pool dataset "users" for env local; its 3 generated example(s) will fail to lease there.',
    ]);
  });

  it('warns when the project has no user pool at all', async () => {
    const res = await lintProject({
      project: project(
        { 'roles.matrix.yaml': MATRIX_YAML, 'features/admin.feature': EXPANDED },
        { data: { sources: {} } },
      ),
    });
    expect(
      res.warnings.filter((w) => w.rule === 'matrix/unseeded-role').map((w) => w.message),
    ).toEqual([
      'matrices.admin-surfaces: the project has no data.userPool, so no @user:<role> scenario can lease an account.',
    ]);
  });

  it('plans only the features that use a matrix', () => {
    const p = project({
      ...seeded,
      'features/admin.feature': TEMPLATE,
      'features/other.feature': 'Feature: O\n',
    });
    const plan = planMatrixExpansion(p, [
      join(p.root, 'features/admin.feature'),
      join(p.root, 'features/other.feature'),
    ]);
    expect(plan.files.map((f) => [f.path, f.changed, f.examples])).toEqual([
      ['features/admin.feature', true, 12],
    ]);
    expect(plan.files[0]!.after).toBe(EXPANDED);
  });
});

describe('generated feature through the Gherkin parser and bddgen', () => {
  it('parses into one pickle per role × row, each carrying its @user:<role>', () => {
    const parsed = parseFeatureFile('admin.feature', EXPANDED);
    expect(parsed.errors).toEqual([]);
    const matrixPickles = parsed.pickles.filter((p) =>
      p.tags.some((t) => t.name === '@matrix:admin-surfaces'),
    );
    expect(matrixPickles).toHaveLength(12);
    const users = matrixPickles.map((p) =>
      p.tags.map((t) => t.name).filter((t) => t.startsWith('@user:')),
    );
    expect(users.every((u) => u.length === 1)).toBe(true);
    expect(users.flat().filter((u) => u === '@user:viewer')).toHaveLength(3);
    expect(scenariosOf(parsed)[0]!.hasTitleFormat).toBe(true);
  });

  it('bddgen generates one test per role × row, tagged @user:<role>, with unique titles', () => {
    const require_ = createRequire(import.meta.url);
    const bdd = require_.resolve('playwright-bdd');
    const cli = join(
      dirname(require_.resolve('playwright-bdd/package.json')),
      'dist',
      'cli',
      'index.js',
    );
    // bddgen compares against the real path; macOS tmpdir() is a symlink into /private.
    const dir = realpathSync(mkdtempSync(join(tmpdir(), 'sdods-matrix-bddgen-')));
    mkdirSync(join(dir, 'features'));
    mkdirSync(join(dir, 'steps'));
    writeFileSync(join(dir, 'features', 'admin.feature'), EXPANDED);
    writeFileSync(
      join(dir, 'steps', 'admin.steps.ts'),
      STEPS.replace("'playwright-bdd'", JSON.stringify(bdd)),
    );
    writeFileSync(
      join(dir, 'playwright.config.mjs'),
      `import { defineBddConfig } from ${JSON.stringify(bdd)};\n` +
        `export default { testDir: defineBddConfig({ features: ${JSON.stringify(join(dir, 'features/*.feature'))}, steps: ${JSON.stringify(join(dir, 'steps/*.ts'))}, outputDir: ${JSON.stringify(join(dir, '.gen'))} }) };\n`,
    );
    const run = spawnSync(process.execPath, [cli, '-c', 'playwright.config.mjs'], {
      cwd: dir,
      encoding: 'utf8',
    });
    expect(run.status, run.stdout + run.stderr).toBe(0);
    const spec = readFileSync(
      join(dir, '.gen', 'features', readdirSync(join(dir, '.gen', 'features'))[0]!),
      'utf8',
    );
    const tests = [...spec.matchAll(/test\('([^']+)', \{ tag: \[([^\]]*)\] \}/g)].map((m) => ({
      title: m[1]!,
      tags: m[2]!.split(',').map((t) => t.trim().replace(/'/g, '')),
    }));
    const matrixTests = tests.filter((t) => t.tags.includes('@matrix:admin-surfaces'));
    expect(matrixTests).toHaveLength(12);
    for (const role of ['owner', 'admin', 'member', 'viewer'])
      expect(matrixTests.filter((t) => t.tags.includes(`@user:${role}`))).toHaveLength(3);
    expect(new Set(matrixTests.map((t) => t.title)).size).toBe(12);
    expect(matrixTests[0]!.title).toBe('owner: /settings/billing → allowed');
  });
});
