import type { Checkpoint, RoadmapPhase } from './types.js';

/** The fourteen phases, each of which ended runnable. Grouped into chapters below. */
const PHASES: RoadmapPhase[] = [
  { phase: 0, scope: 'Monorepo, config precedence, registry, CLI skeleton', status: 'done' },
  { phase: 1, scope: 'API layer end to end (no browser)', status: 'done' },
  { phase: 2, scope: 'UI layer, page objects, self-healing, dashboard', status: 'done' },
  { phase: 3, scope: 'Data providers, user pool, auth capture, hybrid', status: 'done' },
  { phase: 4, scope: 'Screenshot narratives, NDJSON', status: 'done' },
  { phase: 5, scope: 'Database, ingest, switch', status: 'done' },
  { phase: 6, scope: 'Recorder and HAR', status: 'done' },
  { phase: 7, scope: 'MCP server', status: 'done' },
  { phase: 8, scope: 'Agents and insights', status: 'done' },
  { phase: 9, scope: 'Server, scheduler', status: 'done' },
  { phase: 10, scope: 'Web UI', status: 'done' },
  { phase: 11, scope: 'GitHub, Jira, CI workflows', status: 'done' },
  { phase: 12, scope: 'Onboarding analysis, processes, cross-browser matrix', status: 'done' },
  { phase: 13, scope: 'Documentation site, packaging, sdods init', status: 'done' },
];

const phases = (...numbers: number[]): RoadmapPhase[] =>
  numbers.map((n) => PHASES.find((p) => p.phase === n)!);

/**
 * The road, stop by stop.
 *
 * Behind the reader: five chapters, deliberately undated. The work is real and the code is
 * here, but this repository's history is days old and nothing has been released, so a month
 * against each chapter would be a number nobody could check.
 *
 * Ahead: twelve months that are close enough to promise, then three years of direction.
 */
export const CHECKPOINTS: Checkpoint[] = [
  {
    id: 'ch-foundations',
    kind: 'chapter',
    order: 1,
    label: 'Foundations',
    title: 'One command runs a scenario',
    state: 'delivered',
    arc: 1,
    goal: 'A test suite that a new machine can run without a page of setup instructions.',
    ships: [
      'A monorepo with contracts, runtime and CLI, one project per application',
      'Six-layer configuration precedence that can say where every value came from',
      'The organization → workspace → project → module hierarchy and named processes',
      'The API step library: requests, JSON-path assertions, schemas, variable chaining',
    ],
    proof: 'sdods run -p demo-shop -e staging -l api goes green with no browser installed.',
    phases: phases(0, 1),
  },
  {
    id: 'ch-browser',
    kind: 'chapter',
    order: 2,
    label: 'The browser',
    title: 'A UI failure explains itself',
    state: 'delivered',
    arc: 1,
    goal: 'When a browser test fails, the report already contains what you would have asked for.',
    ships: [
      'Page objects with step decorators and heal-aware locators',
      'Self-healing that records which strategy found the element and why',
      'Before and after screenshots for every step, with a pixel diff',
      'Data providers, the leased user pool, captured auth and hybrid scenarios',
    ],
    proof: 'A failed step in the run viewer shows the two screenshots either side of it.',
    phases: phases(2, 3, 4),
  },
  {
    id: 'ch-memory',
    kind: 'chapter',
    order: 3,
    label: 'Memory',
    title: 'Runs stop depending on one laptop',
    state: 'delivered',
    arc: 1,
    goal: 'History that outlives the terminal window the run happened in.',
    ships: [
      'One schema on SQLite or Postgres, switchable with a flag, with migrations',
      'Result ingest from cucumber JSON, NDJSON and runner JSON, and insights over it',
      'The recorder: capture a flow, replay it, convert it to a feature',
      'HAR record and replay for UI and API, so a suite can run offline',
    ],
    proof: 'The same run appears in the dashboard whichever machine produced it.',
    phases: phases(5, 6),
  },
  {
    id: 'ch-machine-readable',
    kind: 'chapter',
    order: 4,
    label: 'Machine-readable',
    title: 'The suite becomes something an agent can read',
    state: 'delivered',
    arc: 1,
    goal: 'An assistant can plan, generate and repair tests against your project, not a generic one.',
    ships: [
      'An MCP server exposing projects, features, steps, runs and results as tools',
      'Five agent roles — planner, generator, healer, upgrader, reviewer',
      'A provider-agnostic adapter, including models that run on your own machine',
      'Proposals: an agent writes, a person accepts, nothing edits the tree unasked',
    ],
    proof: 'sdods mcp install claude, then ask an assistant what a project covers.',
    phases: phases(7, 8),
  },
  {
    id: 'ch-platform',
    kind: 'chapter',
    order: 5,
    label: 'A platform',
    title: 'A team, not a script',
    state: 'delivered',
    arc: 1,
    goal: 'Everything a group of people needs around the runner, rather than around one engineer.',
    ships: [
      'A server with REST, live run streaming, MCP over HTTP and a scheduler',
      'A web UI: dashboards, run comparison, a Gherkin editor, agents, schedules',
      'GitHub checks and issues, Jira issues and links, CI workflows',
      'Onboarding analysis that reads an existing app, and the cross-browser matrix',
      'This documentation site, packaging and sdods init',
    ],
    proof: 'A second person can open the web UI and read yesterday’s run without asking you.',
    phases: phases(9, 10, 11, 12, 13),
  },

  {
    id: 'm-2026-10',
    kind: 'month',
    when: '2026-10',
    label: 'Oct 2026',
    title: 'Every claim on this site is true',
    state: 'now',
    arc: 2,
    goal: 'No page describes a feature that does not run. Trust is the product.',
    ships: [
      'Accessibility checks actually execute axe-core per @a11y scenario, or the guide retracts them',
      'Performance budgets enforced at run time, or the checkbox goes away',
      'Known limitations re-checked line by line against the code',
      'One source of truth for this roadmap, shared by the docs, the site and the README',
    ],
    proof: 'Every capability the documentation claims has a test that exercises it.',
  },
  {
    id: 'm-2026-11',
    kind: 'month',
    when: '2026-11',
    label: 'Nov 2026',
    title: 'A first real release',
    state: 'planned',
    arc: 2,
    goal: 'Install SDODS the way you install anything else.',
    ships: [
      'A version bump through changesets and a git tag that exists',
      'The @sdods packages published to npm for real',
      'A GitHub release with notes generated from the changesets',
      'A server image on GHCR, built from the tag',
    ],
    proof: 'npm view @sdods/cli version answers, and the installer stops falling back to git.',
  },
  {
    id: 'm-2026-12',
    kind: 'month',
    when: '2026-12',
    label: 'Dec 2026',
    title: 'CI and your laptop agree about a screenshot',
    state: 'planned',
    arc: 2,
    goal: 'Visual tests stop being the suite everyone disables.',
    ships: [
      'Cross-platform visual baselines, with Linux baselines produced in CI',
      'A baseline update flow that reviews the diff instead of trusting the runner',
      'Masking of the regions that will never be stable',
    ],
    proof: 'The @visual suite passes on Linux CI and macOS from the same committed baselines.',
  },
  {
    id: 'm-2027-01',
    kind: 'month',
    when: '2027-01',
    label: 'Jan 2027',
    title: 'A suite that runs with the network unplugged',
    state: 'planned',
    arc: 2,
    goal: 'Third-party sandboxes stop deciding whether your build is green.',
    ships: [
      'HAR fixtures per scenario for the sanity and user-pool suites',
      'Recording refreshed on demand, with the diff visible in review',
      '--har-replay --strict as the default in CI',
    ],
    proof: 'The full demo suite passes with outbound network disabled.',
  },
  {
    id: 'm-2027-02',
    kind: 'month',
    when: '2027-02',
    label: 'Feb 2027',
    title: 'Flake becomes a number, not an argument',
    state: 'planned',
    arc: 2,
    goal: 'A flaky test is measured and budgeted rather than retried in silence.',
    ships: [
      'Flake budgets per suite, computed from run history',
      'Automatic quarantine when a scenario exceeds its budget, with an owner',
      'A weekly digest naming what got worse and what recovered',
    ],
    proof: 'The dashboard answers “which tests cost us the most time this week”.',
  },
  {
    id: 'm-2027-03',
    kind: 'month',
    when: '2027-03',
    label: 'Mar 2027',
    title: 'One sign-in for the whole team',
    state: 'planned',
    arc: 2,
    goal: 'People reach their runs with the account they already have.',
    ships: [
      'OIDC single sign-on for the web UI, mapped onto the existing roles',
      'Tokens scoped to a workspace, revocable from the UI',
      'An audit line for who looked at what',
    ],
    proof: 'A new joiner opens the dashboard without anyone creating an account for them.',
  },
  {
    id: 'm-2027-04',
    kind: 'month',
    when: '2027-04',
    label: 'Apr 2027',
    title: 'History leaves the laptop',
    state: 'planned',
    arc: 2,
    goal: 'One history the whole team reads, so no one relitigates a failure.',
    ships: [
      'Hosted run history with retention you choose',
      'Ingest from CI as a first-class path, not an afterthought',
      'Comparison across branches and environments',
    ],
    proof: 'Two people looking at the same failure see the same evidence.',
  },
  {
    id: 'm-2027-05',
    kind: 'month',
    when: '2027-05',
    label: 'May 2027',
    title: 'Runs that know what changed',
    state: 'planned',
    arc: 2,
    goal: 'A pull request runs the tests that its diff can break, and finishes sooner.',
    ships: [
      'Change-aware selection from the diff, routes and page objects touched',
      'Scheduled runs that fill in whatever selection skipped',
      'A stated rule for when the full matrix runs anyway',
    ],
    proof: 'Pull-request feedback lands in minutes without losing a regression.',
  },
  {
    id: 'm-2027-06',
    kind: 'month',
    when: '2027-06',
    label: 'Jun 2027',
    title: 'Agents open pull requests',
    state: 'planned',
    arc: 2,
    goal: 'Locator drift arrives as a reviewable change rather than a red build.',
    ships: [
      'The healer opens a pull request carrying its heal history as evidence',
      'A confidence threshold under which it asks instead of proposing',
      'The same flow on a model running on your own hardware',
    ],
    proof: 'A renamed test id is fixed and merged without anyone writing a selector.',
  },
  {
    id: 'm-2027-07',
    kind: 'month',
    when: '2027-07',
    label: 'Jul 2027',
    title: 'One incident is one item',
    state: 'planned',
    arc: 2,
    goal: 'Forty failures with one cause stop looking like forty problems.',
    ships: [
      'Failure clustering by cause across a run and across runs',
      'A first-failure summary that names the shared step or request',
      'Links from the cluster to every scenario inside it',
    ],
    proof: 'A broken login shows as one item with thirty-nine scenarios attached.',
  },
  {
    id: 'm-2027-08',
    kind: 'month',
    when: '2027-08',
    label: 'Aug 2027',
    title: 'Coverage measured against reality',
    state: 'planned',
    arc: 2,
    goal: 'You learn which journeys real users take that no scenario covers.',
    ships: [
      'Real traffic compared against covered journeys, with the gaps ranked',
      'Suggested scenarios for the gaps, as proposals a person accepts',
      'Coverage reported per business capability, not per file',
    ],
    proof: 'The coverage report names a journey nobody had thought to test.',
  },
  {
    id: 'm-2027-09',
    kind: 'month',
    when: '2027-09',
    label: 'Sep 2027',
    title: '1.0, with a promise attached',
    state: 'planned',
    arc: 2,
    goal: 'You can build on SDODS without expecting it to move under you.',
    ships: [
      'A stable 1.0 of the CLI surface and the run format',
      'A written compatibility promise and a deprecation policy',
      'A migration path from every 0.x release',
    ],
    proof: 'A suite written today still runs unchanged on the next minor version.',
  },

  {
    id: 'y-2028',
    kind: 'year',
    when: '2028',
    year: 2028,
    label: '2028',
    title: 'The suite repairs itself and says what it changed',
    state: 'direction',
    arc: 3,
    goal: 'Maintenance stops being the reason automation gets abandoned.',
    ships: [
      'Agents open pull requests for drift, with the heal history as evidence',
      'Coverage gaps found by comparing real traffic against covered journeys',
      'Test data synthesised per environment, sensitive fields never leaving it',
      'Failures clustered by cause, so one incident is one item',
      'Scenarios suggested from a change set, ranked by the risk they cover',
    ],
    proof: 'Most locator drift is fixed and merged without anyone writing a selector.',
  },
  {
    id: 'y-2029',
    kind: 'year',
    when: '2029',
    year: 2029,
    label: '2029',
    title: 'Checks, approvals and the release in one place',
    state: 'direction',
    arc: 4,
    goal: 'Confidence is not only tests: it is who approved, and on what evidence.',
    ships: [
      'Release gates that read the evidence and hold or pass a deployment',
      'Approvals recorded against the run that justified them',
      'Event-driven workflows across environments, data and deployments',
      'Environment provisioning hooks, so a suite can create what it needs',
      'Connectors for the trackers, chat tools and pipelines already in use',
    ],
    proof: 'The release gate becomes the record teams point at when asked why they shipped.',
  },
  {
    id: 'y-2030',
    kind: 'year',
    when: '2030',
    year: 2030,
    label: '2030',
    title: 'An audit trail the people who sign off actually trust',
    state: 'direction',
    arc: 5,
    goal: 'A regulated team can show the chain from requirement to release, complete.',
    ships: [
      'Policy as code: tagging, coverage and approval rules enforced at run time',
      'Federation across organisations, with retention and residency controls',
      'Evidence export shaped for auditors rather than for engineers',
      'Private and on-premises agent runtimes for regulated environments',
      'A signed trail from requirement through run to release',
    ],
    proof: 'An auditor follows one requirement to one release without asking a human.',
  },
];

/** The checkpoint the traveller is standing on. */
export const TODAY_ID = 'm-2026-10';
