import type { Thread } from '../types';

export const configThreads: Thread[] = [
  {
    slug: 'cfg-unresolved-variable-api-token',
    title:
      'Unresolved variable ${API_TOKEN} at "env.api.auth.token" — where is it supposed to look?',
    askedBy: 'dperera',
    askedOn: '2020-10-06',
    tags: ['config', 'api'],
    votes: 44,
    views: 16240,
    body: [
      'Added bearer auth to the staging environment file:',
      '',
      '```yaml',
      'api:',
      '  baseUrl: https://jsonplaceholder.typicode.com',
      '  auth: { type: bearer, token: "${API_TOKEN}" }',
      '```',
      '',
      'Then:',
      '',
      '```bash',
      'sdods run -p demo-shop -e staging -l api',
      '```',
      '',
      'It dies before a single request goes out:',
      '',
      '```text',
      '✖ CONFIG_UNRESOLVED_VAR: Unresolved variable ${API_TOKEN} at "env.api.auth.token".',
      '  hint: Add API_TOKEN=... to .env or .env.<env> (repo root or project folder), or export it in the shell.',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'The value is in a file next to the project yaml called `env.staging`. What am I missing?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2020-10-06',
        votes: 58,
        body: [
          'The file name. `env.staging` is not a name SDODS looks for — the leading dot is part of it.',
          '',
          'For each of two roots (the repo root first, then the project folder) SDODS reads these four names, in this order:',
          '',
          '- `.env`',
          '- `.env.<env>`',
          '- `.env.local`',
          '- `.env.<env>.local`',
          '',
          'So for `-e staging` inside `projects/demo-shop` that is up to eight files, missing ones skipped. Rename yours to `projects/demo-shop/.env.staging` and the run gets past resolution.',
          '',
          'The check itself is not clever: after every layer has merged, the whole tree is walked and any `${VAR}` that has no value and no default throws with the dotted path it sat on. `env.api.auth.token` is telling you exactly which leaf to look at.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'mkuiper',
        on: '2020-10-09',
        votes: 11,
        body: [
          'Worth adding: exporting it in the shell also works and, if you do both, the shell wins.',
          '',
          '```bash',
          'API_TOKEN=abc123 sdods run -p demo-shop -e staging -l api',
          '```',
          '',
          'We keep the real one out of the tree entirely and only commit a `.env.example` listing the names, which is what the generated project scaffolds anyway.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-secret-literal-env-vars-password',
    title:
      'Secret literal at "env.vars.password" — I want the password in the env file, why is that refused?',
    askedBy: 'hsu-wei-lin',
    askedOn: '2020-11-24',
    tags: ['config', 'lint'],
    votes: 36,
    views: 12680,
    body: [
      'Put the login password straight into `projects/demo-shop/envs/staging.yaml` so the data-driven login scenarios can pick it up:',
      '',
      '```yaml',
      'vars:',
      '  defaultProduct: Sauce Labs Backpack',
      '  password: hunter2',
      '```',
      '',
      'Every command now refuses to start:',
      '',
      '```text',
      '✖ CONFIG_SECRET_LITERAL: Secret literal at "env.vars.password". Use ${VAR} and put the value in .env.<env>.',
      '  hint: Replace the value with "${PASSWORD}" and add PASSWORD=... to your .env file.',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'This is a throwaway demo account. Is there a way to say "yes I meant it"?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2020-11-24',
        votes: 49,
        body: [
          'No override, on purpose. The environment files are committed; a key whose name looks like a secret has to hold a `${VAR}` reference and nothing else.',
          '',
          'Do it the way the shipped demo does:',
          '',
          '```yaml',
          'vars:',
          '  standardPassword: "${DEMO_SHOP_PASSWORD:-secret_sauce}"',
          '```',
          '',
          '```bash',
          'echo "DEMO_SHOP_PASSWORD=hunter2" >> projects/demo-shop/.env.staging',
          '```',
          '',
          'The `:-` form gives you a fallback, so a checkout with no `.env.staging` still runs against the public demo site. Steps read it as `{{standardPassword}}` either way.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2020-11-27',
        votes: 12,
        body: [
          'The reason the rule has no escape hatch is that the same check is what lets us promise the yaml is safe to commit and safe to paste into an issue. Once one project has a literal in it, nobody trusts the rest.',
          '',
          'Keep a `.env.example` next to the project with the names and no values — it documents what a new machine needs without carrying anything.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-unknown-project-demo-shp',
    title: 'Unknown project "demo-shp" — how do I list the slugs it actually knows about?',
    askedBy: 'kmoreau',
    askedOn: '2021-02-15',
    tags: ['config', 'cli'],
    votes: 29,
    views: 10410,
    body: [
      '```bash',
      'sdods run -p demo-shp -l api',
      '```',
      '',
      '```text',
      '✖ PROJECT_NOT_FOUND: Unknown project "demo-shp".',
      '  hint: Known projects: demo-shop, rwa-bank, sdods-web.',
      '```',
      '',
      'Fine, that was a typo. But is the hint the whole list, or only the ones that resolved cleanly? I have a half-finished project folder in there too and it does not appear.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2021-02-15',
        votes: 34,
        body: [
          'It is the whole list of discovered projects, and discovery is simple: every directory under `projects/` that contains a `sdods.project.yaml`. A folder without that file is skipped silently, which is why your half-finished one is invisible.',
          '',
          '```bash',
          'sdods project list',
          '```',
          '',
          '![sdods project list showing demo-shop, rwa-bank and sdods-web with their layers, browsers and environments](/questions/project-list.png "The three projects in this repo")',
          '',
          'Note that discovery is not lazy — every project file is parsed on startup. So a project with a broken yaml does not go missing, it takes the whole command down with its own error instead.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'annika-solheim',
        on: '2021-02-16',
        votes: 8,
        body: [
          'Install the completion and you stop typing slugs by hand:',
          '',
          '```bash',
          'sdods completion',
          '```',
          '',
          'Saved me from `demo-shp` about forty times.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-env-qa-not-in-envs-available',
    title:
      'Environment "qa" is not in envs.available [local, staging] — I created envs/qa.yaml already',
    askedBy: 'tobi-schrader',
    askedOn: '2021-05-11',
    tags: ['config', 'cli'],
    votes: 26,
    views: 9240,
    body: [
      'Wrote `projects/demo-shop/envs/qa.yaml` by copying staging.yaml and changing the URLs. Then:',
      '',
      '```bash',
      'sdods run -p demo-shop -e qa -l api',
      '```',
      '',
      '```text',
      '✖ ENV_NOT_FOUND: Environment "qa" is not in envs.available [local, staging] for project demo-shop.',
      '  hint: Add "qa" to envs.available in sdods.project.yaml and create envs/qa.yaml.',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'The file is right there. Why does it also need declaring?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2021-05-11',
        votes: 31,
        body: [
          'Because the declaration is the list, and the file is the detail. `envs.available` is what `project list`, the CI matrix and the web UI enumerate; a stray file in `envs/` is not an environment until the project says it is.',
          '',
          '```yaml',
          'envs:',
          '  default: staging',
          '  available: [local, staging, qa]',
          '```',
          '',
          'The order matters for the error you get next: availability is checked first, file existence second. So if you had done it the other way round — declared `qa` with no file — you would have seen',
          '',
          '```text',
          '✖ ENV_NOT_FOUND: Environment "qa" has no file at /work/shop-tests/projects/demo-shop/envs/qa.yaml',
          '```',
          '',
          'Two errors, two different halves of the same mistake.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2021-05-12',
        votes: 14,
        body: [
          'There is a command that does both halves and keeps the comments in your project yaml intact:',
          '',
          '```bash',
          'sdods env add qa -p demo-shop --ui-url https://qa.example.com --api-url https://api-qa.example.com',
          '```',
          '',
          'It writes `envs/qa.yaml` and appends `qa` to `envs.available`. Add `--default` if it should become the default environment.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'rgarrido',
        on: '2021-05-20',
        votes: 5,
        body: [
          'Also worth knowing that `-e` is not the only way in. The environment is picked in this order: the `-e` flag, then whatever the caller passed programmatically, then `SDODS_ENV`, then `envs.default` from the project file. A leftover `SDODS_ENV=qa` in a shell profile produces exactly this error with no `-e` in sight.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-precedence-which-layer-wins',
    title:
      'Project yaml, env yaml, .env, an exported variable and a flag all set the same thing — which one wins?',
    askedBy: 'vikram-r',
    askedOn: '2021-08-03',
    tags: ['config'],
    votes: 71,
    views: 24980,
    body: [
      'We have base URLs in `envs/staging.yaml`, an old `SDODS_UI_BASE_URL` exported in the build image, and someone has started passing flags on the command line. Nobody can predict what a run will actually hit any more.',
      '',
      'Is there a documented order, or is it whatever merges last?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2021-08-03',
        votes: 86,
        body: [
          'There is an order, it is fixed, and later always wins:',
          '',
          '1. framework defaults (screenshot policy, heal timeouts, retries)',
          '2. `sdods.project.yaml`',
          '3. `envs/<env>.yaml`',
          '4. `.env` and `.env.<env>` (repo root, then the project folder)',
          '5. `process.env`, including the `SDODS_*` variables',
          '6. flags on `sdods run` and friends',
          '',
          'So your exported `SDODS_UI_BASE_URL` beats the env yaml, and a flag beats the exported variable. Merging is per key, not per file: objects merge recursively, arrays replace wholesale.',
          '',
          'You do not have to reason about it in the abstract — ask:',
          '',
          '```bash',
          'sdods config show -p demo-shop -e staging --explain',
          '```',
          '',
          'One row per leaf with the layer that produced it.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2021-08-04',
        votes: 19,
        body: [
          'The bit that trips people is that layers 4 and 5 do two jobs.',
          '',
          'They are the merge layers above, and they are also the only scope `${VAR}` is resolved against. Layer 5 does a third thing on top: a fixed set of `SDODS_*` names is mapped onto configuration paths, so `SDODS_UI_BASE_URL` is not just a variable, it writes `env.ui.baseUrl`.',
          '',
          'The mapped names are listed in the [environment variables reference](https://docs.sdods.com/docs/reference/environment-variables/). Anything not on that list is only a `${VAR}` source.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'j-okonkwo',
        on: '2021-08-11',
        votes: 7,
        body: [
          'Practical footnote from our build: `CI` counts too. When it is set, `retries.ci` applies instead of `retries.local`, so the same command retries twice on the agent and zero times on your laptop. An environment file can force it with `ci: true` if you want that locally.',
        ].join('\n'),
      },
      {
        id: 'a4',
        by: 'tomas-brekke',
        on: '2021-09-02',
        votes: 4,
        body: [
          'And the thing that is deliberately absent from the order: an environment file cannot override arbitrary project keys. It may only patch `screenshots`, `heal`, `timeouts` and `perf` on top of the project section. Everything else in `envs/<env>.yaml` describes the target, not the project.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-no-sdods-project-yaml-in-directory',
    title: 'New folder under projects/ is ignored completely — no error, just not there',
    askedBy: 'elsa-nyman',
    askedOn: '2021-11-09',
    tags: ['config', 'cli'],
    votes: 16,
    views: 5620,
    body: [
      'Made `projects/billing/` by hand with an `envs/local.yaml` in it. `sdods project list` shows demo-shop, rwa-bank and sdods-web and no billing. No warning either.',
      '',
      'Then when I point at it directly I do get something:',
      '',
      '```text',
      '✖ CONFIG_NOT_FOUND: No sdods.project.yaml in /work/shop-tests/projects/billing',
      '  hint: Run `sdods project create <slug>` or `sdods analyze <app>` to create one.',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'Why silent in one place and loud in the other?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2021-11-10',
        votes: 21,
        body: [
          'Because they are different questions.',
          '',
          'Discovery scans `projects/` and treats "directory with a `sdods.project.yaml`" as the definition of a project. A directory without one is not a broken project, it is not a project — build output, a scratch folder, a leftover `node_modules`. Warning about those would make the tool useless in a real repo.',
          '',
          'Loading a specific project root is the other question, and there the missing file is unambiguously an error, which is the message you pasted.',
          '',
          'Between those two you also get the middle case:',
          '',
          '```text',
          '✖ PROJECT_NOT_FOUND: Unknown project "billing".',
          '  hint: Known projects: demo-shop, rwa-bank, sdods-web.',
          '```',
          '',
          'Simplest fix is to let the scaffold write the file:',
          '',
          '```bash',
          'sdods project create billing --ui-url http://localhost:3000 --api-url http://localhost:3000/api --env local',
          '```',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'lena-hartwig',
        on: '2021-11-12',
        votes: 6,
        body: [
          'If the folder already has work in it, `--force` will overwrite an existing directory, so copy anything you care about out first. We hand-wrote the four required keys instead — `slug`, `name`, `layers`, `envs.default` and `envs.available` — and let the schema defaults fill in the rest.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-shell-variable-beats-dotenv-file',
    title: 'Value in .env.staging is ignored, an old exported variable keeps winning',
    askedBy: 'gcastellano',
    askedOn: '2022-02-21',
    tags: ['config', 'ci'],
    votes: 24,
    views: 8460,
    body: [
      'Rotated a credential. `projects/demo-shop/.env.staging` has the new one:',
      '',
      '```text',
      'DEMO_SHOP_PASSWORD=<new>',
      '```',
      '',
      'Runs still authenticate with the old value. `--explain --show-secrets` confirms the old one is in there. Deleting the line from the file changes nothing, which is how I worked out the file is not the source at all.',
      '',
      'Is the dotenv layer cached somewhere?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2022-02-21',
        votes: 37,
        body: [
          'Not cached — outranked. You have `DEMO_SHOP_PASSWORD` exported in that shell.',
          '',
          '```bash',
          'env | grep DEMO_SHOP',
          'unset DEMO_SHOP_PASSWORD',
          '```',
          '',
          'The `.env` files are parsed into a private map and deliberately never injected into `process.env`. If they were injected, the file would silently become indistinguishable from the process layer and would then outrank it — a value you exported on purpose, for one command, would lose to a file you forgot about. So the map is built first and `process.env` is merged over the top of it: shell beats file, always.',
          '',
          'That is the whole of the difference between layer 4 and layer 5.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'sam-orbison',
        on: '2022-02-22',
        votes: 9,
        body: [
          'The other half of this that bit us in CI: the agent image had the variable baked in, so nobody could reproduce it locally after an `unset`. `sdods config show -p demo-shop -e staging` prints the dotenv files it actually read on the second line, which is a fast way to see whether a file is even being picked up before you go hunting in the environment.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-arrays-replace-objects-merge',
    title: 'Added one mask selector in the env file and the other three disappeared',
    askedBy: 'nadia-belkacem',
    askedOn: '2022-05-17',
    tags: ['config', 'visual'],
    votes: 33,
    views: 11090,
    body: [
      'Project file masks three elements for screenshots. Staging has a clock widget that also needs masking, so I added it to `envs/staging.yaml`:',
      '',
      '```yaml',
      'screenshots:',
      '  mask: [\'[data-test="live-clock"]\']',
      '```',
      '',
      'Now the three from the project file are not masked any more and every visual baseline is failing on the cart badge. I expected the lists to be added together.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2022-05-17',
        votes: 41,
        body: [
          'Arrays replace. Objects merge recursively, arrays are treated as one value and the later layer wins outright.',
          '',
          'So write the whole list:',
          '',
          '```yaml',
          'screenshots:',
          '  mask:',
          '    - \'[data-test="shopping-cart-badge"]\'',
          '    - \'[data-test="live-clock"]\'',
          '```',
          '',
          'It reads as duplication and it is, but the alternative is worse: if arrays concatenated there would be no way to remove an entry from a lower layer, and every list in the tree would grow monotonically as you added environments.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'rgarrido',
        on: '2022-05-18',
        votes: 13,
        body: [
          'Same rule, three more places it catches people:',
          '',
          '- `heal.actions` — patch it in an env file with `[click]` and fill, select, assert and the rest stop healing.',
          '- `--process pr-check`, whose `browsers: [chromium]` replaces the project list of chromium, firefox and webkit. That one is intentional but it surprises everybody the first time a PR run only covers one browser.',
          '- repeatable flags like `-b`, which build a list and then replace the project list rather than narrowing it.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'tomas-brekke',
        on: '2022-05-24',
        votes: 6,
        body: [
          'A whole array is one row in the provenance table, so this is visible directly:',
          '',
          '```bash',
          'sdods config show -p demo-shop -e staging --explain',
          '```',
          '',
          'If `project.screenshots.mask` says `envYaml`, the env file owns the entire list and the project file contributed nothing to it.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-slug-does-not-match-directory',
    title: 'Project slug "demo-shop" does not match its directory "demoshop" after a rename',
    askedBy: 'owen-brackley',
    askedOn: '2022-07-05',
    tags: ['config', 'cli'],
    votes: 20,
    views: 7180,
    body: [
      'Renamed the folder to drop the dash. Every command now stops at:',
      '',
      '```text',
      '✖ CONFIG_INVALID: Project slug "demo-shop" does not match its directory "demoshop".',
      '  hint: Rename the directory to demo-shop or set slug: demoshop.',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'I can obviously do either. Which one is the right one, and why does it care at all?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2022-07-05',
        votes: 26,
        body: [
          'Change whichever one is wrong and leave the other alone — the point of the check is that there is only ever one name.',
          '',
          'The slug is the identity everything else addresses the project by: `-p demo-shop` on every command, the folder discovery walks, the run target names, the artefact paths. If the folder and the yaml could disagree, half of those would resolve one way and half the other, and the failure would land somewhere unrelated hours later. So the two are compared the moment the project file is parsed.',
          '',
          'If you actually want the new name, rename both and update the references:',
          '',
          '```bash',
          'git mv projects/demoshop projects/demo-shop',
          '```',
          '',
          'Slugs are lowercase letters, digits and dashes.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'mina-farouk',
        on: '2022-07-06',
        votes: 7,
        body: [
          'One thing to check before you settle on a new slug: anything that already stored runs under the old one keeps them there. We renamed a project and then spent an afternoon wondering where the history went. Not a blocker, just do it deliberately rather than as a drive-by tidy-up.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-cannot-parse-yaml-indentation',
    title:
      'Cannot parse YAML at envs/staging.yaml — all mapping items must start at the same column',
    askedBy: 'sunita-kale',
    askedOn: '2022-09-28',
    tags: ['config'],
    votes: 18,
    views: 6320,
    body: [
      'Added a `use:` block to the staging file and now nothing runs:',
      '',
      '```text',
      '✖ CONFIG_INVALID: Cannot parse YAML at /work/shop-tests/projects/demo-shop/envs/staging.yaml: All mapping items must start at the same column at line 12, column 3',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'Line 12 looks identical to line 11 to me.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2022-09-28',
        votes: 24,
        body: [
          'It will be a tab. Tabs are never valid indentation in YAML, and they line up perfectly in an editor that renders them as spaces.',
          '',
          "That message is the YAML parser talking, not SDODS — the file never gets as far as the schema, which is why you see a parse error rather than a list of field problems. Line and column are the parser's, so they point at the real character.",
          '',
          'Set your editor to insert spaces for `.yaml`, and check the whole tree in one shot before pushing:',
          '',
          '```bash',
          'sdods config validate',
          '```',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'petrov-k',
        on: '2022-09-29',
        votes: 8,
        body: [
          'The other reliable producer of that exact message is a two-space indent under a key that already opened a flow mapping on the same line, e.g.',
          '',
          '```yaml',
          'use: { locale: en-US }',
          '  timezoneId: America/New_York',
          '```',
          '',
          'Pick one style per block — either all flow or all block — and it goes away.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-var-default-syntax',
    title:
      'What does ${DEMO_SHOP_PASSWORD:-secret_sauce} mean, and how does it get past the secret check?',
    askedBy: 'lars-vinter',
    askedOn: '2022-12-06',
    tags: ['config'],
    votes: 23,
    views: 7690,
    body: [
      'The demo staging file ships with this:',
      '',
      '```yaml',
      'vars:',
      '  standardPassword: "${DEMO_SHOP_PASSWORD:-secret_sauce}"',
      '```',
      '',
      'Two questions. What is the `:-` part, and why is a key called `standardPassword` allowed to carry a literal password as a fallback when a plain `password: secret_sauce` is rejected?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2022-12-06',
        votes: 28,
        body: [
          '`${VAR:-default}` uses the default when the variable is absent from both the dotenv layer and the process environment. Without the `:-` an absent variable is a hard error; with it, resolution just falls through.',
          '',
          'And yes, the secret check accepts it. The rule is that the value must be exactly one `${...}` reference and nothing else — a reference with a default still is one. The check is about not committing a value under a name that looks like a credential; it does not try to be a static analysis of what the default happens to be.',
          '',
          "It is only defensible in the demo because the target is a public sandbox and the fallback is that site's published password. For anything real, drop the default: you want the loud failure on a machine where the variable is missing, not a silent run against the wrong credential.",
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-invalid-configuration-zod-issues',
    title:
      'Invalid configuration in envs/staging.yaml with a bullet list — how do I read the paths?',
    askedBy: 'ade-oyinlola',
    askedOn: '2023-01-31',
    tags: ['config'],
    votes: 19,
    views: 6210,
    body: [
      'Hand-edited an environment file and got a list back instead of one message:',
      '',
      '```text',
      '✖ CONFIG_INVALID: Invalid configuration in /work/shop-tests/projects/demo-shop/envs/staging.yaml:',
      '  • ui.baseUrl: Invalid URL',
      '  • api.baseUrl: Invalid input: expected string, received undefined',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'The `api.baseUrl` one confuses me most — it is definitely in the file.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2023-01-31',
        votes: 25,
        body: [
          'Each bullet is one schema issue: the dotted path inside the file, then the reason. Both of yours are real.',
          '',
          '`ui.baseUrl` needs a scheme. `www.saucedemo.com` is not a URL; `https://www.saucedemo.com` is.',
          '',
          '`api.baseUrl` reporting as missing almost always means the indentation put it somewhere else — under `ui`, or at the top level — so the `api` block genuinely has no `baseUrl`. Check the column of the key, not its spelling:',
          '',
          '```yaml',
          'ui:',
          '  baseUrl: https://www.saucedemo.com',
          'api:',
          '  baseUrl: https://jsonplaceholder.typicode.com',
          '  headers: { Accept: application/json }',
          '```',
          '',
          'The paths are relative to the file, so `ui.baseUrl` here, not `env.ui.baseUrl`. The `env.` prefix only appears once the file has become part of the resolved tree — that is why unresolved-variable errors carry it and schema errors do not.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'ify-adeyemi',
        on: '2023-02-12',
        votes: 9,
        body: [
          'Run it as a pre-push hook and you never see this on a build agent:',
          '',
          '```bash',
          'sdods config validate',
          '```',
          '',
          'It resolves every project against every environment it declares and stops at the first failure, exit 2.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'annika-solheim',
        on: '2023-02-14',
        votes: 4,
        body: [
          'Both the project file and the environment file go through the same reporting, so the same bullet format shows up for `sdods.project.yaml` too. The file path on the first line is the only thing that tells you which one you broke — worth reading before you go editing the wrong file, which I have now done twice.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-explain-provenance-table-envyaml',
    title: 'config show --explain says envYaml for a value that came out of .env.staging',
    askedBy: 'renata-kohl',
    askedOn: '2023-03-22',
    tags: ['config', 'cli'],
    votes: 28,
    views: 9130,
    body: [
      '```bash',
      'sdods config show -p demo-shop -e staging --explain',
      '```',
      '',
      '```text',
      'path                              layer    value',
      'env.api.baseUrl                   envYaml  https://jsonplaceholder.typicode.com',
      'env.ui.baseUrl                    envYaml  https://www.saucedemo.com',
      'env.vars.standardPassword         envYaml  ***',
      'project.screenshots.onlyOnFailure envYaml  false',
      'project.screenshots.policy.@smoke project  scenario',
      'runtime.retries                   defaults 0',
      '```',
      '',
      'The documented layer names include `dotenv`, but `standardPassword` is only in the yaml as a `${VAR}` and its actual value comes from `.env.staging`. Why does the row say `envYaml` and not `dotenv`?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2023-03-22',
        votes: 33,
        body: [
          'Because the column answers "which layer owns this path", and the dotenv layer does not own paths — it supplies variables.',
          '',
          'The two things happen in a fixed order. First every layer merges and the winning layer is recorded per leaf. Then, once the tree is final, `${VAR}` references inside those values are substituted. The string `${DEMO_SHOP_PASSWORD}` was written by `envs/staging.yaml`, so the leaf belongs to `envYaml`; the dotenv layer changed what that string reads as, not who put it there.',
          '',
          'That is also why a value substituted from the shell shows `envYaml` and not `processEnv`, while `SDODS_UI_BASE_URL` — which writes a path directly rather than filling in a reference — really does show `processEnv`.',
          '',
          'For the variable side of the picture, the plain `config show` prints the dotenv files it read, and `sdods doctor -p demo-shop` reports whether each reference resolves.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'vikram-r',
        on: '2023-03-23',
        votes: 11,
        body: [
          '`***` in that table is redaction by key name, not a marker that the value came from somewhere secret. Two flags to know:',
          '',
          '```bash',
          'sdods config show -p demo-shop -e staging --explain --show-secrets',
          'sdods --json config show -p demo-shop -e staging --explain',
          '```',
          '',
          'The first prints them; the second gives you the same rows as JSON, which is far easier to diff between two environments than the table.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'helle-borg',
        on: '2023-11-02',
        votes: 5,
        body: [
          'Late, but for anyone diffing environments: pipe the JSON form through a sort on `path` and compare local against staging. Ninety per cent of "works on my machine" turns out to be one row where the layer differs, not the value.',
        ].join('\n'),
      },
    ],
  },

  {
    slug: 'cfg-exit-code-2-in-ci',
    title: 'CI job exits 2 with no test results and an empty report — what is code 2?',
    askedBy: 'yusuf-demir',
    askedOn: '2023-05-16',
    tags: ['config', 'ci', 'cli'],
    votes: 25,
    views: 8020,
    body: [
      'Pipeline step fails, the report artefact is empty, and the only thing in the log is the process exiting 2. When tests actually fail we get 1 and a report. What is 2?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2023-05-16',
        votes: 30,
        body: [
          'Configuration or usage error. Nothing ran, which is why there is no report.',
          '',
          '```text',
          '0    success',
          '1    failure — scenario failures, a gate not met, an unexpected runtime error',
          '2    configuration or usage error',
          '3    lint errors',
          '130  cancelled',
          '```',
          '',
          'Everything in this area lands on 2: unknown project, an environment that is not declared or has no file, invalid YAML, a schema issue, an unresolved `${VAR}`, a literal secret, a bad flag value.',
          '',
          'The message is on stderr rather than in the report. If your CI only captures stdout, that is why the log looks empty — add `--json` and you get the structured error as one JSON line on stderr with `code`, `message`, `hint` and `docsUrl`.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2023-05-17',
        votes: 12,
        body: [
          'Make it its own step so the failure names itself:',
          '',
          '```bash',
          'sdods config validate',
          '```',
          '',
          'Then the pipeline distinguishes "the config is broken" from "the tests are red" without anybody reading exit codes. Same trick for lint, which is code 3 — `sdods run` lints first, so a tag mistake also stops you before any browser starts.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-which-key-names-count-as-secrets',
    title:
      'Which key names does the secret check actually match? tokenUrl is fine but standardPassword is not',
    askedBy: 'thom-vasseur',
    askedOn: '2023-07-11',
    tags: ['config'],
    votes: 27,
    views: 8570,
    body: [
      'Trying to work out the rule from the outside. These are all accepted as literals:',
      '',
      '```yaml',
      'auth:',
      '  tokenUrl: https://id.example.com/oauth/token',
      '  passwordSelector: "#password"',
      '  tokenPlacement: { kind: header, name: Authorization }',
      '```',
      '',
      'This is rejected:',
      '',
      '```yaml',
      'vars:',
      '  standardPassword: secret_sauce',
      '```',
      '',
      'So it is not an exact-name list and it is not a "contains password" list either. What is it?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2023-07-11',
        votes: 34,
        body: [
          'It is a case-insensitive substring match with a short exemption list on the suffix.',
          '',
          'A key is treated as secret if its name contains any of `password`, `secret`, `token`, `apiKey`, `api_key`, `clientSecret` or `client_secret`. Substring, so `standardPassword` and `refreshToken` match as surely as `password` does — which is the point, since renaming the key was the obvious way around it.',
          '',
          'It is then exempted if the name ends in `url`, `env`, `selector` or `placement`. That is exactly your three: `tokenUrl` is an endpoint, `tokenEnv` is a variable name, `passwordSelector` is a CSS selector, `tokenPlacement` is a structure. None of them can hold a credential, so requiring `${VAR}` there would be noise.',
          '',
          'An empty string is also allowed, so `token: ""` passes.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'ify-adeyemi',
        on: '2023-07-12',
        votes: 10,
        body: [
          'Consequence worth spelling out: the integrations and MCP sections store the names of variables rather than their values, and the field names say so — `tokenEnv`, `emailEnv`, `envFrom`, `headersFrom`. If you find yourself wanting to put a value in one of those, you have the wrong field.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'tomas-brekke',
        on: '2023-07-19',
        votes: 6,
        body: [
          'Same name pattern drives redaction elsewhere, so a key you name `apiKey` is masked in `config show` output and in the logs whether or not its value is a reference. Naming a non-secret field `sessionToken` will get it starred out in places you did not expect.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-environment-qa-has-no-file',
    title: 'Environment "qa" has no file at projects/demo-shop/envs/qa.yaml',
    askedBy: 'chandra-p',
    askedOn: '2023-09-12',
    tags: ['config', 'cli'],
    votes: 17,
    views: 5610,
    body: [
      'Declared it in the project file:',
      '',
      '```yaml',
      'envs:',
      '  default: staging',
      '  available: [local, staging, qa]',
      '```',
      '',
      '```bash',
      'sdods run -p demo-shop -e qa -l api',
      '```',
      '',
      '```text',
      '✖ ENV_NOT_FOUND: Environment "qa" has no file at /work/shop-tests/projects/demo-shop/envs/qa.yaml',
      '  hint: Run `sdods env add qa --project demo-shop --ui-url ... --api-url ...`.',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'Does an environment have to have a file? I only wanted the name to exist so CI could pass it through.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2023-09-12',
        votes: 22,
        body: [
          'Yes. The file is what an environment consists of — the UI and API base URLs are required fields, and there is nothing sensible to run against without them.',
          '',
          'A declared name with no file is the half-finished state, and this error is the other side of the one you get when the file exists but the name is undeclared. Availability is checked first, so you only ever see one of the two.',
          '',
          '```bash',
          'sdods env add qa -p demo-shop --ui-url https://qa.example.com --api-url https://api-qa.example.com',
          '```',
          '',
          'If CI is meant to point the same environment somewhere else per branch, create the file with sensible defaults and override at run time with `SDODS_UI_BASE_URL` and `SDODS_API_BASE_URL`.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'thom-vasseur',
        on: '2023-09-13',
        votes: 8,
        body: [
          'Both mismatches show up without running anything:',
          '',
          '```bash',
          'sdods project list',
          'sdods env list -p demo-shop',
          'sdods doctor -p demo-shop',
          '```',
          '',
          '`project list` marks environments whose file is missing, and `env list` prints the base URLs per environment or the error that stops it resolving.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-per-environment-base-urls-structure',
    title:
      'Four environments, same app — how should base URLs be laid out so nobody copies the wrong one?',
    askedBy: 'helle-borg',
    askedOn: '2023-11-14',
    tags: ['config'],
    votes: 21,
    views: 6740,
    body: [
      'We are moving off a home-grown runner where the base URL was a giant switch statement in a helper. Four targets: a stack we bring up on the laptop, a shared dev box, staging and a read-only production smoke.',
      '',
      'What does the idiomatic layout look like here? One file per target, or one file with a map inside it?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2023-11-14',
        votes: 26,
        body: [
          'One file per target, always. An environment is one file under `envs/`, and its name is the file name:',
          '',
          '```text',
          'projects/shop/',
          '  sdods.project.yaml',
          '  envs/local.yaml',
          '  envs/dev.yaml',
          '  envs/staging.yaml',
          '  envs/prod-smoke.yaml',
          '```',
          '',
          '```yaml',
          'name: staging',
          'ui: { baseUrl: https://staging.example.com }',
          'api:',
          '  baseUrl: https://api-staging.example.com',
          '  headers: { Accept: application/json }',
          '  auth: { type: bearer, token: "${SHOP_API_TOKEN}" }',
          'users: { poolSize: 4 }',
          '```',
          '',
          'Then declare them so the tooling can enumerate them:',
          '',
          '```yaml',
          'envs:',
          '  default: staging',
          '  available: [local, dev, staging, prod-smoke]',
          '```',
          '',
          'A map inside one file would defeat the whole design — `-e` selects a file, provenance reports per environment, and secrets live in a `.env.<env>` named after it.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'thom-vasseur',
        on: '2023-11-15',
        votes: 11,
        body: [
          'Two things that stopped us hard-coding URLs anywhere else:',
          '',
          'Put paths in `routes:` in the project file rather than in steps, so a scenario says `goto(cart)` and the environment supplies the origin.',
          '',
          'And for the read-only production target, use the per-environment overrides for the things that should differ in anger — `timeouts`, `retries` via `ci: true`, `screenshots` — instead of forking the project file.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'j-okonkwo',
        on: '2023-11-21',
        votes: 7,
        body: [
          'If the same environment answers on more than one origin — a vanity domain and an internal one, say — put the extras in `aliases:` rather than making a second environment. The recorder rewrites them back to routes, so a flow recorded against the internal host still replays against the public one.',
        ].join('\n'),
      },
    ],
  },

  {
    slug: 'cfg-project-dotenv-beats-repo-root',
    title: 'Repo-root .env and a project .env both set the same name — which one is used?',
    askedBy: 'nikhil-sane',
    askedOn: '2024-02-20',
    tags: ['config'],
    votes: 15,
    views: 4830,
    body: [
      'Monorepo with three projects. There is a `.env` at the repo root with shared values, and each project has its own `.env.staging`. If both define `API_TOKEN`, which is used, and is that documented anywhere or just an accident of ordering?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2024-02-20',
        votes: 20,
        body: [
          'The project one, and it is deliberate.',
          '',
          'Two roots are read, repo root first and then the project folder, and within each root four names in this order: `.env`, `.env.<env>`, `.env.local`, `.env.<env>.local`. Every file is merged over what came before, so later assignment wins. That gives you, from weakest to strongest:',
          '',
          '1. repo `.env`',
          '2. repo `.env.staging`',
          '3. repo `.env.local`',
          '4. repo `.env.staging.local`',
          '5. project `.env`',
          '6. project `.env.staging`',
          '7. project `.env.local`',
          '8. project `.env.staging.local`',
          '',
          'The root is for what every project shares; the project folder is for what one project needs, and it is more specific, so it wins. Missing files are skipped, and the whole stack still loses to an exported variable.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-unknown-module-name-versus-path',
    title: 'Unknown module "api" for project demo-shop — but features/api/ exists',
    askedBy: 'fiona-mcallister',
    askedOn: '2024-04-29',
    tags: ['config', 'cli'],
    votes: 14,
    views: 4460,
    body: [
      '```bash',
      'sdods run -p demo-shop -e staging -m api',
      '```',
      '',
      '```text',
      '✖ CONFIG_INVALID: Unknown module "api" for project demo-shop.',
      '  hint: Known modules: auth, inventory, cart, posts-api, hybrid.',
      '```',
      '',
      'The directory is `features/api/`, so where does `posts-api` come from? `-m cart` works and that folder is `features/cart/`.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2024-04-29',
        votes: 19,
        body: [
          '`-m` takes the module name, not the folder. They are usually the same because `path` defaults to the name, but they do not have to be:',
          '',
          '```yaml',
          'modules:',
          '  - name: posts-api',
          '    title: Posts API',
          '    path: api',
          '    layers: [api]',
          '```',
          '',
          'So `cart` works because that module never set `path`, and `api` fails because it is a folder, not a module.',
          '',
          '```bash',
          'sdods run -p demo-shop -e staging -m posts-api',
          '```',
          '',
          'The hint always lists the real names, which is the fastest way to check without opening the yaml.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'bea-lindqvist',
        on: '2024-04-30',
        votes: 6,
        body: [
          'The names are also what the module carries elsewhere — its testing types, the tag every scenario in it should have, its owner and Jira component. Keeping `name` readable and letting `path` be whatever the folder is called historically is fine; we did the reverse for a while and ended up with a module called `svc-2`.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-process-not-defined-typo',
    title: 'Process "pr-chek" is not defined for project demo-shop — where do processes come from?',
    askedBy: 'bea-lindqvist',
    askedOn: '2024-06-11',
    tags: ['config', 'ci', 'cli'],
    votes: 16,
    views: 5090,
    body: [
      '```bash',
      'sdods run -p demo-shop --process pr-chek',
      '```',
      '',
      '```text',
      '✖ CONFIG_NOT_FOUND: Process "pr-chek" is not defined for project demo-shop.',
      '  hint: Known processes: pr-check, nightly-regression, release-gate, api-contract. Define it under processes: in sdods.project.yaml or defaults.processes in sdods.workspace.yaml.',
      '```',
      '',
      'Typo, obviously. But the hint mentions two files — how do those two lists combine? We have `pr-check` in both.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2024-06-11',
        votes: 21,
        body: [
          'By name, project last.',
          '',
          "The workspace `defaults.processes` are collected first, then the project's own `processes:` are applied over them. Same name replaces outright; a new name is added. So a `pr-check` in the project file is the whole of the `pr-check` you get, and the workspace one contributes nothing to it — not even the fields the project omitted.",
          '',
          'That is the array-replace rule again, applied per entry rather than per list.',
          '',
          '```bash',
          'sdods processes list -p demo-shop',
          '```',
          '',
          'That prints the merged result: name, trigger, tags, layers, browsers, env, gates and schedule, which is what a run with `--process` will actually use.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'nikhil-sane',
        on: '2024-06-12',
        votes: 8,
        body: [
          'And explicit flags beat the process. `--process nightly-regression -b chromium` runs the nightly tag expression on one browser rather than three, which is handy for reproducing a nightly failure locally without editing the yaml.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-invalid-shard-format',
    title: 'Invalid shard "1-3", expected "<current>/<total>" like 1/3',
    askedBy: 'bruno-teixeira',
    askedOn: '2024-08-08',
    tags: ['config', 'ci', 'cli'],
    votes: 13,
    views: 4120,
    body: [
      'Our matrix generates the shard string and we used a dash because a slash was awkward to quote in the pipeline file.',
      '',
      '```text',
      '✖ CONFIG_INVALID: Invalid shard "1-3", expected "<current>/<total>" like 1/3.',
      '  docs: https://docs.sdods.com/docs/guides/configuration',
      '```',
      '',
      'Is a dash form supported anywhere, or is it slash only?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2024-08-08',
        votes: 17,
        body: [
          'Slash only, one form: `<current>/<total>`, both integers, `1/3` through `3/3`. Whitespace around the slash is tolerated; nothing else is.',
          '',
          '```bash',
          'sdods run -p demo-shop -e staging --shard 1/3',
          '```',
          '',
          '`SDODS_SHARD` takes the same string and goes through the same parser, so if the flag is awkward to quote, set the variable instead:',
          '',
          '```bash',
          'SDODS_SHARD=1/3 sdods run -p demo-shop -e staging',
          '```',
          '',
          'Whichever way you pass it, a malformed value fails immediately with exit 2 rather than silently running everything on every shard — which is the failure you actually want, because the silent version looks like a passing build with triple the runtime.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-keeping-secrets-out-of-git',
    title:
      'Team-wide setup for keeping credentials out of the repo — what actually works day to day?',
    askedBy: 'anouk-devries',
    askedOn: '2024-10-02',
    tags: ['config', 'ci'],
    votes: 31,
    views: 9260,
    body: [
      'We are onboarding six more testers and the current answer is "ask someone in chat for the staging password". I would like to write down one way of doing this that survives contact with people who are not going to read a wiki page.',
      '',
      'What does a working setup look like — files, gitignore, CI, and what a new laptop has to do on day one?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2024-10-02',
        votes: 27,
        body: [
          'Four rules and the tooling enforces two of them for you.',
          '',
          '1. YAML holds references, never values. A key that looks like a credential must be `${VAR}` or resolution refuses to start, so this one polices itself.',
          '2. Values live in `.env.<env>` beside the project, and `.env*` is gitignored except `.env.example`.',
          '3. `.env.example` lists every name with no value. It is the day-one checklist and it is reviewed like code, so a new variable arrives with its documentation.',
          '4. On a build agent there are no files at all — export the names from the secret store. The process layer sits above the file layer, so the same project works unchanged.',
          '',
          '```text',
          '.env',
          '.env.*',
          '!.env.example',
          '```',
          '',
          'Day one for a new laptop is then: clone, copy `.env.example` to `.env.staging`, fill in the four values, run `sdods doctor -p demo-shop`.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2024-10-03',
        votes: 15,
        body: [
          'Adding the CI half properly, because this is where people reach for a committed file.',
          '',
          'Export in the job environment, do not write a `.env` in a build step. Two reasons: an exported variable outranks any file, so a stray file on the agent cannot shadow it; and a file written by a step tends to survive into the artefact upload.',
          '',
          'Then put a validation step before the run so a missing secret fails in five seconds with a name, rather than twenty minutes in with an auth failure:',
          '',
          '```bash',
          'sdods config validate',
          '```',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'helle-borg',
        on: '2024-10-08',
        votes: 9,
        body: [
          'One thing people miss: integrations and MCP servers store the names of variables rather than their values — `tokenEnv`, `emailEnv`, `envFrom`, `headersFrom`. So the GitHub and Jira config is safe to commit in full, and if you find yourself pasting a token into one of those fields you are in the wrong field.',
          '',
          'Logs, HAR files and screenshots are redacted by the same key pattern plus your `mask` selectors, which is worth knowing before you attach a trace to a ticket.',
        ].join('\n'),
      },
      {
        id: 'a4',
        by: 'sam-orbison',
        on: '2024-11-19',
        votes: 6,
        body: [
          'Counterpoint on rule 3 only: we found `.env.example` drifts unless something checks it. We added a step that greps the referenced variable names out of the yaml and diffs them against the example file. Crude, but it caught two missing entries in the first month.',
        ].join('\n'),
      },
    ],
  },

  {
    slug: 'cfg-browsers-key-in-env-yaml-ignored',
    title: 'browsers: [chromium] in envs/local.yaml does nothing and raises no error',
    askedBy: 'petrov-k',
    askedOn: '2024-12-03',
    tags: ['config', 'ui'],
    votes: 18,
    views: 5480,
    body: [
      'Wanted local runs on chromium only while staging keeps all three, so I put this in `envs/local.yaml`:',
      '',
      '```yaml',
      'browsers: [chromium]',
      '```',
      '',
      'No error. `sdods run -p demo-shop -e local -l ui --list` still lists chromium, firefox and webkit targets. If the key is wrong I would rather be told.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2024-12-03',
        votes: 23,
        body: [
          'There is no `browsers` key in the environment schema, and unknown keys are dropped rather than rejected — so your line is parsed, discarded, and never reaches anything.',
          '',
          'Browsers are a project-level decision. An environment describes where the app is, not how you drive it, and the only project sections an environment file may patch are `screenshots`, `heal`, `timeouts` and `perf`.',
          '',
          'Three ways to get what you want:',
          '',
          '```bash',
          'sdods run -p demo-shop -e local -l ui -b chromium',
          '```',
          '',
          'a process with `browsers: [chromium]` for the recipe you repeat, or `SDODS_*` in a shell profile if it is really per-machine. The flag is layer 6 and wins over everything.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'sam-orbison',
        on: '2024-12-04',
        votes: 8,
        body: [
          'You can prove it in one command rather than by running a suite:',
          '',
          '```bash',
          'sdods config show -p demo-shop -e local --explain',
          '```',
          '',
          '`project.browsers` will say `project`. If the env file had contributed anything the layer would read `envYaml`.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-several-projects-pass-project',
    title: 'Several projects found; pass --project <slug> — it used to work without one',
    askedBy: 'sergio-alcaraz',
    askedOn: '2025-02-11',
    tags: ['config', 'cli'],
    votes: 12,
    views: 3620,
    body: [
      'We had one project and every command worked bare. Added a second one this week and now:',
      '',
      '```text',
      '✖ PROJECT_NOT_FOUND: Several projects found; pass --project <slug>.',
      '  hint: Known projects: demo-shop, rwa-bank.',
      '```',
      '',
      'Is there a way to nominate a default project so the old commands keep working?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2025-02-11',
        votes: 16,
        body: [
          'No default, and that is the intent. The rule is narrow: when exactly one project is discovered it is used; otherwise `-p` is required.',
          '',
          'The alternative would be a default project stored somewhere, and then "which project did that run touch" becomes a question you cannot answer from the command in the pull request. With two projects, the slug is the cheapest disambiguation there is.',
          '',
          'The third state in that family, for completeness, is an empty repo:',
          '',
          '```text',
          '✖ PROJECT_NOT_FOUND: No projects found.',
          '  hint: Run `sdods project create <slug>`.',
          '```',
          '',
          'Shell aliases are the usual workaround — `alias sdshop="sdods -p demo-shop"` and so on.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-workspace-not-declared-in-workspace-yaml',
    title: 'Project references workspace "payments" which is not declared in sdods.workspace.yaml',
    askedBy: 'tanvi-bhatt',
    askedOn: '2025-03-27',
    tags: ['config'],
    votes: 14,
    views: 4090,
    body: [
      'Put `workspace: payments` in a new project so it would not sit with the rest. Now every command in the repo fails, including ones about other projects:',
      '',
      '```text',
      '✖ CONFIG_INVALID: Project "billing" references workspace "payments" which is not declared in sdods.workspace.yaml.',
      "  hint: Declared workspaces: default, platform-qa. Add it to workspaces[] or fix the project's workspace: field.",
      '```',
      '',
      'Why does one project break `sdods project list` for all of them?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2025-03-27',
        votes: 18,
        body: [
          'Because discovery is eager: every project under `projects/` is parsed and checked on startup, before any command decides which project it cares about. A repo where one project is misfiled is a repo with a broken hierarchy, and finding that out only when you happen to name that project would be worse.',
          '',
          'Declare it and everything comes back:',
          '',
          '```yaml',
          'workspaces:',
          '  - { slug: default, name: Default workspace, organization: sdods }',
          '  - { slug: platform-qa, name: Platform QA, organization: sdods }',
          '  - { slug: payments, name: Payments, organization: sdods }',
          'defaultWorkspace: default',
          '```',
          '',
          'There are two siblings of this error you will meet eventually:',
          '',
          '```text',
          '✖ CONFIG_INVALID: Project "billing" references organization "acme" but this repo belongs to "sdods".',
          '✖ CONFIG_INVALID: defaultWorkspace "payments" is not declared in workspaces[] of /work/shop-tests/sdods.workspace.yaml.',
          '```',
          '',
          'One repo is one organization; workspaces are how you split teams inside it.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'sergio-alcaraz',
        on: '2025-03-28',
        votes: 6,
        body: [
          'Omitting `workspace:` entirely is also legal — the project then joins `defaultWorkspace`. We only set it explicitly on the projects that genuinely belong elsewhere, which keeps the diff small when the workspace list changes.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'gcastellano',
        on: '2025-04-14',
        votes: 4,
        body: [
          'To see the result rather than guess at it:',
          '',
          '```bash',
          'sdods workspace tree',
          '```',
          '',
          'Organization, then workspaces, then the projects in each with their modules and processes. It is the quickest check that a project landed where you meant it to.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-sharing-config-between-projects',
    title: 'Three projects with nearly identical settings — how much can actually be shared?',
    askedBy: 'koen-vermeulen',
    askedOn: '2025-06-10',
    tags: ['config'],
    votes: 22,
    views: 6180,
    body: [
      'Our three project files are 80% the same: same browsers, same suites, same four processes, same timeouts. Every change is a three-file change and one of them always gets missed.',
      '',
      'Is there an include or an extends, or is the workspace file the answer?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2025-06-10',
        votes: 24,
        body: [
          'No includes, no extends. The one sharing mechanism that carries real weight is `defaults.processes` in `sdods.workspace.yaml`:',
          '',
          '```yaml',
          'defaults:',
          '  processes:',
          '    - { name: pr-check, trigger: pr, tags: "@smoke", browsers: [chromium], harMode: replay, gates: { minPassRate: 100 } }',
          '    - { name: nightly-regression, trigger: nightly, tags: "@regression", browsers: [chromium, firefox, webkit], notify: [github] }',
          '```',
          '',
          'Those are visible to every project, and a project overrides one by defining the same name. That covers the part you actually change often — the run recipes — and it is one file.',
          '',
          'For the rest, keep it explicit per project. A project file that states its own browsers and timeouts is a file you can read on its own and reason about, and the merge rules stay a straight line from defaults to flags. Three files that agree is a smaller problem than an inheritance chain you have to simulate in your head to answer "what will this run do".',
          '',
          'If it really is one application, consider whether it should be one project with several modules instead of three projects.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'tanvi-bhatt',
        on: '2025-06-11',
        votes: 10,
        body: [
          "What we do share and would recommend: a repo-root `.env` for the values every project needs, so credentials are declared once. That layer is read before each project's own files, so a project can still override a name locally.",
          '',
          'We also keep shared step definitions and page-object base classes in one package the three projects import. That is where the duplication actually hurt, far more than the yaml did.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'priya-venkatesh',
        on: '2025-06-12',
        votes: 8,
        body: [
          'Do not share environment files though. Every one we have seen turn into a shared file ended up with `if project == x` logic smuggled in as variables, and then the base URL for staging depended on which project read the file.',
          '',
          'Environments are per project because they describe one deployment of one application.',
        ].join('\n'),
      },
      {
        id: 'a4',
        by: 'ify-adeyemi',
        on: '2025-07-30',
        votes: 5,
        body: [
          'Practical middle ground we settled on: a small script in CI that diffs the three project files against each other and prints the keys that differ. It does not enforce anything, it just makes the drift visible in the pull request, which turned out to be enough.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-null-clears-a-key-where',
    title: 'Docs say null clears a key and undefined is skipped — where does that apply, exactly?',
    askedBy: 'mina-farouk',
    askedOn: '2025-07-22',
    tags: ['config'],
    votes: 13,
    views: 3740,
    body: [
      'The merge rules say objects merge, arrays replace, `undefined` is skipped and `null` clears a key. The first two I have hit in practice. The last two I cannot reproduce — putting `mask: null` in an environment file gives me a schema error, not a cleared key.',
      '',
      'Am I using it in the wrong place?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2025-07-22',
        votes: 19,
        body: [
          'Yes — the two rules live in different places, and neither is where you looked.',
          '',
          '`null` clears a key during a merge that happens before validation. That is the project file: framework defaults are merged with `sdods.project.yaml` and the result is then parsed. So a `null` there removes the key from the merged object, and the schema default takes over for it — which usually means you get the default back rather than nothing. In an environment file the order is reversed, the file is parsed first, so `mask: null` is a type error exactly as you saw.',
          '',
          '`undefined` skipped is the flag layer, and it is what makes flags usable at all: a flag you did not pass is undefined and never overwrites the yaml. Without that rule every unpassed flag would blank out the value beneath it.',
          '',
          'Also worth knowing: a bare `mask:` in YAML with nothing after it is `null`, not "unset". People write that meaning "leave it alone" and get the other behaviour.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-dataset-var-from-env-file',
    title: 'Does ${VAR} in a CSV dataset resolve from .env.staging, or only from the shell?',
    askedBy: 'rasha-halabi',
    askedOn: '2025-09-04',
    tags: ['config', 'data', 'data-driven'],
    votes: 17,
    views: 4610,
    body: [
      "Our `data/common/users.csv` has a password column holding `${TEST_MEMBER_PASSWORD}` so the value is not in the repo. It works on my machine, where the variable is exported. On a colleague's machine, where it is only in `projects/demo-shop/.env.staging`, the logins fail — and not with a config error, just a failed login.",
      '',
      'Is the dotenv layer supposed to reach dataset rows, or is the shell the only source there?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2025-09-04',
        votes: 22,
        body: [
          'It is supposed to reach them, and it does — dataset rows are interpolated with the same variable scope the YAML was, which is the dotenv layer with `process.env` merged over the top. So `.env.staging` is a valid home for that value.',
          '',
          'Which means your colleague has a different problem, and the reason it looks like this one is the second half of the design: unresolved references in dataset rows are kept rather than thrown on. A row can legitimately contain `${...}` that is not a variable at all, so failing the run would be wrong. The cost is that a typo travels all the way to the login form as the literal string `${TEST_MEMBER_PASSWORD}` and surfaces as a rejected credential.',
          '',
          'Check the spelling on both sides and check which file it is in — the `.env.staging` has to be at the repo root or in the project folder, and the `-e` has to be `staging` for `.env.staging` to be read at all.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2025-09-05',
        votes: 9,
        body: [
          'Worth stepping back: if every row has the same password, the reference in the CSV is doing no work. Put the credential in the environment file as a `vars:` entry and let the steps read `{{standardPassword}}`; keep the dataset for the things that genuinely vary per row.',
          '',
          'If the accounts differ per row and must not collide between workers, that is what the user pool is for rather than a shared column.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'devon-marsh',
        on: '2025-11-28',
        votes: 4,
        body: [
          'Hit this exact thing. What made it obvious was grepping the trace for the literal `${` — if it shows up in a request body or a form fill, it is an unresolved reference and not a wrong password.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-sdods-ui-base-url-shadows-env-choice',
    title:
      'SDODS_UI_BASE_URL in the build image overrides -e staging and there seems to be no flag to beat it',
    askedBy: 'devon-marsh',
    askedOn: '2025-11-19',
    tags: ['config', 'ci'],
    votes: 3,
    views: 231,
    body: [
      'Our agent image exports `SDODS_UI_BASE_URL=http://localhost:3000` for an unrelated tool. Runs pick the staging environment correctly — the API side goes to the staging API — but every browser lands on localhost.',
      '',
      '```bash',
      'sdods run -p demo-shop -e staging -l ui -b chromium -t @smoke',
      'sdods config show -p demo-shop -e staging --explain',
      '```',
      '',
      '```text',
      'env.ui.baseUrl   processEnv  http://localhost:3000',
      'env.api.baseUrl  envYaml     https://jsonplaceholder.typicode.com',
      '```',
      '',
      'So I understand what is happening — the mapped variable writes the path directly and sits above the env file. What I cannot work out is whether `-e` is meant to win here, since selecting an environment and then not using its base URL feels like it defeats the point. And `run` does not seem to take a `--ui-base-url` to override it back from layer 6.',
      '',
      'Is unsetting the variable the only route, or is there something on the run command I have missed?',
    ].join('\n'),
    answers: [],
  },

  {
    slug: 'cfg-config-validate-as-a-ci-gate',
    title:
      'Catching broken configuration in the pull request instead of ten minutes into the suite',
    askedBy: 'anouk-devries',
    askedOn: '2026-01-15',
    tags: ['config', 'ci', 'cli'],
    votes: 10,
    views: 2380,
    body: [
      'Twice this month a pull request that only touched an environment file went green on review and then took the nightly down. Both times it was something a schema check would have caught in a second.',
      '',
      'What is the right gate to add, and where in the pipeline does it go?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2026-01-15',
        votes: 15,
        body: [
          'Its own step, before anything installs a browser:',
          '',
          '```bash',
          'sdods config validate',
          '```',
          '',
          'That resolves every project against every environment it declares — YAML parse, schema, `${VAR}` resolution, secret literals, the workspace checks — and exits 2 on the first failure. It runs in about a second and needs nothing but the repo.',
          '',
          'One thing to get right: on an agent there are no `.env` files, so every reference has to come from the job environment. That is a feature here — validate will fail loudly on a variable your laptop happens to have and the agent does not, which is the class of bug that otherwise only appears at three in the morning.',
          '',
          'Then order the rest by cost: validate (exit 2), lint (exit 3), run (exit 1).',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2026-01-16',
        votes: 7,
        body: [
          'We pair it with a machine check on the same step:',
          '',
          '```bash',
          'sdods doctor --json',
          '```',
          '',
          'Validate answers "is the configuration coherent"; doctor answers "can this machine act on it" — node, browsers, the variables per project and environment, the database. On a fresh runner image the second one is what actually breaks.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-which-dotenv-files-are-read',
    title: 'Exactly which .env files get read, in which order, and how do I confirm it?',
    askedBy: 'ingrid-solberg',
    askedOn: '2026-03-03',
    tags: ['config'],
    votes: 9,
    views: 2040,
    body: [
      'I have inherited a repo with `.env`, `.env.local`, `.env.staging` and `.env.staging.local` at the root and two more inside the project folder. Nobody remembers why.',
      '',
      'Before I delete any of them: what is the full list of names that are read, and is there a way to see which ones a given run actually picked up?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2026-03-03',
        votes: 14,
        body: [
          'Four names, two roots, eight possible files. For `-e staging` from a repo root with a project at `projects/demo-shop`:',
          '',
          '```text',
          '<root>/.env',
          '<root>/.env.staging',
          '<root>/.env.local',
          '<root>/.env.staging.local',
          '<root>/projects/demo-shop/.env',
          '<root>/projects/demo-shop/.env.staging',
          '<root>/projects/demo-shop/.env.local',
          '<root>/projects/demo-shop/.env.staging.local',
          '```',
          '',
          'Read in that order, each merged over the last, missing ones skipped. So the bottom of the list wins, and the whole stack still loses to an exported variable.',
          '',
          'To see which ones a run actually read:',
          '',
          '```bash',
          'sdods config show -p demo-shop -e staging',
          '```',
          '',
          'The second line is the list of dotenv files, or `(none)`.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'anouk-devries',
        on: '2026-03-04',
        votes: 6,
        body: [
          'Before deleting, diff them — the usual reason for six files is that two people solved the same problem in different places and both work, so neither noticed.',
          '',
          'Convention that has held up for us: `.env.<env>` is committed to nothing but documented in `.env.example` and shared with the team; `.env.local` is personal and never mentioned to anyone. If a file does not fit one of those two descriptions it can go.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'zeynep-arslan',
        on: '2026-08-04',
        votes: 3,
        body: [
          'Late addition for anyone finding this: the same eight paths are checked whether or not the project folder differs from the repo root. In a single-project repo where the two are the same directory, only the four names are read once — you do not get duplicates.',
        ].join('\n'),
      },
    ],
  },

  {
    slug: 'cfg-no-projects-found-in-container',
    title: 'No projects found when running inside a container, works fine on the host',
    askedBy: 'paulo-mendes',
    askedOn: '2026-04-21',
    tags: ['config', 'cli', 'docker'],
    votes: 8,
    views: 1690,
    body: [
      'Same repo, mounted into the image at `/srv/app`. On the host every command is fine. Inside:',
      '',
      '```text',
      '✖ PROJECT_NOT_FOUND: No projects found.',
      '  hint: Run `sdods project create <slug>`.',
      '```',
      '',
      'And naming one explicitly gives a slightly different message:',
      '',
      '```text',
      '✖ PROJECT_NOT_FOUND: Unknown project "demo-shop".',
      '  hint: No projects found under /srv/app/projects. Run `sdods project create <slug>`.',
      '```',
      '',
      'The directory is definitely there — `ls /srv/app/projects` shows all three.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2026-04-21',
        votes: 12,
        body: [
          'The second message names the directory it looked in, and that is the thing to trust: `/srv/app/projects`. If the folders are there and it found none, the projects were skipped rather than missed — each one needs a `sdods.project.yaml` directly inside it.',
          '',
          'Most likely your mount is not bringing the files in, only the directory names, or the working directory is not where you think. The repo root is found by walking up from the current directory looking for `sdods.config.ts`, `sdods.config.json` or `sdods.workspace.yaml`, or for a `projects/` directory next to a `package.json`. A container whose workdir is `/` will walk up from there and find nothing.',
          '',
          '```bash',
          'ls /srv/app/projects/demo-shop/sdods.project.yaml',
          '```',
          '',
          'If the layout is unusual, name the directory outright:',
          '',
          '```bash',
          'SDODS_PROJECTS_DIR=/srv/app/projects sdods project list',
          '```',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-04-22',
        votes: 7,
        body: [
          'Set the working directory to the repo root in the container and this stops being a special case — everything below it then resolves the same way it does on your machine.',
          '',
          'Also check the mount is the repo root and not `projects/` itself. Mounting the inner directory gets you the project folders with no `sdods.workspace.yaml` above them, which changes where the root walk stops.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-doctor-vars-zero-resolved',
    title:
      'sdods doctor says "demo-shop/staging vars — 0 var(s) resolved" and passes. Is that right?',
    askedBy: 'zeynep-arslan',
    askedOn: '2026-06-30',
    tags: ['config', 'cli'],
    votes: 7,
    views: 1420,
    body: [
      'Green tick, zero variables. The staging environment definitely has a `${...}` in it, so I expected at least one.',
      '',
      '![sdods doctor output with green ticks for node, bun, runner, browsers, projects, per-project vars, database and the CLI checks](/questions/doctor.png "Every check passing, with 0 var(s) resolved per environment")',
      '',
      'Is the check finding nothing, or finding nothing to complain about?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2026-06-30',
        votes: 11,
        body: [
          'Finding nothing to complain about — and the count is the number it had to check, not the number in the file.',
          '',
          'That row verifies that every `${VAR}` that has no default resolves from the `.env` files or the shell. A reference with a default cannot fail, so it is not collected. The demo staging file uses',
          '',
          '```yaml',
          'vars:',
          '  standardPassword: "${DEMO_SHOP_PASSWORD:-secret_sauce}"',
          '```',
          '',
          'which is defaulted, so the count is zero and the check is trivially satisfied.',
          '',
          'Add a bearer token as a bare `${API_TOKEN}` and the number goes to one — or the check fails and names the variable, which is the case the row exists for.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'tanvi-bhatt',
        on: '2026-07-02',
        votes: 4,
        body: [
          'Consequence: a defaulted reference is invisible to doctor, so a missing value silently falls back instead of being reported. Fine for a public demo target, not fine for a credential — which is a decent argument for not putting defaults on anything real.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'cfg-explain-losing-layers-not-shown',
    title: 'Can --explain show the values a layer lost with, not just the winner?',
    askedBy: 'koen-vermeulen',
    askedOn: '2026-08-12',
    tags: ['config', 'cli'],
    votes: 2,
    views: 108,
    body: [
      'The provenance table gives one row per leaf with the winning layer. Passing `--headed` shows `runtime.headed cli`; exporting `SDODS_HEADED=1` instead shows `processEnv`; with both it shows `cli`.',
      '',
      'What I want in a support conversation is the other three-quarters of that: what did the env file say before the variable overwrote it, and what did the project file say before that. `--json` gives me the resolved tree, which is the same information in a different shape.',
      '',
      'Is there a verbose mode, or a debug variable, that dumps the per-layer values rather than the collapsed result? Happy to post-process JSON, I just cannot find a source that has the history in it.',
    ].join('\n'),
    answers: [],
  },
];
