import type { Thread } from '../types';

const L = (...lines: string[]) => lines.join('\n');

export const harThreads: Thread[] = [
  {
    slug: 'har-tagged-scenario-recorded-nothing',
    title: 'Scenario tagged @har:products runs green but har/staging is still empty',
    askedBy: 'lena-hartwig',
    askedOn: '2021-10-21',
    tags: ['har', 'ui', 'cli'],
    votes: 19,
    views: 7420,
    body: L(
      'I added the tag and ran the suite. It passes, but nothing lands in',
      '`projects/demo-shop/har/staging/`.',
      '',
      '```gherkin',
      '@ui @smoke @har:products',
      'Scenario: Products render from recorded traffic',
      '  Given I am on the inventory page',
      '  Then I should see the text "Sauce Labs Backpack"',
      '```',
      '',
      '```bash',
      'bun run sdods run -p demo-shop -e staging -l ui -b chromium -t @smoke',
      '```',
      '',
      'The only odd thing in the output was a yellow line I scrolled past:',
      '',
      '```text',
      '2021-10-21 09:12:44 [WARN] [har] @har:products has no recording at /work/projects/demo-shop/har/staging/products.har. Run: sdods har record -p demo-shop -e staging -t @har:products',
      '```',
      '',
      'Do I have to create the file by hand before the tag does anything?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'j-okonkwo',
        on: '2021-10-21',
        votes: 24,
        body: L(
          'The warning is the whole answer, and it even prints the command. A plain `sdods run` never',
          'records. The mode resolves like this: an explicit mode wins; otherwise it is replay when the',
          'file already exists, and off when it does not. Your file did not exist, so the hook fell to',
          'off and skipped routing entirely.',
          '',
          'Record it once:',
          '',
          '```bash',
          'bun run sdods har record -p demo-shop -e staging -t @har:products',
          '```',
          '',
          'That is the same thing as `sdods run ... --har-update`: requests go to the real network and the',
          'file is written on the way through. From then on every ordinary run of that scenario replays',
          'from `har/staging/products.har`, no flag needed.',
          '',
          'You also get a sidecar next to it, `products.har.json`, holding the project, the env, the URL',
          'glob, the timestamp and the scenario titles that contributed.',
        ),
      },
      {
        id: 'a2',
        by: 'reeta-nandal',
        on: '2021-10-25',
        votes: 11,
        body: L(
          'Adding one detail: if you leave `-t` off, `har record` runs the whole project in update mode',
          'and says so:',
          '',
          '```text',
          'no --tags given: running the project in HAR update mode (only @har-tagged scenarios record)',
          '```',
          '',
          'Untagged scenarios just run normally, so it is safe, only slower. Prefer the tag expression',
          'when you know which recording you are refreshing.',
          '',
          '> [!NOTE]',
          '> Recording is authoring, not testing. Do it deliberately, look at the diff, commit it.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-one-recording-for-every-environment',
    title: 'Can one HAR recording cover staging and prod, or is it per environment?',
    askedBy: 'sam-orbison',
    askedOn: '2022-05-11',
    tags: ['har', 'config'],
    votes: 14,
    views: 5210,
    body: L(
      'We have three environments that serve identical payloads. Re-recording the same traffic three',
      'times feels silly. `sdods har list` prints an `env` column so I assume the answer is no, but',
      'before I go symlinking directories: is the environment part of the lookup, or just part of the',
      'display?',
      '',
      '```bash',
      'bun run sdods har list -p demo-shop',
      '```',
    ),
    answers: [
      {
        id: 'a1',
        by: 'hsu-wei-lin',
        on: '2022-05-12',
        votes: 18,
        body: L(
          'It is part of the path, so it is part of the lookup. Files live at:',
          '',
          '```text',
          'projects/<slug>/har/<env>/<name>.har',
          'projects/<slug>/har/<env>/<name>.har.json',
          '```',
          '',
          'The directory comes from the resolved environment name, so a scenario running with',
          '`-e staging` can only ever see `har/staging/`. There is no fallback to another env and no way',
          'to point one env at another file.',
          '',
          'The tag names the file, the environment names the directory. So `@har:products` is one tag',
          'that maps to a different recording per env, which is usually what you want anyway: the hosts',
          'in the recorded URLs differ per environment, and a staging HAR replayed against prod URLs',
          'would miss on every entry.',
          '',
          'Do not symlink. The sidecar records which project and env it was captured against, and the',
          'first time the payloads diverge you will spend an afternoon working out why one env is',
          'asserting on the other one’s data.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-vs-mock-step-when-to-use-which',
    title: 'When should I reach for the mock step instead of @har, or the other way round?',
    askedBy: 'petrov-k',
    askedOn: '2022-10-03',
    tags: ['har', 'mock', 'ui'],
    votes: 27,
    views: 9640,
    body: L(
      'Both stub the network. I can write this:',
      '',
      '```gherkin',
      'When I mock "**/api/banner" with JSON:',
      '  """json',
      '  { "text": "Welcome {{username}}" }',
      '  """',
      '```',
      '',
      'or I can tag the scenario `@har:banner` and record it. They look interchangeable from where I',
      'am standing. Is there a rule for which one to pick, or is it taste?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'j-okonkwo',
        on: '2022-10-03',
        votes: 22,
        body: L(
          'Not taste. They answer different questions.',
          '',
          '- The mock step is route fulfilment for one URL pattern with a payload you wrote. Use it when the payload is the point of the test: an empty list, a 500, a banner with a specific string in it. The response is authored, so it says exactly what you meant.',
          '- `@har:<name>` is a snapshot of whatever the application actually sent, every request in the scenario, captured once and replayed verbatim. Use it when the payload is not the point and you just want the scenario to stop depending on a live service.',
          '',
          'Rough test: if you would have to hand-write more than one or two responses to make the page',
          'render, record a HAR. If you are asserting on a value you chose, mock it inline, because a',
          'recording will drift away from your assertion the next time someone re-records it.',
        ),
      },
      {
        id: 'a2',
        by: 'gcastellano',
        on: '2022-10-06',
        votes: 9,
        body: L(
          'We ended up using both in the same scenario and it works fine. Record the background traffic',
          'so the page loads offline, then mock the one endpoint whose shape the test is about. No',
          'trouble so far — the mock wins for its pattern and the recording answers everything else.',
          '',
          'One thing to watch: tag the scenario `@mock` as well if it carries an inline mock, otherwise',
          'nobody grepping for stubbed scenarios will find it.',
        ),
      },
      {
        id: 'a3',
        by: 'reeta-nandal',
        on: '2022-11-02',
        votes: 14,
        body: L(
          'One more axis nobody has mentioned: layers.',
          '',
          'The mock step is a browser step. It fulfils a page route, so it does nothing for an `@api`',
          'scenario. The `@har:<name>` tag drives both layers from the same tag — the browser side',
          'through Playwright route interception, the API side through the API client’s own recorder',
          'and replayer.',
          '',
          'So for an `@api` or `@hybrid` scenario that needs stubbed traffic, HAR is not one of two',
          'options, it is the option.',
          '',
          '[Network mocking and HAR](https://docs.sdods.com/docs/guides/network-mocking-and-har/)',
        ),
      },
    ],
  },

  {
    slug: 'har-should-we-commit-the-files',
    title: 'Should HAR files go into git? Ours are nearly a megabyte each',
    askedBy: 'ify-adeyemi',
    askedOn: '2023-03-20',
    tags: ['har', 'ci', 'config'],
    votes: 31,
    views: 11380,
    body: L(
      'Three recordings and the repository is a couple of megabytes heavier:',
      '',
      '```text',
      '926K  projects/demo-shop/har/staging/cart.har',
      '926K  projects/demo-shop/har/staging/login.har',
      '926K  projects/demo-shop/har/staging/products.har',
      '```',
      '',
      'Two worries. Size, obviously, since every re-record rewrites the whole blob and the history',
      'grows. And the login one — that recording was made while signed in, so I would rather like to',
      'know what is in it before I push. Gitignore them and rebuild in CI, or commit?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2023-03-20',
        votes: 26,
        body: L(
          'Commit them. The entire point of a recording is that CI does not need the application to be',
          'reachable; a HAR that CI has to rebuild is a HAR that buys you nothing. Treat them the way',
          'you treat visual baselines: checked in, reviewed in the diff, refreshed on purpose.',
          '',
          'On the credentials, your instinct is right and it is handled, but you should know how. The',
          'browser HAR is written by Playwright itself, verbatim, including the `Cookie`, `Set-Cookie`',
          'and `Authorization` headers of the application under test. So `sdods har record` scrubs the',
          'directory after the run and tells you what it touched:',
          '',
          '```text',
          'scrubbed 214 credential value(s) from 3 HAR file(s)',
          '```',
          '',
          'Values are replaced with `***` rather than the headers being deleted, so replay still matches',
          'on their presence. The API layer never has the problem: it redacts those headers as it builds',
          'the entry.',
          '',
          '> [!WARNING]',
          '> Read the diff of the first recording you commit. That is the one where you find out that',
          '> your application puts something interesting in a header nobody thought to name.',
        ),
      },
      {
        id: 'a2',
        by: 'j-okonkwo',
        on: '2023-03-22',
        votes: 12,
        body: L(
          'On the size: most of that 926 KB is embedded response bodies, and for a UI recording that',
          'means the bundle, the CSS and every image the page pulled. There is not much to trim after',
          'the fact — the place to cut is at record time, by limiting what gets captured at all:',
          '',
          '```bash',
          'bun run sdods har record -p demo-shop -e staging --interactive --name products --url /inventory.html --har-glob "**/api/**"',
          '```',
          '',
          'A HAR captured with a narrow glob is a few KB instead of a megabyte. The catch is that',
          'anything you excluded now goes to the real network on replay, so a strict offline run will',
          'abort on it. Narrow globs are for API traffic, not for pages you want to render offline.',
        ),
      },
      {
        id: 'a3',
        by: 'hsu-wei-lin',
        on: '2023-04-11',
        votes: 7,
        body: L(
          'Worth adding for anyone finding this later: API-layer recordings are nothing like this size.',
          'Ours run 2 KB to 100 KB because there is no bundle, no fonts and no images in them, only the',
          'JSON. If your project is mostly `@api` scenarios the whole storage question evaporates.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-run-passes-live-run-fails',
    title: 'Green on my machine, red on the runner — it was replaying a HAR the whole time',
    askedBy: 'yusuf-demir',
    askedOn: '2023-09-07',
    tags: ['har', 'ci', 'api'],
    votes: 22,
    views: 8140,
    body: L(
      'Spent most of a day on this so I am writing it down.',
      '',
      'A colleague recorded `@har:posts` a fortnight ago. Since then my local runs have been passing',
      'against a payload that no longer exists on staging, because the recording was sitting in the',
      'project and I never passed a HAR flag in my life. CI has a clean checkout, so it saw the same',
      'file and passed too — until the endpoint changed shape and the assertion started failing on',
      'the one job that runs against the live API.',
      '',
      '```bash',
      'bun run sdods run -p demo-shop -e staging -l api -t @smoke',
      '```',
      '',
      'How do I run the plain command and get the real network? I tried `SDODS_HAR_MODE=off` and it',
      'still replayed.',
    ),
    answers: [
      {
        id: 'a1',
        by: 'j-okonkwo',
        on: '2023-09-07',
        votes: 25,
        body: L(
          'Because off does not mean off once a file exists. The mode resolution is: take the requested',
          'mode, and if it is anything other than off use it; if it is off, fall through to a file check',
          'and replay when the recording is there. `SDODS_HAR_MODE=off` lands you in exactly that',
          'fall-through, which is why it changed nothing.',
          '',
          'Two ways to get the live network for a `@har`-tagged scenario:',
          '',
          '1. `sdods run ... --har-update`, which hits the real service and rewrites the file as it goes.',
          '2. Move the recording out of `har/<env>/` for the duration.',
          '',
          'If what you actually want is a job that proves the live API still matches, drop the `@har`',
          'tag from that scenario and use a recorded copy of it for the offline job instead. A scenario',
          'that is tagged for replay is not a contract test, and it will never fail when the service',
          'changes.',
        ),
      },
      {
        id: 'a2',
        by: 'reeta-nandal',
        on: '2023-09-19',
        votes: 8,
        body: L(
          'Fair complaint about the surface, and I will own it: the mode table documents `off` as "no',
          'HAR routing", and the resolution then treats off as "decide from the filesystem". Those two',
          'sentences do not say the same thing, and you are the second person to lose a day to the gap.',
          '',
          'Until that is reconciled, the reliable statement is the one to put in your team notes: once',
          '`har/<env>/<name>.har` exists, that scenario replays unless you pass `--har-update`.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-api-layer-writes-a-different-file',
    title: 'Why did my API scenario write posts.api.har and not posts.har?',
    askedBy: 'bea-lindqvist',
    askedOn: '2024-02-28',
    tags: ['har', 'api', 'cli'],
    votes: 29,
    views: 9870,
    body: L(
      'Same tag, same command shape as the UI one, different filename. After recording:',
      '',
      '```text',
      'projects/demo-shop/har/staging/products.har        926K   <- the @ui scenario',
      'projects/demo-shop/har/staging/products.har.json     205',
      'projects/demo-shop/har/staging/posts.api.har       97K    <- the @api scenario',
      'projects/demo-shop/har/staging/posts.har.json        149',
      '```',
      '',
      'There is no `posts.har`. I assumed the extension was a typo somewhere until I went looking for',
      'the file by hand and could not find it. Is `.api.har` a different format, and why does the',
      'sidecar drop the `.api` but the recording keeps it?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'j-okonkwo',
        on: '2024-02-28',
        votes: 33,
        body: L(
          'Not a typo, and it trips up nearly everyone once.',
          '',
          'Playwright’s HAR routing only exists on a page or a browser context. An `@api` scenario never',
          'opens either, so there is nothing to route from and the API client carries its own recorder',
          'and replayer instead. That second implementation writes `<name>.api.har`, deliberately a',
          'different filename, so that a `@hybrid` scenario running both layers does not have Playwright',
          'overwrite the file the API client just wrote.',
          '',
          'So for one tag you can end up with three files:',
          '',
          '```text',
          'projects/<slug>/har/<env>/<name>.har        browser layer',
          'projects/<slug>/har/<env>/<name>.api.har    API layer',
          'projects/<slug>/har/<env>/<name>.har.json   sidecar, shared by both',
          '```',
          '',
          'The sidecar is shared on purpose — it describes the recording, not the transport — which is',
          'why it keeps the plain `.har.json` name.',
          '',
          'Both are ordinary HAR and both open in any HAR viewer. The API one carries an extra `_sdods`',
          'block per entry holding the lookup key, because the replayer matches on that key rather than',
          'walking the entries.',
        ),
      },
      {
        id: 'a2',
        by: 'reeta-nandal',
        on: '2024-03-04',
        votes: 11,
        body: L(
          'The listing shows you which halves exist without you having to look in the directory:',
          '',
          '```bash',
          'bun run sdods har list -p demo-shop -e staging',
          '```',
          '',
          'The `api` column is yes when `<name>.api.har` is present. A row with `api` empty is browser',
          'only; a row for a name that has no browser recording at all is API only.',
          '',
          'The lookup key on the API side is method, normalised URL and a hash of the request body, so',
          'the same endpoint called with two different bodies is two entries.',
          '',
          '[sdods record, har, auth](https://docs.sdods.com/docs/reference/cli-commands/record-har-auth/)',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-re-record-after-api-changed',
    title: 'The API added a field — how do I re-record so the old entries stop coming back?',
    askedBy: 'nikhil-sane',
    askedOn: '2024-06-12',
    tags: ['har', 'api', 'regression'],
    votes: 18,
    views: 6320,
    body: L(
      'Backend renamed a field. I re-recorded:',
      '',
      '```bash',
      'bun run sdods har record -p demo-shop -e staging -t @har:posts',
      '```',
      '',
      'The scenario passes now, but the file grew instead of being replaced, and the old response with',
      'the old field name is still sitting in there. I would rather not ship a recording that contains',
      'a payload the service can no longer produce. Is there a prune step I am missing?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'j-okonkwo',
        on: '2024-06-12',
        votes: 21,
        body: L(
          'No prune step, and the two layers behave differently here, which is the part that confuses',
          'people.',
          '',
          'The API recorder is append-or-refresh. For each request it computes the lookup key, and if an',
          'entry with that key already exists it replaces it, otherwise it appends. Nothing is ever',
          'removed, so an entry whose key no longer occurs stays in the file forever.',
          '',
          'The browser recorder does not have that problem, because Playwright rewrites the file from',
          'the session rather than merging into it.',
          '',
          'So for an API recording, delete first:',
          '',
          '```bash',
          'rm projects/demo-shop/har/staging/posts.api.har',
          'bun run sdods har record -p demo-shop -e staging -t @har:posts',
          '```',
          '',
          'Leave the sidecar alone, it gets merged and updated in place.',
        ),
      },
      {
        id: 'a2',
        by: 'hsu-wei-lin',
        on: '2024-06-13',
        votes: 9,
        body: L(
          'To be precise about why it grew rather than refreshed: the key includes a hash of the request',
          'body. If the backend change also changed what you send, the new request hashes differently,',
          'misses the existing entry and appends a second one. Same URL, same method, two entries, only',
          'one of which anything will ever ask for again.',
          '',
          'That is also why an occasional delete-and-record is worth doing even when nothing broke.',
        ),
      },
      {
        id: 'a3',
        by: 'gcastellano',
        on: '2024-07-30',
        votes: 5,
        body: L(
          'Process suggestion rather than a mechanism: re-record in the same pull request that changes',
          'the API, not afterwards. Then the recording diff and the code diff are reviewed together and',
          'somebody notices when the payload changed in a way nobody intended.',
          '',
          'The `recorded` column of `sdods har list` gives you the age of each one, which is a decent',
          'thing to glance at before a release.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-recording-with-workers-loses-entries',
    title: 'Recorded with four workers and half the requests are missing from the file',
    askedBy: 'bruno-teixeira',
    askedOn: '2024-08-14',
    tags: ['har', 'cli', 'ci'],
    votes: 12,
    views: 4180,
    body: L(
      'Four scenarios share `@har:cart`. I recorded them together to save time:',
      '',
      '```bash',
      'SDODS_HAR_MODE=update bun run sdods run -p demo-shop -e staging -l ui -b chromium -t @har:cart -w 4',
      '```',
      '',
      'The run was green and the file exists, but on replay two of the four scenarios abort on',
      'requests that definitely happened during recording. Re-running the recording gives me a',
      'different two. Nothing in the output complains.',
    ),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2024-08-14',
        votes: 20,
        body: L(
          'Four workers sharing one recording name means four contexts writing the same file, each one',
          'flushing what it saw when it closed. Last close wins and the rest is gone — which matches',
          'your "different two each time".',
          '',
          'The runner already guards against this, but only when the mode comes from the flags. Passing',
          '`--har-update` clamps the run to a single worker and warns:',
          '',
          '```text',
          'Recording HAR fixtures runs with a single worker so shared files keep every request.',
          '```',
          '',
          'You set `SDODS_HAR_MODE` in the environment instead. That variable is read further down, when',
          'each worker resolves its own config, so the command never knew it was a recording run and',
          'never clamped anything. Hence no warning.',
          '',
          'Use the flag, or the wrapper that sets it for you:',
          '',
          '```bash',
          'bun run sdods har record -p demo-shop -e staging -t @har:cart',
          '```',
          '',
          'Recording is a one-off authoring step, so the serial run costs you a minute and nothing else.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-get-replays-but-post-misses',
    title: 'GET replays fine, the POST in the same scenario misses on every run',
    askedBy: 'tanvi-bhatt',
    askedOn: '2025-04-16',
    tags: ['har', 'api'],
    votes: 26,
    views: 7960,
    body: L(
      'Recorded, committed, replays fine for a day, then the POST starts failing and never recovers.',
      'The GET against the same endpoint keeps working.',
      '',
      '```bash',
      'bun run sdods har replay -p demo-shop -e staging -t @har:posts --strict',
      '```',
      '',
      '```text',
      'Error: HAR strict mode: no recorded entry for POST https://jsonplaceholder.typicode.com/posts 0736c37d8e28 in /home/tanvi/work/projects/demo-shop/har/staging/posts.api.har',
      '```',
      '',
      'The entry is in the file. I opened it and the URL and method match. What is `0736c37d8e28`?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'j-okonkwo',
        on: '2025-04-16',
        votes: 30,
        body: L(
          'It is a fingerprint of the request body. The API replayer does not scan entries looking for a',
          'match, it builds a key and does a map lookup, and the key is three parts:',
          '',
          '```text',
          '<METHOD> <normalised URL> <sha1 of the body, first 12 chars>',
          '```',
          '',
          'A GET has no body, so its key is just method and URL and it will keep matching forever. Your',
          'POST has a body, so the third part moves whenever the body does — and the error is telling',
          'you the body you are sending now hashes to `0736c37d8e28`, which is not what you recorded.',
          '',
          'The usual cause is a generated body. If the request is built from the factory, or carries a',
          'timestamp, a UUID or a random email, every run produces a new hash and the entry recorded',
          'yesterday can never be hit again.',
          '',
          'Make the body deterministic — a dataset row rather than a generated value — and then',
          're-record. Grep the file for `_sdods` and you will see the recorded keys; that is what you',
          'need yours to equal.',
        ),
      },
      {
        id: 'a2',
        by: 'hsu-wei-lin',
        on: '2025-04-17',
        votes: 12,
        body: L(
          'Before you blame the body, rule out the URL half, because it is normalised and not everything',
          'survives:',
          '',
          '- query parameters named `_`, `t`, `ts`, `timestamp`, `nonce`, `cb` or `cache` are dropped, so a cache-buster does not break matching',
          '- the remaining parameters are sorted, so parameter order does not matter',
          '- the host is lowercased and a trailing slash on the path is stripped',
          '',
          'Any other query parameter is part of the key. A page size or a filter that differs between',
          'the recording and the run gives you exactly this error.',
          '',
          'On the body side, object keys are sorted before hashing, so key order is not the culprit —',
          'only an actual value difference is.',
        ),
      },
      {
        id: 'a3',
        by: 'gcastellano',
        on: '2025-05-02',
        votes: 6,
        body: L(
          'Landing here from a UI scenario: none of this applies to you. The fingerprint, the key and',
          'this error message all come from the API replayer. On the browser side strict mode aborts the',
          'route instead, so you do not get a message naming the request — you get whatever your',
          'application does with a failed fetch, which is usually a spinner that never stops.',
          '',
          'Take the trace for those.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-strict-error-has-no-code-or-hint',
    title:
      'Why does the HAR strict failure have no code, hint or docs link like every other error?',
    askedBy: 'koen-vermeulen',
    askedOn: '2025-07-02',
    tags: ['har', 'api', 'cli'],
    votes: 17,
    views: 5040,
    body: L(
      'Small thing, but it broke a script. Every failure I have seen so far comes out shaped like',
      'this, and our CI wrapper parses the code out of it:',
      '',
      '```text',
      '✖ CONFIG_INVALID: Layer "api" is not enabled for project demo-shop (layers: ui).',
      '```',
      '',
      'A strict HAR miss comes out shaped like nothing:',
      '',
      '```text',
      'Error: HAR strict mode: no recorded entry for POST https://jsonplaceholder.typicode.com/posts 0736c37d8e28 in /srv/ci/projects/demo-shop/har/staging/posts.api.har',
      '```',
      '',
      'No code, no hint line, no docs line. Is that intentional, or is it just one that has not been',
      'converted yet?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2025-07-02',
        votes: 21,
        body: L(
          'Not intentional, and not converted yet. Two different things are going on.',
          '',
          'The structured shape comes from the error class the CLI throws: it carries a code, an optional',
          'hint and an optional docs path, and the renderer prints them as the three lines you are',
          'parsing. Anything that is not one of those errors falls back to `INTERNAL` plus the message.',
          '',
          'The strict miss is a plain error thrown by the API replayer, and it is thrown inside the test',
          'worker rather than in the CLI, so it surfaces through the test reporter and never reaches that',
          'renderer at all. Even if it did, it has nothing to render.',
          '',
          'There is a `HAR_MISS` code sitting in the error enum that this throw site does not use, which',
          'tells you roughly what happened: the code was reserved and the throw was never moved over.',
          '',
          'So: real gap, not a design decision. In the meantime do not parse it as a coded error — it',
          'will not gain a code silently.',
        ),
      },
      {
        id: 'a2',
        by: 'j-okonkwo',
        on: '2025-07-09',
        votes: 9,
        body: L(
          'For what it is worth, the message carries more than the coded ones do. It gives you the exact',
          'lookup key that missed and the exact file it looked in, which is everything you need to fix',
          'it. The coded errors give you a docs link.',
          '',
          'If your wrapper needs a stable marker, match on the literal prefix `HAR strict mode: no',
          'recorded entry for` — it comes from one place in the code, so it is at least not ambiguous.',
        ),
      },
    ],
  },

  {
    slug: 'har-run-the-whole-suite-with-no-network',
    title: 'Running the smoke suite on a plane — what do I need so nothing touches the network?',
    askedBy: 'rasha-halabi',
    askedOn: '2025-09-29',
    tags: ['har', 'ci', 'smoke'],
    votes: 33,
    views: 11920,
    body: L(
      'Long flight, and separately we are being asked to prove the suite runs on an air-gapped runner.',
      'Same problem twice, so I would like to get it right once.',
      '',
      'Everything is tagged `@har:<something>` and the recordings are committed. If I just pull the',
      'cable, do the scenarios replay, or do they quietly go looking for the network for anything that',
      'was not captured?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'j-okonkwo',
        on: '2025-09-29',
        votes: 38,
        body: L(
          'They go looking. Replay on its own is permissive: anything the recording does not answer',
          'falls through to the real network, which is fine on your desk and useless on a plane.',
          '',
          'This is the whole recipe:',
          '',
          '```bash',
          'bun run sdods run -p demo-shop -e staging --har-replay --strict -t @smoke',
          '```',
          '',
          '`--strict` alongside `--har-replay` turns the fall-through into an abort and sets offline mode',
          'for the run, so every request that is not in a recording fails loudly instead of leaving.',
          'That is the difference between "probably offline" and "provably offline": a missing entry is',
          'now a red scenario with a message naming the request.',
          '',
          'Do a strict run once while you still have network. Everything you missed at record time shows',
          'up in that run and nowhere else.',
        ),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2025-09-30',
        votes: 16,
        body: L(
          'That is the same command we put in the air-gapped job, so a couple of notes from running it',
          'in anger.',
          '',
          'Offline mode blocks everything, not just the application. Analytics, fonts from a CDN, an',
          'error reporter — if the page asks for it and the recording does not answer it, it aborts.',
          'That is the point, but the first strict run after enabling it will be red for reasons that',
          'have nothing to do with your test.',
          '',
          'A scenario without a `@har` tag in an offline run gets blocked wholesale and warned about:',
          '',
          '```text',
          'SDODS_OFFLINE=1 but the scenario has no @har tag: all network requests are blocked.',
          '```',
          '',
          'So restrict the offline job by tag, or make sure the suite it runs is fully recorded.',
          '',
          '[Sharding and CI](https://docs.sdods.com/docs/guides/sharding-and-ci/)',
        ),
      },
      {
        id: 'a3',
        by: 'hsu-wei-lin',
        on: '2025-10-02',
        votes: 9,
        body: L(
          'The thing that got us on an actual flight: authentication.',
          '',
          'Cached login state lives under `projects/<slug>/.auth/<env>/` and gets refreshed automatically',
          'when it expires. Refreshing means logging in, which means network. The demo targets public',
          'sandboxes whose session cookies live about ten minutes, so a cache captured in the departure',
          'lounge is stale before the seatbelt sign goes off, and offline it cannot be renewed.',
          '',
          'Capture before you take off:',
          '',
          '```bash',
          'bun run sdods auth capture -p demo-shop -e staging --all',
          '```',
          '',
          'Or record the login traffic into the HAR as well, so there is nothing to renew.',
        ),
      },
      {
        id: 'a4',
        by: 'gcastellano',
        on: '2025-11-20',
        votes: 4,
        body: L(
          'Late addition for anyone verifying this rather than trusting it: strict replay announces',
          'itself per scenario. You will not see it at the default log level though — it is emitted at',
          'step level, which sits above info, so you have to ask for it:',
          '',
          '```bash',
          'SDODS_LOG_LEVEL=step bun run sdods run -p demo-shop -e staging --har-replay --strict -t @smoke',
          '```',
          '',
          '```text',
          '2025-11-20 08:41:07 [STEP] [har] ▶ HAR replay (strict): /srv/ci/projects/demo-shop/har/staging/products.har',
          '```',
          '',
          'One line per routed scenario. That was how we found two scenarios in the offline job that had',
          'lost their tag in a rename and had been going to the network the whole time.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-interactive-record-needs-name',
    title: 'sdods har record --interactive exits before the browser even opens',
    askedBy: 'ingrid-solberg',
    askedOn: '2026-03-05',
    tags: ['har', 'recording', 'cli'],
    votes: 15,
    views: 4360,
    body: L(
      'Trying to capture a flow by hand rather than through a scenario.',
      '',
      '```bash',
      'bun run sdods har record -p demo-shop -e staging --interactive',
      '```',
      '',
      '```text',
      '✖ CONFIG_INVALID: --interactive needs --name <har-name>.',
      '```',
      '',
      'Fine, added `--name checkout`. Codegen opened, I clicked through the flow, closed the window,',
      'and got this:',
      '',
      '```text',
      '✖ RUN_FAILED: Codegen closed without writing a HAR.',
      '```',
      '',
      'Nothing in `har/staging/`. Two errors, two guesses, no recording.',
    ),
    answers: [
      {
        id: 'a1',
        by: 'j-okonkwo',
        on: '2026-03-05',
        votes: 19,
        body: L(
          'The first one is straightforward. Interactive recording is not driven by a scenario, so there',
          'is no `@har:<name>` tag to take the filename from and you have to supply it. That is also the',
          'tag you will put on scenarios afterwards, so pick the name you want to type in Gherkin.',
          '',
          'The second one is about how the file gets written. The recording is flushed when the browser',
          'context closes cleanly. If the process was interrupted — Ctrl-C in the terminal, or the',
          'window going away without the context shutting down — nothing is written and you get exactly',
          'that message. Close the codegen window itself and let the command finish on its own.',
          '',
          'Full form:',
          '',
          '```bash',
          'bun run sdods har record -p demo-shop -e staging --interactive --name checkout --url /cart.html --har-glob "**/*"',
          '```',
          '',
          'On success it tells you the tag to use:',
          '',
          '```text',
          '✔ HAR written: projects/demo-shop/har/staging/checkout.har — tag scenarios with @har:checkout',
          '```',
        ),
      },
      {
        id: 'a2',
        by: 'paulo-mendes',
        on: '2026-06-14',
        votes: 6,
        body: L(
          'Months late, but one thing that is easy to get wrong from reading the flag list: `--har-glob`',
          'only does anything in interactive mode.',
          '',
          'When you record through scenarios instead, the glob is not taken from the command line at',
          'all — it comes from the sidecar of the existing recording, defaulting to everything. So if',
          'you want a narrow capture, do the first recording interactively with the glob you want; the',
          'sidecar remembers it and later scenario-driven refreshes keep it.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-list-shows-blank-glob-and-recorded',
    title: 'sdods har list leaves glob and recorded blank even though the sidecar exists',
    askedBy: 'zeynep-arslan',
    askedOn: '2026-07-14',
    tags: ['har', 'cli', 'api'],
    votes: 11,
    views: 2870,
    body: L(
      'Cosmetic, but it made me think the recording was broken.',
      '',
      '![sdods har list output for rwa-bank on the local environment: a single row named profile, tag @har:profile, 2 KB, api yes, with the glob and recorded columns blank and scenarios 0](/questions/har-list.png "sdods har list -p rwa-bank -e local")',
      '',
      'The sidecar is right there next to the recording and it has the timestamp in it:',
      '',
      '```json',
      '{',
      '  "name": "profile",',
      '  "project": "rwa-bank",',
      '  "env": "local",',
      '  "recordedAt": "2026-07-13T18:22:04.911Z",',
      '  "source": "api",',
      '  "scenarios": []',
      '}',
      '```',
      '',
      'The replay works. Why does the listing not show any of it?',
    ),
    answers: [
      {
        id: 'a1',
        by: 'paulo-mendes',
        on: '2026-07-14',
        votes: 14,
        body: L(
          'Because your recording is API only, and the listing builds those rows on a second pass that',
          'does not read the sidecar.',
          '',
          'It walks the environment directory twice. The first pass takes every `.har` that is not an',
          '`.api.har`, and for each one it looks for the matching `.har.json` and fills in `glob`,',
          '`recorded` and `scenarios`. The second pass then picks up any name that only ever produced an',
          '`.api.har` — yours — and adds a row from the file on disk alone.',
          '',
          'So the sidecar is fine, it is simply not consulted for that row. `size` and `api` are real',
          'because they come from the filesystem; the three blanks are the ones that would have come',
          'from the sidecar.',
          '',
          'Two of your three fields would be empty anyway, incidentally: an API-mode recording writes no',
          '`urlGlob` at all, and its `scenarios` list stays empty. Only `recorded` is genuinely being',
          'lost here.',
        ),
      },
      {
        id: 'a2',
        by: 'j-okonkwo',
        on: '2026-07-16',
        votes: 5,
        body: L(
          'If you want the timestamp without opening the file, the sidecar is plain JSON with a stable',
          'name, so `cat projects/rwa-bank/har/local/profile.har.json` is the honest answer today.',
          '',
          'And do not read the `api` column as a health check — it is only "does `<name>.api.har` exist',
          'on disk". A stale recording and a fresh one both say yes.',
        ),
      },
    ],
    acceptedAnswerId: 'a1',
  },

  {
    slug: 'har-record-did-not-scrub-without-project-flag',
    title: 'har record printed no scrub line and the Cookie header is still sitting in the file',
    askedBy: 'devon-marsh',
    askedOn: '2026-08-20',
    tags: ['har', 'recording', 'cli'],
    votes: 3,
    views: 96,
    body: L(
      'We only have one project registered, so I have got into the habit of leaving `-p` off and',
      'letting it pick.',
      '',
      '```bash',
      'bun run sdods har record -e staging -t @har:cart',
      '```',
      '',
      'Recorded fine, scenario replays. But there was no line like this at the end, which I have seen',
      'on every other recording I have made:',
      '',
      '```text',
      'scrubbed 214 credential value(s) from 3 HAR file(s)',
      '```',
      '',
      'And sure enough the `Cookie` header in `har/staging/cart.har` is the real value, not `***`. Ran',
      'the identical command again with `-p demo-shop` in front of it and it scrubbed on the spot.',
      '',
      'So the scrub appears to be skipped when the project is resolved rather than passed. Is that',
      'deliberate, or should I be filing it? Asking because "credentials are only stripped when you',
      'happen to type a flag" is a slightly alarming shape for a safety net.',
    ),
    answers: [],
  },
];
