import type { Thread } from '../types';

export const installThreads: Thread[] = [
  {
    slug: 'ins-see-what-the-install-script-does-first',
    title: 'Is there a way to see what the install script will do before it does it?',
    askedBy: 'dperera',
    askedOn: '2020-11-14',
    tags: ['install', 'cli'],
    votes: 41,
    views: 15230,
    body: [
      'Our security team will not let anyone pipe a URL into a shell on a company laptop, and honestly I agree with them. I want to install SDODS but I need to be able to show someone what the script touches before I run it.',
      '',
      'Is reading the script the only option, or does it have something better?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2020-11-14',
        votes: 36,
        body: [
          'It has `--dry-run`, which prints every step and writes nothing. Download it, check the checksum, read it, then run it in dry-run mode:',
          '',
          '```bash',
          'curl -fsSLO https://sdods.com/install.sh',
          'curl -fsSLO https://sdods.com/install.sh.sha256',
          'sha256sum -c install.sh.sha256',
          'less install.sh',
          'sh install.sh --dry-run',
          '```',
          '',
          'On macOS the checksum line is `shasum -a 256 -c install.sh.sha256`.',
          '',
          'Every line of dry-run output that begins with "would" is a step that has not happened. Nothing is written, no shell profile is touched, no browser is downloaded.',
          '',
          '> [!NOTE]',
          '> Your shell profile is only ever edited when you pass `--modify-path`. Without it the installer prints the PATH line and leaves the editing to you, which is usually what a security review wants to hear.',
          '',
          'The full contract is at [Reference → Installer](https://docs.sdods.com/docs/reference/installer/) — options, what it writes, and what it refuses to do.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'mkuiper',
        on: '2020-11-17',
        votes: 12,
        body: [
          'Adding to that: `--version-check` is the other half. It detects what is on the machine and prints the paths it resolved, then exits without installing anything.',
          '',
          '```bash',
          'sh install.sh --version-check',
          '```',
          '',
          'I paste that output into the change ticket. It answers "what will this touch" in one block, which is the question the reviewer actually has.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-sdods-command-not-found-after-a-clean-install',
    title: 'sdods: command not found right after the installer said it succeeded',
    askedBy: 'kmoreau',
    askedOn: '2021-05-04',
    tags: ['install', 'cli'],
    votes: 38,
    views: 14110,
    body: [
      'Installer finished, green ticks all the way down, and then:',
      '',
      '```text',
      'sdods: command not found',
      '```',
      '',
      'The file is there. `ls ~/.local/bin/sdods` shows it and it is executable. So the install worked and something else is wrong, I just cannot see what.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2021-05-04',
        votes: 44,
        body: [
          '`~/.local/bin` is not on your PATH. The installer writes the command there and prints the line to add, but it does not edit your shell profile unless you ask it to.',
          '',
          'Either add it yourself:',
          '',
          '```bash',
          'export PATH="$HOME/.local/bin:$PATH"',
          '```',
          '',
          'or re-run the installer with `--modify-path`, which appends that line to your profile once:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --modify-path',
          '```',
          '',
          'Then open a new shell. Re-running is safe — it upgrades the install in place and the PATH line is only added once, no matter how many times you run it.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'annika-solheim',
        on: '2021-05-05',
        votes: 9,
        body: [
          'If you use zsh and you have both `.zshrc` and `.zprofile`, check which one the line landed in. Mine went into the profile and my terminal only sources `.zshrc` for interactive shells, so it worked in a login shell and nowhere else.',
          '',
          '`echo $PATH | tr : "\\n" | grep local` in the shell that fails is the quickest way to confirm which one you are in.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'avery-hollis',
        on: '2021-06-02',
        votes: 4,
        body: [
          'Same thing bit me over SSH. Non-interactive shells on our boxes read nothing at all, so a CI step that worked interactively failed in the job. Passing `--bin-dir` at a directory that is already on the system PATH avoids the whole question.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-installer-dies-behind-the-corporate-proxy',
    title: 'Installer cannot reach anything behind our corporate proxy',
    askedBy: 'elsa-nyman',
    askedOn: '2021-11-08',
    tags: ['install'],
    votes: 33,
    views: 11640,
    body: [
      'Everything on this laptop goes through an outbound proxy. Browsers work, our internal tools work, the installer does not — it gets partway and then hangs until it gives up on the download.',
      '',
      'Does it read proxy settings at all, or do I need to fetch things by hand?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2021-11-08',
        votes: 37,
        body: [
          'It honours `HTTPS_PROXY`, `HTTP_PROXY` and `NO_PROXY`, and so do curl, git and the package manager once those are exported. Export them in the same shell you run the installer from — not in your profile only, if you are testing in an already-open terminal.',
          '',
          '```bash',
          'export HTTPS_PROXY=http://proxy.corp.example:8080',
          'export HTTP_PROXY="$HTTPS_PROXY"',
          'export NO_PROXY=localhost,127.0.0.1,.corp.example',
          'curl -fsSL https://sdods.com/install.sh | sh',
          '```',
          '',
          'If a clone still fails after that, git needs telling separately — it does not always pick the variable up depending on how it was built:',
          '',
          '```bash',
          'git config --global http.proxy "$HTTPS_PROXY"',
          '```',
          '',
          'Do not forget `NO_PROXY`. Sending localhost through the proxy is how people end up with an installer that works and a test run that cannot reach its own server.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'rgarrido',
        on: '2021-11-10',
        votes: 11,
        body: [
          'One more thing that is easy to miss: if the proxy also inspects TLS you will get past the hang and into a certificate error instead. That is a different fix — you have to give the toolchain your internal CA bundle. Worth knowing before you conclude the proxy variables did not work.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-windows-script-refuses-to-run-in-git-bash',
    title:
      'Installer says "This is Windows" when I run it in Git Bash — what should I use instead?',
    askedBy: 'sam-orbison',
    askedOn: '2022-03-15',
    tags: ['install', 'windows', 'linux'],
    votes: 29,
    views: 10280,
    body: [
      'I copied the macOS/Linux one-liner into Git Bash because that is where I live on this machine. It refuses immediately:',
      '',
      '```text',
      'This is Windows (MINGW64_NT-10.0-19044).',
      '  Use PowerShell instead:',
      '    irm https://sdods.com/install.ps1 | iex',
      '  Or install inside WSL, where this script works normally.',
      '```',
      '',
      'I do have WSL. Which one is actually the right answer if I want to run browser tests?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2022-03-15',
        votes: 34,
        body: [
          'Both are supported, and the choice follows where your tests will run, not where you happen to be typing.',
          '',
          '- Testing a Windows browser, or you want the app on Windows: use PowerShell. The shell script deliberately refuses under MSYS/MinGW because half the paths it builds would be wrong in ways that only surface later.',
          '- Testing on Linux, or matching a Linux CI runner: install inside WSL and use the ordinary one-liner there. Inside WSL it is a normal Linux install and nothing is special about it.',
          '',
          'What you should not do is install on Windows and then drive it from a WSL shell, or the reverse. Two filesystems, two browser caches, and the failures are confusing out of all proportion to the cause.',
          '',
          'The PowerShell form is:',
          '',
          '```powershell',
          'irm https://sdods.com/install.ps1 | iex',
          '```',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'mkuiper',
        on: '2022-03-16',
        votes: 8,
        body: [
          'And if you go the WSL route, keep the workspace on the Linux side of the filesystem. Running a suite out of `/mnt/c/...` is slow enough that people assume the tool is slow.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-refusing-to-install-as-root-on-a-build-agent',
    title: 'Refusing to install as root — our build agent only has a root account',
    askedBy: 'sunita-kale',
    askedOn: '2022-10-04',
    tags: ['install', 'ci', 'linux'],
    votes: 27,
    views: 9420,
    body: [
      'Trying to bake SDODS into our build image. The agent runs everything as root, and the installer stops:',
      '',
      '```text',
      'Refusing to install as root.',
      '  Browsers and npm caches installed as root break for normal users.',
      '  Re-run as your own user, or set SDODS_ALLOW_ROOT=1 if this is a container.',
      '```',
      '',
      'I understand why it does this on a laptop. On a throwaway agent there is no other user to be.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2022-10-04',
        votes: 31,
        body: [
          'The error tells you the override, and your case is exactly the one it was written for. Set it on the shell that actually runs the script — a prefix on the left of the pipe is read by `curl`, which does not care, and the installer never sees it:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | SDODS_ALLOW_ROOT=1 CI=1 sh',
          '```',
          '',
          '`CI=1` is worth adding too — it implies `--yes`, so nothing waits for a keypress it will never get.',
          '',
          'The refusal exists because on a shared machine a root install leaves the browser cache and the package manager cache owned by root, and then every later command by a normal user fails somewhere deep with a permission error that does not mention root at all. On a single-user build agent that cannot happen, so the override is the right call rather than a workaround.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2022-10-05',
        votes: 14,
        body: [
          'If you have the choice, adding a plain user to the image is still better than the override — it gets you closer to how developers run the same suite, and the failures you see in CI stay recognisable.',
          '',
          'Where that is not worth the effort, pin the paths explicitly so the install is predictable rather than wherever root happens to point:',
          '',
          '```bash',
          'SDODS_HOME=/opt/sdods SDODS_BIN_DIR=/usr/local/bin SDODS_BROWSERS=chromium \\',
          '  SDODS_YES=1 SDODS_ALLOW_ROOT=1 sh -c "curl -fsSL https://sdods.com/install.sh | sh"',
          '```',
          '',
          'Every flag has an environment variable equivalent, which is what makes this readable in an image build. The list is in [Reference → Installer](https://docs.sdods.com/docs/reference/installer/).',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-bin-dir-is-not-writable-on-a-shared-host',
    title: '"/usr/local/bin is not writable" — can I put the command somewhere else?',
    askedBy: 'ade-oyinlola',
    askedOn: '2023-01-30',
    tags: ['install', 'linux'],
    votes: 21,
    views: 7180,
    body: [
      'Shared dev host, no sudo, never will have sudo. Our team wiki says to pass `--bin-dir /usr/local/bin` so everyone has the command in the same place, and the install gets all the way to writing it and then:',
      '',
      '```text',
      '/usr/local/bin is not writable.',
      '  Pass --bin-dir <writable path>.',
      '```',
      '',
      'The hint is clear enough, I just want to know whether that leaves anything half-installed behind.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2023-01-30',
        votes: 24,
        body: [
          'Nothing is half-installed — the command shim is the last step, so everything before it is already in place and re-running with a directory you own just finishes the job.',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --bin-dir ~/.local/bin --modify-path',
          '```',
          '',
          'The wiki line is written for machines where people have sudo. On this one you do not, so name a directory you own instead, and let `--modify-path` save you the second round of "command not found". Nothing else about the install differs — the shim is a two-line file that execs the real command.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-chromium-will-not-start-on-a-fresh-ubuntu-box',
    title: 'Chromium downloaded fine but will not launch on a fresh Ubuntu server',
    askedBy: 'yusuf-demir',
    askedOn: '2023-05-22',
    tags: ['install', 'linux', 'ui'],
    votes: 44,
    views: 16920,
    body: [
      'Minimal Ubuntu server image, no desktop installed. The install completed and the engine is on disk, but any UI scenario dies before the first step:',
      '',
      '```text',
      'browserType.launch: Host system is missing dependencies to run browsers.',
      'Missing libraries:',
      '    libnss3.so',
      '    libnspr4.so',
      '    libatk-1.0.so.0',
      '```',
      '',
      'API scenarios run perfectly on the same box, so the install itself is fine. Do I need a desktop environment?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'lars-vinter',
        on: '2023-05-22',
        votes: 39,
        body: [
          'No desktop needed — you need the shared libraries the engine links against, which a minimal server image does not ship. That install needs root, which is why it is not part of the ordinary installer run:',
          '',
          '```bash',
          'sudo sdods browsers install -b chromium --with-deps',
          '```',
          '',
          '`--with-deps` is the part that matters; without it you download the same engine again and it still cannot start. Nothing about your SDODS install is wrong, and you do not need to reinstall anything.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2023-05-23',
        votes: 17,
        body: [
          'For an image you build rather than a box you keep, put the dependency install in the image and leave the engine download to the run. Then the layer that needs root is separate from the layer that changes every release, which is also the one you want cached.',
          '',
          'And if that box only ever runs API scenarios, install nothing at all:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --browsers none',
          '```',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'reeta-nandal',
        on: '2023-05-24',
        votes: 12,
        body: [
          '`sdods doctor` reports this one directly rather than making you read a launch stack trace — the browser checks probe the executable, so you get a line per engine and you can tell "not downloaded" from "downloaded and cannot start".',
          '',
          '```bash',
          'sdods doctor',
          '```',
        ].join('\n'),
      },
      {
        id: 'a4',
        by: 'thom-vasseur',
        on: '2023-09-11',
        votes: 6,
        body: [
          'Landed here from a search after hitting the same thing on Debian slim. Worth saying out loud for the next person: the missing library list is not always the same on every distribution, so do not go hunting for `libnss3` by hand. `--with-deps` resolves the set for the distribution it is running on.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-how-much-disk-does-a-full-install-take',
    title: 'How much disk does a full SDODS install actually need?',
    askedBy: 'helle-borg',
    askedOn: '2023-11-02',
    tags: ['install'],
    votes: 26,
    views: 8760,
    body: [
      'I have to justify this on a laptop with a small SSD and a quota I did not choose. Before I ask for more space I would like a real number rather than "a few hundred megabytes".',
      '',
      'What does each part cost?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2023-11-02',
        votes: 30,
        body: [
          'Roughly, and in the order they land:',
          '',
          '- The SDODS packages themselves: about 9 MB. They ship compiled, so there is no source tree.',
          '- With their dependencies, the global install comes to around 400 MB.',
          '- Each browser engine adds about 500 MB on top, in a cache shared with any other Playwright tool on the machine.',
          '- Installing from source instead (`--source git`) clones the repository and installs every workspace, which needs about 1.5 GB.',
          '',
          'So the default — packages plus Chromium only — is roughly 900 MB. If you only run API scenarios, `--browsers none` keeps it under half of that.',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --browsers none',
          '```',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'lars-vinter',
        on: '2023-11-06',
        votes: 9,
        body: [
          'The number that surprises people later is the browser cache, because it does not shrink when you uninstall — it is shared, so removing SDODS deliberately leaves it alone.',
          '',
          'Check it before you ask for a quota increase; you may already be paying for it:',
          '',
          '```bash',
          'du -sh ~/.cache/ms-playwright              # Linux',
          'du -sh ~/Library/Caches/ms-playwright      # macOS',
          '```',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-does-it-download-chromium-again-if-i-have-playwright',
    title: 'Will SDODS download its own Chromium if I already have Playwright installed?',
    askedBy: 'bea-lindqvist',
    askedOn: '2024-06-05',
    tags: ['install', 'macos', 'linux'],
    votes: 23,
    views: 6940,
    body: [
      'I already have a Playwright project on this machine with all three engines downloaded. I would rather not carry a second copy of everything just to try SDODS.',
      '',
      'Does it use the engines that are already there, or is it a separate download?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2024-06-05',
        votes: 27,
        body: [
          'Same cache, no second copy. Engines live in the shared Playwright cache and SDODS reads and writes the same place:',
          '',
          '```text',
          '~/Library/Caches/ms-playwright     macOS',
          '~/.cache/ms-playwright             Linux',
          '```',
          '',
          'If the version SDODS wants is already there, nothing is downloaded. If it wants a newer build it fetches that one and both tools keep working, because the cache is keyed per build rather than overwritten.',
          '',
          'You can skip the download step entirely at install time and let it resolve what is already present:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --browsers none',
          'sdods doctor',
          '```',
          '',
          '`doctor` will tell you which engines it found. Add `--fix` if one is genuinely missing.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'lars-vinter',
        on: '2024-06-07',
        votes: 8,
        body: [
          'Consequence worth knowing in the other direction: uninstalling SDODS does not delete that cache, on purpose, because it is not only ours to delete. If you are chasing disk you have to remove it yourself.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-uninstalled-but-barely-got-any-disk-back',
    title: 'Uninstalled SDODS and got almost no disk space back',
    askedBy: 'anouk-devries',
    askedOn: '2024-10-08',
    tags: ['install'],
    votes: 12,
    views: 3980,
    body: [
      'Ran the uninstall and it reported success:',
      '',
      '```bash',
      'curl -fsSL https://sdods.com/install.sh | sh -s -- --uninstall --yes',
      '```',
      '',
      'It removed the install root and the command. But `df` barely moved. I was expecting most of a gigabyte.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2024-10-08',
        votes: 16,
        body: [
          'The browser engines are the gigabyte, and they are not in the install root. They live in the shared Playwright cache, which the uninstall leaves alone deliberately — deleting it would break any other tool on the machine that uses the same engines.',
          '',
          'The uninstall prints the two lines at the end for exactly this reason:',
          '',
          '```bash',
          'rm -rf ~/Library/Caches/ms-playwright     # macOS',
          'rm -rf ~/.cache/ms-playwright            # Linux',
          '```',
          '',
          'Workspaces you created are also untouched, which is the other place the space can be hiding if you scaffolded a few and forgot.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'helle-borg',
        on: '2024-10-09',
        votes: 5,
        body: [
          'Also check that you had not previously installed from source into a different home. If you ever passed `--dir`, the uninstall only removes the root it is pointed at, so an older tree can sit there indefinitely with nobody referencing it.',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'ins-node-is-too-old-can-the-installer-fix-it',
    title: 'Node v20 is too old — can the installer sort that out itself?',
    askedBy: 'nikhil-sane',
    askedOn: '2024-12-03',
    tags: ['install', 'ci'],
    votes: 25,
    views: 7320,
    body: [
      'Our runner image is pinned to an older Node and I do not own that image. Install stops here:',
      '',
      '```text',
      'Node v20 is too old. SDODS needs Node 22 or newer.',
      '```',
      '',
      'Is there a way to get a new enough Node without rebuilding the image or asking the platform team for a change window?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2024-12-03',
        votes: 28,
        body: [
          'Yes — `--install-node`. It sets up fnm (or uses nvm if you already have it) and installs a supported Node without touching the system one:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --install-node',
          '```',
          '',
          'When neither fnm nor nvm is present it installs fnm inside the SDODS home rather than into your profile, so nothing outside that directory changes. It warns about that and prints the two lines you need if you also want that Node on your own PATH.',
          '',
          'Node is the one prerequisite the installer will not put on your machine behind your back, which is why this is a flag and not the default. If it still cannot find a new enough Node afterwards it says so plainly:',
          '',
          '```text',
          'Node is still not on PATH after installation.',
          '```',
          '',
          'which almost always means you need a fresh shell.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'sam-orbison',
        on: '2024-12-04',
        votes: 10,
        body: [
          'Worth knowing that the PowerShell script has no equivalent — there is no install-node parameter on Windows. It checks Node, tells you it is too old and prints the commands to install a supported one, and then stops. So on a Windows runner this is a step you own rather than a flag you pass.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'bea-lindqvist',
        on: '2024-12-11',
        votes: 6,
        body: [
          'One caution from doing this in CI: if you use `--install-node` in a job, remember the fnm environment only exists inside the installer process. The step after it needs to set the PATH itself, or you get a green install followed by a "command not found" that looks unrelated.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-self-signed-certificate-chain-during-install',
    title: 'Install fails with a self-signed certificate in the chain on a work laptop',
    askedBy: 'sergio-alcaraz',
    askedOn: '2025-02-19',
    tags: ['install', 'macos'],
    votes: 19,
    views: 4820,
    body: [
      'Proxy variables are exported and the download starts, so the proxy part is working. Then it stops with:',
      '',
      '```text',
      'unable to get local issuer certificate',
      'self-signed certificate in certificate chain',
      '```',
      '',
      'Our gateway does TLS inspection, so I am guessing that is the cause. What do I point at what?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2025-02-19',
        votes: 23,
        body: [
          'That is TLS interception, yes. The gateway presents its own certificate and the toolchain does not know the internal CA that signed it. Give it the bundle:',
          '',
          '```bash',
          'export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/corp-root-ca.pem',
          'export HTTPS_PROXY=http://proxy.corp.example:8080',
          'curl -fsSL https://sdods.com/install.sh | sh',
          '```',
          '',
          'Export it before the installer runs, not after — it has to be in the environment of the processes the installer starts, which is where the failure actually is.',
          '',
          'Keep that variable exported for test runs too. The same chain has to verify when a scenario calls an internal API, and it is a confusing morning if the install works and the first API run does not.',
          '',
          'What you should not do is disable certificate checking to get past it. That turns a one-line fix into an unaudited machine.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'lars-vinter',
        on: '2025-02-20',
        votes: 8,
        body: [
          'Where to find the bundle, since that is usually the hard part: on a managed Mac it has normally been pushed into the system keychain, and your IT portal will have the `.pem` for download. Ask for "the root CA in PEM form" rather than "the certificate", or you will be sent the gateway leaf and it will not work.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-what-to-paste-when-reporting-an-install-problem',
    title: 'What should I paste when I report an install problem?',
    askedBy: 'tanvi-bhatt',
    askedOn: '2025-04-30',
    tags: ['install', 'cli'],
    votes: 17,
    views: 4310,
    body: [
      'I keep getting asked follow-up questions when I report installer trouble and I would rather include the right thing the first time. Is there one command whose output covers it?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2025-04-30',
        votes: 14,
        body: [
          'Two, and they answer different questions.',
          '',
          '```bash',
          'sh install.sh --version-check',
          '```',
          '',
          'prints the platform, the tool versions it detected and every path it resolved, then exits without installing. That is the state of the machine before anything happens.',
          '',
          '```bash',
          'sdods doctor',
          '```',
          '',
          'is the state after: the runner, the browser engines, the projects it can discover, the resolved variables and the database. It keeps going past a failure rather than stopping at the first one, so you get the whole picture in one pass.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2025-05-02',
        votes: 21,
        body: [
          'Both of those, plus the third thing people leave out: the command you actually ran, in full, and the error verbatim rather than paraphrased.',
          '',
          'If the failure is in the middle of a long step, re-run with `--verbose`. Output is hidden by default and only the tail is printed on failure, so the interesting line is often in the part you did not see.',
          '',
          '```bash',
          'sh install.sh --verbose',
          '```',
          '',
          '> [!TIP]',
          '> `--version-check` output is safe to paste in public — it is versions and paths, not tokens.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a2',
  },
  {
    slug: 'ins-two-installs-side-by-side-on-one-machine',
    title: 'Can I keep two SDODS installs on one machine without them fighting?',
    askedBy: 'koen-vermeulen',
    askedOn: '2025-07-14',
    tags: ['install', 'cli'],
    votes: 15,
    views: 3640,
    body: [
      'I need to reproduce a run from a while back against the build the team was standardised on then, while keeping my normal install for day-to-day work. Is that supported or am I going to have to uninstall and reinstall each time?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2025-07-14',
        votes: 18,
        body: [
          'Supported. `--dir` and `--bin-dir` keep two installs completely apart, and `--version` takes any git ref, so the second one can track a branch or a tag independently:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- \\',
          '  --version main --dir ~/.sdods-main --bin-dir ~/.local/bin/sdods-main',
          '```',
          '',
          'Two things to keep straight:',
          '',
          '- Re-running the same command upgrades that install in place. It is not additive, so a second install has to differ in `--dir` and `--bin-dir` or you are just replacing the first one.',
          '- Uninstall is scoped to the root you point it at, so pass the same `--dir` when you remove one. It refuses paths like `$HOME` or `/` outright, but it will happily remove the wrong SDODS root if you name the wrong one.',
          '',
          'The browser cache is still shared between them, which is what you want — the engines are not the thing that differs.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-install-has-been-sitting-on-dependencies-for-20-minutes',
    title: 'Install has been sitting on the dependency step for twenty minutes — stuck or slow?',
    askedBy: 'rasha-halabi',
    askedOn: '2025-09-25',
    tags: ['install'],
    votes: 3,
    views: 610,
    body: [
      'On the VPN, laptop otherwise idle. The installer printed the dependency install step and has produced nothing since. No error, no progress, cursor still blinking.',
      '',
      'I re-ran it with `--verbose` and now I can see it is doing something, but it is crawling and I cannot tell whether it will finish or whether I should kill it and start over.',
      '',
      '```bash',
      'sh install.sh --verbose',
      '```',
      '',
      'Is there a point at which I should assume it is wedged? I would rather not interrupt it halfway if re-running is worse than waiting.',
    ].join('\n'),
    answers: [],
  },
  {
    slug: 'ins-powershell-options-ignored-when-piping-to-iex',
    title: 'PowerShell installer ignores every option I pass it',
    askedBy: 'hsu-wei-lin',
    askedOn: '2026-01-06',
    tags: ['install', 'windows', 'cli'],
    votes: 16,
    views: 3140,
    body: [
      'I want the installer to also scaffold a workspace, so I tried adding the parameter to the one-liner:',
      '',
      '```powershell',
      'irm https://sdods.com/install.ps1 | iex -Workspace C:\\my-tests',
      '```',
      '',
      'PowerShell does not like that, and every variation I have tried either errors or installs with the defaults and silently ignores the parameter. What is the correct form?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'sam-orbison',
        on: '2026-01-06',
        votes: 22,
        body: [
          '`iex` cannot forward parameters — it evaluates a string, and the parameters you type belong to `iex` itself, not to the script inside the string. Build a script block instead and call it:',
          '',
          '```powershell',
          '& ([scriptblock]::Create((irm https://sdods.com/install.ps1))) -Workspace C:\\my-tests -Mcp claude',
          '```',
          '',
          'That is the documented form and it takes all the parameters: `-Version`, `-Dir`, `-BinDir`, `-Pm`, `-Browsers`, `-Workspace`, `-Source`, `-Mcp`, `-ModifyPath`, `-Yes`, `-Uninstall`, `-DryRun`, `-VersionCheck`, `-Help`.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-01-07',
        votes: 11,
        body: [
          'The other option, and the better one if this goes in a runbook where someone will read it later, is to download it first:',
          '',
          '```powershell',
          'irm https://sdods.com/install.ps1 -OutFile install.ps1',
          '.\\install.ps1 -Workspace C:\\my-tests -Browsers chromium',
          '```',
          '',
          'Every parameter also has an environment variable, which is usually cleaner in CI than either form:',
          '',
          '```powershell',
          '$env:SDODS_WORKSPACE = "C:\\my-tests"; $env:SDODS_BROWSERS = "chromium"; $env:SDODS_YES = "1"',
          'irm https://sdods.com/install.ps1 | iex',
          '```',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-browsers-flag-will-not-take-firefox',
    title: '--browsers firefox is rejected — how do I get anything other than Chromium?',
    askedBy: 'mina-farouk',
    askedOn: '2026-01-22',
    tags: ['install', 'cli'],
    votes: 10,
    views: 1810,
    body: [
      'Our suite runs on Firefox, so I asked for it at install time and got:',
      '',
      '```text',
      "--browsers must be all, chromium or none (got 'firefox').",
      '  Docs: https://docs.sdods.com/docs/getting-started/installation/',
      '```',
      '',
      'Exit code 2. So the flag exists but does not take an engine name. Is Firefox not supported?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-01-22',
        votes: 14,
        body: [
          'Firefox is supported; the installer flag just is not the place to name one engine. It takes three values because it is answering "how much do you want downloaded", not "which one".',
          '',
          'Either take all three at install time:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --browsers all',
          '```',
          '',
          'or install nothing and pick engines afterwards, which is what I would do if you only ever use one:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --browsers none',
          'sdods browsers install -b firefox',
          '```',
          '',
          'The CLI command is the one that takes engine names, and it accepts `-b` more than once plus `--with-deps` when you need the system libraries as well.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-what-does-the-installer-write-outside-its-own-directory',
    title: 'Does the installer write anything outside its own directory?',
    askedBy: 'avery-hollis',
    askedOn: '2026-02-03',
    tags: ['install', 'cli'],
    votes: 24,
    views: 4270,
    body: [
      'Managed laptop. The question I have to answer in writing is not "is it safe", it is "what does it touch" — specifically whether it edits my shell profile, whether it puts anything in a system directory, and whether removing it later is a matter of deleting one tree or hunting for leftovers.',
      '',
      'I have read the script and I think the answer is "no, almost nothing", but I would rather quote something than paraphrase myself to a reviewer.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2026-02-03',
        votes: 26,
        body: [
          'There is a table for exactly this, and it is short. On a default install:',
          '',
          "- your package manager's global directory — the SDODS packages themselves",
          '- the bin directory — the `sdods` command, a two-line shim that execs the real one',
          '- the shared browser engine cache — unless you pass `--browsers none`',
          '- the install root — only if Bun was not already on your PATH, in which case it goes in there rather than into your system',
          '',
          'Everything else is behind a flag you have to type: the shell profile only with `--modify-path`, a workspace only with `--workspace`, a source checkout only with `--source git`, an agent client config only with `--mcp`. Nothing is written to a system directory unless you point `--bin-dir` at one.',
          '',
          'The full version, including what each path is for, is in [Reference → Installer](https://docs.sdods.com/docs/reference/installer/). That is the page to attach to the request.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-02-04',
        votes: 15,
        body: [
          'If the reviewer would rather see it from your machine than from our docs, the script will tell them itself. `--dry-run` prints every step it would take and writes nothing:',
          '',
          '```bash',
          'curl -fsSLO https://sdods.com/install.sh',
          'sh install.sh --dry-run --browsers chromium',
          '```',
          '',
          '![Terminal output of sh install.sh --dry-run --browsers chromium, listing the fetch, the dependency install, the browser install and the command shim, none of which have happened](/questions/install-dry-run.png "Every line beginning would is a step that has not happened.")',
          '',
          'And `--version-check` prints the paths it resolved on this specific machine, then exits:',
          '',
          '```bash',
          'sh install.sh --version-check',
          '```',
          '',
          '![Terminal output of sh install.sh --version-check showing the resolved platform, tool versions and install paths](/questions/version-check.png "Versions and paths, then it exits without installing.")',
          '',
          'Between the two, a reviewer gets the claim and the evidence for it without anyone having to trust a summary.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-pm-yarn-is-not-an-accepted-value',
    title: '--pm yarn is rejected — we standardised on yarn everywhere',
    askedBy: 'thom-vasseur',
    askedOn: '2026-02-17',
    tags: ['install', 'cli'],
    votes: 8,
    views: 1290,
    body: [
      'Every repo here uses yarn, so I passed it through and got:',
      '',
      '```text',
      "--pm must be bun, pnpm or npm (got 'yarn').",
      '```',
      '',
      'Is that a deliberate omission or just something nobody has got to yet? I would rather not have a second package manager on the machine only for this.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-02-17',
        votes: 12,
        body: [
          'Deliberate, and narrower than it looks: `--pm` only chooses which package manager performs the install of the SDODS packages. It has nothing to do with the package manager your own projects use, and it does not go near your repos.',
          '',
          'Pick `npm` and nothing else changes on the machine — it ships with Node, which you already need:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --pm npm',
          '```',
          '',
          'The default is `bun`, which the installer will install into the SDODS home if you do not have it. If you would rather it did not, `--pm npm` is the flag that prevents that.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'reeta-nandal',
        on: '2026-02-18',
        votes: 6,
        body: [
          'To be explicit about the part that worries people: SDODS does not require a lockfile, a workspace field or a package manager in your test repository. A workspace scaffolded by `sdods init` is project YAML, environment YAML and feature files. Your yarn setup and this flag never meet.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-cli-is-not-available-on-the-npm-registry',
    title: '"@sdods/cli is not available on the npm registry" behind an internal mirror',
    askedBy: 'ify-adeyemi',
    askedOn: '2026-03-05',
    tags: ['install', 'cli', 'ci'],
    votes: 13,
    views: 2380,
    body: [
      'Our build network can only reach an internal registry mirror. The installer stops before it downloads anything:',
      '',
      '```text',
      '@sdods/cli is not available on the npm registry.',
      '  Check your registry and network, or install from source with: --source git',
      '  Docs: https://docs.sdods.com/docs/getting-started/installation/',
      '```',
      '',
      'Exit code 7. The package resolves fine from my laptop, so I assume the mirror has not pulled it through yet. Is there a way to confirm that rather than guess?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-03-05',
        votes: 17,
        body: [
          'Confirm it directly — the installer is asking the registry your environment points at, so ask it the same question yourself:',
          '',
          '```bash',
          'npm view @sdods/cli version --registry "$(npm config get registry)"',
          '```',
          '',
          'If that fails, the mirror is the problem and nothing about SDODS will fix it. Most proxying registries only fetch a package on first request and some need it allow-listed first.',
          '',
          'Note which message you got, because there are two and they mean different things:',
          '',
          '- "is not available on the npm registry" comes from `--source npm`, where you told it not to consider anything else.',
          '- "could not be found on the npm registry" is the `auto` path, and that one is usually temporary — retry before doing anything else.',
          '',
          '`auto` never falls back to a clone on its own. A registry outage should say so rather than hand you a 1.5 GB source tree you did not ask for.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2026-03-06',
        votes: 9,
        body: [
          'For the build itself, do not install from the network on every job. Install once when you bake the image — the install is the slow, flaky step in that pipeline and it does not change between commits.',
          '',
          '```bash',
          'SDODS_HOME=/opt/sdods SDODS_BIN_DIR=/usr/local/bin SDODS_BROWSERS=chromium SDODS_YES=1 \\',
          '  sh -c "curl -fsSL https://sdods.com/install.sh | sh"',
          '```',
          '',
          'Every flag has an environment variable equivalent, which is what keeps that layer readable and cacheable.',
          '',
          'More on shaping this for CI in [Guides → Sharding and CI](https://docs.sdods.com/docs/guides/sharding-and-ci/).',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'sergio-alcaraz',
        on: '2026-03-09',
        votes: 4,
        body: [
          'We hit this exact thing and it was the mirror. Ours only mirrors scopes that have been requested through the UI once, so `@sdods` did not exist until someone asked for it. Took a day, then the ordinary one-liner worked with no flags.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-checkout-is-missing-packages-cli',
    title: '"The checkout is missing packages/cli — the clone looks incomplete"',
    askedBy: 'petrov-k',
    askedOn: '2026-03-18',
    tags: ['install', 'cli', 'linux'],
    votes: 7,
    views: 1060,
    body: [
      'Installing with `--source git` because I want to work on SDODS itself. The clone appears to succeed and then:',
      '',
      '```text',
      'The checkout is missing packages/cli — the clone looks incomplete.',
      '```',
      '',
      'Exit code 7. `~/.sdods/app` exists and has a `.git` directory in it, so something arrived.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-03-18',
        votes: 11,
        body: [
          'That check runs after the clone and asserts the tree actually contains what it needs, because a clone can exit zero and still leave you with a partial tree — a proxy that truncates a large transfer is the usual cause, and a mid-transfer network drop is the other.',
          '',
          'Delete the directory and let it clone from scratch. Re-running on top of a broken checkout tries to fetch and check out again, which will not repair a tree that is missing files:',
          '',
          '```bash',
          'rm -rf ~/.sdods/app',
          'curl -fsSL https://sdods.com/install.sh | sh -s -- --source git --verbose',
          '```',
          '',
          '`--verbose` matters here: the clone output is hidden unless you ask for it, and if the transfer is being cut off the git error usually says so in a line you would otherwise never see.',
          '',
          'If you are behind a proxy, also set `git config --global http.proxy` before retrying. And if you only want to use SDODS rather than work on it, drop `--source git` entirely — the default installs compiled packages and never clones anything.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-brew-asks-me-to-trust-the-tap',
    title: 'brew install asks me to trust the SDODS tap first — is that expected?',
    askedBy: 'sergio-alcaraz',
    askedOn: '2026-03-24',
    tags: ['install', 'macos', 'cli'],
    votes: 12,
    views: 2040,
    body: [
      'Ran the documented command:',
      '',
      '```bash',
      'brew install siri1410/sdods/sdods',
      '```',
      '',
      'Homebrew stops and asks me to confirm I trust the tap, and prints a `brew trust` command to run. I have installed plenty of things with brew and not seen this before, so before I type it: is that a normal step or a sign I have the wrong command?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-03-24',
        votes: 16,
        body: [
          'Normal, and it is Homebrew being careful rather than anything about SDODS. Third-party taps are not in homebrew/core, so the first install from one asks you to trust it explicitly. You have not seen it before because most of what you install lives in core.',
          '',
          'You can read the formula before deciding — inspecting needs no trust, only installing does:',
          '',
          '```bash',
          'brew info siri1410/sdods/sdods',
          '```',
          '',
          "What you will see: the formula holds no software of its own. It installs the published CLI packages and depends on Homebrew's `node` rather than vendoring one, so SDODS runs on the same Node as the rest of your toolchain. `brew upgrade sdods` updates it from then on.",
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'mkuiper',
        on: '2026-03-26',
        votes: 6,
        body: [
          'Worth knowing what it gives you: the CLI, not the desktop app. If you were after the app, brew is not the channel — the download page has the installers.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-brew-no-matching-version-with-a-date-before',
    title:
      'brew install fails with "No matching version found for @sdods/agents ... with a date before"',
    askedBy: 'paulo-mendes',
    askedOn: '2026-04-21',
    tags: ['install', 'macos'],
    votes: 14,
    views: 2260,
    body: [
      'Tried to install the day a release went out and got this, which I cannot make sense of:',
      '',
      '```text',
      'No matching version found for @sdods/agents@0.2.2 with a date before 2026-04-21T00:00:00.000Z',
      '```',
      '',
      'The version exists — I can see it on npm and `npm i -g @sdods/cli` works fine on the same machine. So why does brew think it does not?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-04-21',
        votes: 19,
        body: [
          'The formula is correct and the package exists. It is too new.',
          '',
          'Homebrew builds node formulae with `std_npm_args`, which passes `--min-release-age`. npm then refuses any dependency published inside that window, and the message it prints is the one you pasted — it reads like "this version does not exist" but it means "this version is younger than the floor I was given".',
          '',
          'There is nothing to fix on your side. Wait for the packages to age past the window and the same command installs. If you need it today, npm has no such floor:',
          '',
          '```bash',
          'npm install -g @sdods/cli',
          '```',
          '',
          'This is also why the formula is never pushed the same day the packages are published — it would be correct and uninstallable, which is the worst combination.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'sergio-alcaraz',
        on: '2026-04-22',
        votes: 7,
        body: [
          'Confirming from the other side of it: I hit the same message on Tuesday, changed nothing at all, and it installed on Thursday. Do not go editing the formula locally, you will only give yourself a second problem.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'reeta-nandal',
        on: '2026-04-23',
        votes: 5,
        body: [
          'If you use the install script instead of brew you never see this either — it fetches the published packages directly and has no release-age policy of its own.',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh',
          '```',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-docker-no-matching-manifest-on-apple-silicon',
    title: 'docker run fails on an M-series Mac: no matching manifest for linux/arm64/v8',
    askedBy: 'ingrid-solberg',
    askedOn: '2026-05-04',
    tags: ['install', 'docker', 'macos'],
    votes: 21,
    views: 3540,
    body: [
      'Wanted the server and web UI without installing anything, so I went for the image:',
      '',
      '```bash',
      'docker run --rm -p 8080:8080 -v sdods-data:/data ghcr.io/siri1410/sdods-server',
      '```',
      '',
      '```text',
      'no matching manifest for linux/arm64/v8 in the manifest list entries',
      '```',
      '',
      'I thought Docker Desktop emulated whatever was missing on Apple silicon. It seems not, or I have misunderstood something.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'nikhil-sane',
        on: '2026-05-04',
        votes: 25,
        body: [
          'You have not misunderstood the machine, only Docker. Docker does not fall back to emulation for a missing architecture — it refuses the pull. Emulation only happens once you ask for a platform it can emulate, which is what the flag does:',
          '',
          '```bash',
          'docker run --rm --platform linux/amd64 -p 8080:8080 -v sdods-data:/data ghcr.io/siri1410/sdods-server',
          '```',
          '',
          'The published image is `linux/amd64` only today, so on Apple silicon it goes through Rosetta. It works and it is slower — mostly on startup rather than during a run.',
          '',
          'On an Intel machine, or once an arm64 image is published, no flag is needed.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-05-04',
        votes: 13,
        body: [
          'The reason it is amd64 only, since it comes up every time: building arm64 in CI was tried and abandoned. Under emulation on an amd64 runner the arm64 stage did not finish inside the job limit, because the dependency install, the native module builds and the web bundle all run emulated. Fixing it properly needs a native arm64 runner or splitting the build so the architecture-independent part is not emulated.',
          '',
          'The install page reads the architectures out of the actual manifest rather than a claim in a config file, which is why it says amd64 rather than quietly promising both.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'sergio-alcaraz',
        on: '2026-05-08',
        votes: 6,
        body: [
          'If the emulated startup bothers you, the CLI is native on Apple silicon and installs in under a minute:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/install.sh | sh',
          '```',
          '',
          'The image is the better choice when you want the server and web UI without installing anything on the host. For running suites locally the CLI is the faster path on that hardware.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-run-a-suite-inside-the-server-image',
    title: 'Can I run a suite with the Docker image, or is it only the server?',
    askedBy: 'bruno-teixeira',
    askedOn: '2026-05-19',
    tags: ['install', 'docker', 'ci'],
    votes: 15,
    views: 2470,
    body: [
      'The image is described as the server and the web UI. Our CI does not need a UI, it needs to run the API layer and fail the build. Is the image the wrong tool for that, or does it do both?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'nikhil-sane',
        on: '2026-05-19',
        votes: 19,
        body: [
          'It does both. The entrypoint defaults to `serve`, understands `bootstrap`, and passes anything else straight to the CLI. So any command you would run locally is an argument to the container:',
          '',
          '```bash',
          'docker run --rm ghcr.io/siri1410/sdods-server run -p demo-shop -e staging -l api',
          '```',
          '',
          'The exit code comes back through, which is the part that matters for a build gate.',
          '',
          'For a UI layer you need nothing extra — the browser engines are already inside the image. That is the one channel that needs nothing at all installed on the host.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2026-05-20',
        votes: 10,
        body: [
          'Mount your project in and point the run at it, or it will only ever see the demo project that ships inside the image:',
          '',
          '```bash',
          'docker run --rm -v "$PWD":/work -w /work ghcr.io/siri1410/sdods-server run -p my-app -e staging -l api',
          '```',
          '',
          'Projects are discovered from the working directory, so `-w` is doing real work in that line and not just tidiness.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'lars-vinter',
        on: '2026-05-26',
        votes: 5,
        body: [
          'On Apple silicon add `--platform linux/amd64` to both of those — the image is amd64 only and Docker refuses the pull rather than emulating on its own.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-where-does-the-container-keep-its-data',
    title: 'Where does the Docker image keep its data, and what happens without the volume?',
    askedBy: 'devon-marsh',
    askedOn: '2026-06-23',
    tags: ['install', 'docker'],
    votes: 8,
    views: 1120,
    body: [
      'The documented run command has `-v sdods-data:/data` in it. I dropped it to try the UI quickly, created a couple of things, and after a restart they were gone.',
      '',
      'I assume that is the volume doing its job and I removed it. Before I put it back properly — what exactly lives in there, and can I point it at a directory instead of a named volume?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'nikhil-sane',
        on: '2026-06-23',
        votes: 12,
        body: [
          'Yes, that is exactly what happened. `/data` is where the platform database and run artifacts live, and `--rm` with no volume means the container filesystem goes away with the container.',
          '',
          'A named volume is the simple form:',
          '',
          '```bash',
          'docker run --rm -p 8080:8080 -v sdods-data:/data ghcr.io/siri1410/sdods-server',
          '```',
          '',
          'A host directory works the same way and is easier to back up or inspect:',
          '',
          '```bash',
          'docker run --rm -p 8080:8080 -v "$HOME/sdods-data":/data ghcr.io/siri1410/sdods-server',
          '```',
          '',
          'Deployment shapes, including running it somewhere permanent, are in [Guides → Hosting](https://docs.sdods.com/docs/guides/hosting/).',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'paulo-mendes',
        on: '2026-06-25',
        votes: 4,
        body: [
          'One gotcha with the host-directory form: the container writes as its own user, so on Linux you can end up with a directory you cannot read afterwards. A named volume sidesteps that entirely, which is probably why the docs lead with it.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-build-the-server-image-for-a-private-registry',
    title: 'Can I build the server image myself and push it to our own registry?',
    askedBy: 'zeynep-arslan',
    askedOn: '2026-07-09',
    tags: ['install', 'docker', 'ci'],
    votes: 5,
    views: 640,
    body: [
      'Our cluster only pulls from an internal registry, so pulling from a public one is not an option regardless of how convenient it is. Is building the image ourselves supported, or is the published one the only route?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'nikhil-sane',
        on: '2026-07-09',
        votes: 7,
        body: [
          'Supported — the image is built from a Dockerfile in the checkout, on the official Playwright base, so the browser engines come in with the base rather than being downloaded during the build.',
          '',
          '```bash',
          'docker build -t sdods-server .',
          'docker run --rm sdods-server doctor',
          '```',
          '',
          'Tag it for your registry and push it like anything else. The entrypoint behaves identically no matter where the image is stored — `serve` by default, `bootstrap`, and any other argument goes to the CLI.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-07-10',
        votes: 4,
        body: [
          'If you build for a mix of hardware, be deliberate about it: building an arm64 image under emulation on an amd64 runner is very slow, for the same reason the published image is amd64 only. A native runner per architecture is the difference between minutes and not finishing.',
          '',
          '`docker run --rm sdods-server doctor` is the right smoke test for the built image, and it is worth running in the build pipeline rather than after the push.',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'ins-macos-says-the-app-is-damaged',
    title: 'macOS says "SDODS is damaged and can\'t be opened" after downloading the app',
    askedBy: 'gcastellano',
    askedOn: '2026-06-04',
    tags: ['install', 'macos'],
    votes: 18,
    views: 3020,
    body: [
      'Downloaded the desktop app, dragged it to Applications, double-clicked, and:',
      '',
      '```text',
      "SDODS is damaged and can't be opened. You should move it to the Trash.",
      '```',
      '',
      'Downloaded it twice in case something was truncated. Same message. Is the download actually broken or is this the usual macOS thing?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-06-04',
        votes: 24,
        body: [
          'The usual macOS thing. The download is fine — the app is not signed yet, and Gatekeeper phrases "I do not recognise who made this" as "damaged", which is a genuinely terrible message for the situation.',
          '',
          'The safest way past it is the one macOS offers itself: find SDODS in Applications, right-click, choose Open, and confirm in the dialog. macOS remembers the decision, so you only do it once and every later launch is a normal double-click.',
          '',
          'There is also the direct form:',
          '',
          '```bash',
          'xattr -dr com.apple.quarantine /Applications/SDODS.app',
          '```',
          '',
          'It works, and I mention it second on purpose: it is worse advice to hand a stranger, because it is a command you can be talked into running against something that really is malicious. Right-click and Open is the same decision with a dialog attached.',
          '',
          'The CLI is unaffected by any of this — nothing installed by the script is quarantined.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'mkuiper',
        on: '2026-06-05',
        votes: 9,
        body: [
          'To answer the implied question: signing is not free and not automatic. It needs an Apple Developer Program membership, a Developer ID Application certificate and a notarization step per build. Until that exists every download says this.',
          '',
          'If you want to verify the download rather than trust the dialog, every release ships a `SHA256SUMS.txt` and you can check the file you got against it.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'sergio-alcaraz',
        on: '2026-06-06',
        votes: 5,
        body: [
          'Do not skip the right-click. I tried Open from the Finder menu bar with the app already selected and got the same refusal; the context-menu Open is the one carrying the override.',
        ].join('\n'),
      },
      {
        id: 'a4',
        by: 'annika-solheim',
        on: '2026-06-18',
        votes: 3,
        body: [
          'For a managed fleet, none of the above scales — ask whoever runs your MDM to allow the app rather than telling twenty people to right-click. That is also the honest answer to give a security team, who will not love a `xattr` instruction in a runbook.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-scoop-and-winget-install-the-desktop-app-not-the-cli',
    title:
      'scoop install sdods gave me the app, not the sdods command — where is the CLI on Windows?',
    askedBy: 'fiona-mcallister',
    askedOn: '2026-05-28',
    tags: ['install', 'windows', 'cli'],
    votes: 14,
    views: 2210,
    body: [
      'Added the bucket and installed:',
      '',
      '```powershell',
      'scoop bucket add sdods https://github.com/siri1410/scoop-sdods',
      'scoop install sdods',
      '```',
      '',
      'I now have a desktop application. What I wanted was `sdods run` in a terminal. Did I pick the wrong package name?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'sam-orbison',
        on: '2026-05-28',
        votes: 18,
        body: [
          'Right name, wrong channel for what you want. Scoop and winget both install the desktop app — they are the managers Windows users already have, and a GUI installer is what they are built to place.',
          '',
          'The CLI on Windows comes from the PowerShell script or from npm:',
          '',
          '```powershell',
          'irm https://sdods.com/install.ps1 | iex',
          '```',
          '',
          '```powershell',
          'npm install -g @sdods/cli',
          '```',
          '',
          'Both give you `sdods` on PATH. Having the app as well is fine — they are separate things and do not conflict.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-05-29',
        votes: 8,
        body: [
          'Worth reading the channel table with that split in mind: it lists three different products. The scripts, npm and Homebrew install the CLI; Docker installs the server and web UI; Scoop, winget and the Debian packages install the desktop app.',
          '',
          'The whole table is in [Getting started → Installation](https://docs.sdods.com/docs/getting-started/installation/), with what each one needs.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'hsu-wei-lin',
        on: '2026-06-02',
        votes: 4,
        body: [
          'If you install both, keep in mind that upgrading one does not upgrade the other. `scoop update sdods` moves the app; the CLI moves when you re-run the script or update the npm package. Ours drifted apart for a month before anyone noticed.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-scoop-installed-into-the-default-directory',
    title: 'Scoop installed SDODS into Program Files instead of the Scoop apps directory',
    askedBy: 'owen-brackley',
    askedOn: '2026-06-16',
    tags: ['install', 'windows'],
    votes: 7,
    views: 940,
    body: [
      'I maintain an internal bucket and I copied the SDODS manifest as a starting point for another app. Mine keeps landing in the default install directory instead of the one Scoop asks for, and Scoop then cannot see or uninstall it properly.',
      '',
      'The SDODS one works correctly, so I am clearly getting something subtly wrong in the copy. What is the difference?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'sam-orbison',
        on: '2026-06-16',
        votes: 9,
        body: [
          'Almost certainly the argument order. The installer is NSIS, and the silent form is:',
          '',
          '```text',
          '/S /D=$dir',
          '```',
          '',
          '`/D` has to be last and unquoted. That is an NSIS rule, not a Scoop one. Quote the path or put another switch after it and NSIS ignores the directory entirely and installs to its default — silently, with a success exit code, which is why nothing in your logs points at it.',
          '',
          'So a path with a space in it will not work by quoting it, which is the first thing everyone tries.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-06-17',
        votes: 11,
        body: [
          'To add the diagnosis rather than just the rule: check the manifest you copied against the SDODS one and compare the `installer` args element by element. The failure mode here is that everything looks right and behaves wrong, so reading it as prose does not catch it.',
          '',
          'Test it by installing into a path Scoop chose and then asking Scoop where it thinks the app is. If those disagree, it is the `/D` ordering every time.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a2',
  },
  {
    slug: 'ins-winget-says-no-package-found-matching-input',
    title: 'winget install SDODS.SDODS says no package found — is the ID wrong?',
    askedBy: 'tanvi-bhatt',
    askedOn: '2026-07-02',
    tags: ['install', 'windows'],
    votes: 6,
    views: 810,
    body: [
      'The docs table lists it, so I ran it:',
      '',
      '```powershell',
      'winget install SDODS.SDODS',
      '```',
      '',
      '```text',
      'No package found matching input criteria.',
      '```',
      '',
      '`winget search sdods` finds nothing either. Have I got the identifier wrong, or is my winget source stale?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-07-02',
        votes: 10,
        body: [
          "The identifier is right and your source is fine. The manifest is not merged yet — it sits in Microsoft's review queue, and only their reviewers can merge it.",
          '',
          'There is friction in that queue for us specifically: the installers are unsigned, and that is something their validation flags. So this is not a matter of waiting a fixed number of days.',
          '',
          'Notice that the install page does not offer winget while the docs table does. That is deliberate — the page lists a channel only once its registry actually answers, and a tab whose command fails is worse than a missing tab. The docs table is the full set including what is not live yet.',
          '',
          'Until it merges, Scoop installs the same desktop app:',
          '',
          '```powershell',
          'scoop bucket add sdods https://github.com/siri1410/scoop-sdods',
          'scoop install sdods',
          '```',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'sam-orbison',
        on: '2026-07-03',
        votes: 5,
        body: [
          'Or take the installer straight from [the download page](https://sdods.com/download) if you only need it on one machine. You lose the update channel, which is the only thing winget was going to give you here.',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'ins-smartscreen-blocks-the-windows-installer',
    title: 'Windows protected your PC — how do I get past SmartScreen on the installer?',
    askedBy: 'renata-kohl',
    askedOn: '2026-07-15',
    tags: ['install', 'windows'],
    votes: 11,
    views: 1520,
    body: [
      "Downloaded the Windows installer and SmartScreen blocks it with the blue dialog. There is no obvious way to continue — only a Don't run button.",
      '',
      'Two questions really: how do I proceed, and should I be worried?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'sam-orbison',
        on: '2026-07-15',
        votes: 12,
        body: [
          'The continue option is hidden behind the "More info" link on that dialog. Click it and a "Run anyway" button appears. That is the whole trick, and it catches everyone the first time because the visible buttons do not suggest there is another path.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-07-15',
        votes: 16,
        body: [
          'And to the second question, which is the better one: the installers are not signed yet, so SmartScreen has no publisher identity to have an opinion about. It is telling you it does not recognise the file, not that it found something in it.',
          '',
          'If you want to check the download rather than trust a dialog, every release ships `SHA256SUMS.txt`; compare the hash of the file you have against it.',
          '',
          'Signing is a real cost rather than an oversight — a certificate, a validated identity, and since 2023 a hardware or cloud HSM holding the key, which is what makes signing in CI awkward. It is also the thing blocking the winget submission, so it is not being ignored.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'hsu-wei-lin',
        on: '2026-07-17',
        votes: 7,
        body: [
          'One correction to something you will find in older guides while searching this: an EV certificate no longer skips SmartScreen on day one. It used to, which is why so much advice recommends paying the EV premium for a new app, but Microsoft removed that behaviour in 2024. EV-signed files now build reputation the same way OV-signed ones do.',
          '',
          'So even once these are signed, expect the warning to fade rather than vanish, and expect it to reset if the signing identity ever changes.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a2',
  },
  {
    slug: 'ins-install-the-deb-directly-without-the-repository',
    title: 'Can I just install the .deb without adding the apt repository?',
    askedBy: 'anouk-devries',
    askedOn: '2026-07-28',
    tags: ['install', 'linux'],
    votes: 6,
    views: 720,
    body: [
      'One laptop, one install, and I would rather not add a third-party apt source to a machine that our security policy says should have as few as possible. Is the standalone package a supported path or just a by-product?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'lars-vinter',
        on: '2026-07-28',
        votes: 9,
        body: [
          'Supported, and it is the documented choice for exactly your case — the app without the update channel. Download the `.deb` from [the download page](https://sdods.com/download) first, then:',
          '',
          '```bash',
          'sudo apt install ./SDODS-*-linux-amd64.deb',
          '```',
          '',
          'Two details that matter. The leading `./` is required: without it apt looks for a package by that name in your configured sources and tells you it does not exist. And use the glob rather than typing the version — the filename carries it, so a pasted command goes stale the moment there is a new release.',
          '',
          'The trade-off is the obvious one: `apt upgrade` will never move it. You reinstall by hand when you want a newer build, which for one laptop is a fine deal.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-apt-update-does-not-have-a-release-file',
    title: 'apt update: the repository "does not have a Release file"',
    askedBy: 'lars-vinter',
    askedOn: '2026-08-11',
    tags: ['install', 'linux'],
    votes: 13,
    views: 1480,
    body: [
      'Added the SDODS apt source and the key, then:',
      '',
      '```text',
      "E: The repository 'https://sdods.com/apt ./ Release' does not have a Release file.",
      "N: Updating from such a repository can't be done securely, and is therefore disabled by default.",
      '```',
      '',
      'The odd part: the files are there. `curl https://sdods.com/apt/dists/stable/InRelease` returns a signed index perfectly happily. So apt is asking for something in a different place than the one I can fetch by hand.',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-08-11',
        votes: 17,
        body: [
          "Look at the distribution in your error: `./`. That is a flat-repository source line, and this repository is not flat — it is a standard `dists/` layout, which is why your `curl` of the `dists/` path works and apt's fetch does not.",
          '',
          'A flat source puts a `./` segment into every path apt builds, so it asks for:',
          '',
          '```text',
          'https://sdods.com/apt/./InRelease',
          '```',
          '',
          'Fix the source line to name the distribution and the component:',
          '',
          '```bash',
          'echo "deb [signed-by=/usr/share/keyrings/sdods-archive-keyring.gpg] https://sdods.com/apt stable main" | sudo tee /etc/apt/sources.list.d/sdods.list',
          '```',
          '',
          '```bash',
          'sudo apt update && sudo apt install sdods',
          '```',
          '',
          'The two setup lines in full, with the key, are at [https://sdods.com/apt/](https://sdods.com/apt/) and in [Getting started → Installation](https://docs.sdods.com/docs/getting-started/installation/).',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'chandra-p',
        on: '2026-08-12',
        votes: 8,
        body: [
          'Adding the detail that makes this worth reading rather than just fixing: the repository was published flat once, and it failed for everybody in exactly this way while looking perfectly healthy to `curl`.',
          '',
          'The hosting layer answers a path containing `/./` with a redirect to somewhere that 404s. Every file was reachable on the normalised path, so checking the files existed said the repository was fine. Only an actual `apt install` in a container found it.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'petrov-k',
        on: '2026-08-13',
        votes: 5,
        body: [
          'If you copied the old line from somewhere, check for a stray `[trusted=yes]` too while you are in there. That disables signature checking for the source, and people add it to get past an error that is really about layout rather than signing.',
        ].join('\n'),
      },
      {
        id: 'a4',
        by: 'priya-venkatesh',
        on: '2026-08-20',
        votes: 4,
        body: [
          'General lesson from that one, since it applies well beyond apt: "the files are reachable" and "the client can use them" are different questions, and only the second one is the one you care about. The check that catches this is an install in a clean container, not a `curl` of each artifact.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-apt-nopubkey-after-adding-the-signing-key',
    title: 'NO_PUBKEY on apt update even though I installed the SDODS key',
    askedBy: 'chandra-p',
    askedOn: '2026-08-19',
    tags: ['install', 'linux'],
    votes: 7,
    views: 780,
    body: [
      'Key is installed, source is added, and apt still will not verify the index:',
      '',
      '```text',
      "W: GPG error: https://sdods.com/apt stable InRelease: The following signatures couldn't be verified",
      'because the public key is not available: NO_PUBKEY BED37DAF83087449',
      "E: The repository 'https://sdods.com/apt stable InRelease' is not signed.",
      '```',
      '',
      'I saved the key into `/usr/share/keyrings/` and the file is definitely there. What am I missing?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'lars-vinter',
        on: '2026-08-19',
        votes: 8,
        body: [
          'Almost certainly the format. apt reads binary keyrings from that directory, and an ASCII-armoured key saved there fails with an error that blames the signature rather than the format — which is exactly the message you have.',
          '',
          'The published key is already in the binary form, so fetch that one rather than converting anything:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/apt/sdods-archive-keyring.gpg | sudo tee /usr/share/keyrings/sdods-archive-keyring.gpg > /dev/null',
          '```',
          '',
          'Then check your source line actually points `signed-by` at that exact path — a typo there produces the same NO_PUBKEY, because apt is looking in a keyring that does not exist.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'daniel-oyelaran',
        on: '2026-08-19',
        votes: 11,
        body: [
          'And if you used `apt-key add` from an older guide, that is the other cause. It is deprecated, and a key in the legacy global keyring is not consulted for a source that names `signed-by`. The two mechanisms do not see each other.',
          '',
          'The full sequence, in the order it has to happen:',
          '',
          '```bash',
          'curl -fsSL https://sdods.com/apt/sdods-archive-keyring.gpg | sudo tee /usr/share/keyrings/sdods-archive-keyring.gpg > /dev/null',
          '```',
          '',
          '```bash',
          'echo "deb [signed-by=/usr/share/keyrings/sdods-archive-keyring.gpg] https://sdods.com/apt stable main" | sudo tee /etc/apt/sources.list.d/sdods.list',
          '```',
          '',
          '```bash',
          'sudo apt update',
          '```',
          '',
          'The fingerprint is published at [https://sdods.com/apt/](https://sdods.com/apt/) so you can check the key you installed is the one signing the repository, which is worth doing once.',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'bruno-teixeira',
        on: '2026-08-24',
        votes: 3,
        body: [
          'Whatever you do, do not reach for `[trusted=yes]` to get past it. That disables signature checking for that source, and it is a very sticky line to leave in a sources file on a machine that installs other things.',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a2',
  },
  {
    slug: 'ins-doctor-says-a-browser-engine-is-missing',
    title: 'doctor reports chromium missing but the install said it downloaded it',
    askedBy: 'tobi-schrader',
    askedOn: '2026-04-01',
    tags: ['install', 'cli'],
    votes: 9,
    views: 1560,
    body: [
      'Install finished with no errors. `sdods doctor` disagrees about the browser:',
      '',
      '```text',
      'browser:chromium   not installed',
      '```',
      '',
      'Everything else in the report is fine. Do I need to reinstall everything, or is there a smaller fix?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'reeta-nandal',
        on: '2026-04-01',
        votes: 13,
        body: [
          'Much smaller. `doctor --fix` installs the engines that are missing and touches nothing else:',
          '',
          '```bash',
          'sdods doctor --fix',
          '```',
          '',
          'The usual cause is that the install ran with `--browsers none`, or with a different `HOME` than the shell you are checking from — the engine cache is per user, so a run under another account looks like a missing engine rather than a permission problem.',
          '',
          'If `--fix` downloads it and it still will not launch, that is a different failure: the engine is present and the system libraries are not. On Linux that one needs `sdods browsers install -b chromium --with-deps` with root.',
          '',
          'For reference, this is what a clean pass looks like — every engine line is probed rather than assumed, so you can tell "not downloaded" from "downloaded and will not start":',
          '',
          '![Terminal output of sdods doctor with every check passing: node, bun, the runner, the browser engines, the discovered projects, the resolved variables and the database](/questions/doctor.png "doctor keeps going past a failure, so one run gives you every check.")',
          '',
          'The full check list is in [Reference → sdods doctor](https://docs.sdods.com/docs/reference/cli-commands/doctor/).',
        ].join('\n'),
      },
    ],
    acceptedAnswerId: 'a1',
  },
  {
    slug: 'ins-branching-on-installer-exit-codes-in-a-script',
    title: 'What do the installer exit codes mean? They do not match the CLI ones',
    askedBy: 'nikhil-sane',
    askedOn: '2026-04-09',
    tags: ['install', 'ci', 'cli'],
    votes: 11,
    views: 1690,
    body: [
      'I want our provisioning script to react differently depending on why the install failed — retry a download, but fail the build for a bad flag. I found the CLI exit code table and started using it, then noticed the numbers did not line up with what I was seeing.',
      '',
      'Are they two different sets?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-04-09',
        votes: 14,
        body: [
          'Two different sets, yes, and that trips people up because they are both "SDODS exit codes". The installer is a standalone script and answers a different set of questions than the CLI does.',
          '',
          'The installer codes:',
          '',
          '```text',
          '0  success (also --help, --version-check, a cancelled uninstall)',
          '1  generic failure',
          '2  usage error: unknown flag, missing value, invalid choice',
          '3  unsupported platform',
          '4  missing prerequisite: git, curl, or the requested package manager',
          '5  Node missing or too old',
          '6  download failure',
          '7  install failure, including an incomplete checkout',
          '8  permission problem: bin directory not writable, or running as root',
          '```',
          '',
          'For your branching: 6 is the retryable one, and 2, 3, 4 and 8 are all "the environment or the command is wrong" and should fail fast rather than loop.',
          '',
          'Every failure also prints a docs link on the last line, so a captured log tells you where to look without needing the table.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'priya-venkatesh',
        on: '2026-04-10',
        votes: 8,
        body: [
          'Do not carry the CLI table over by accident — the CLI uses `2` for a configuration or usage error and `3` for lint errors, which is nothing like `3` on the installer. Two tables, two pages: [Reference → Installer](https://docs.sdods.com/docs/reference/installer/) and [Reference → Exit codes](https://docs.sdods.com/docs/reference/exit-codes/).',
        ].join('\n'),
      },
      {
        id: 'a3',
        by: 'paulo-mendes',
        on: '2026-04-19',
        votes: 4,
        body: [
          'Practical note from wiring this up: retrying 6 blindly is not always right either. A download failure behind a proxy that is refusing the host will fail identically every time, and three retries just makes the job three times slower before it reports the same thing. We retry once and then surface the log.',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'ins-brew-formula-gives-the-cli-not-the-app',
    title: 'Installed with brew and there is no SDODS in my Applications folder',
    askedBy: 'rasha-halabi',
    askedOn: '2026-06-11',
    tags: ['install', 'macos', 'cli'],
    votes: 5,
    views: 690,
    body: [
      'I wanted the desktop app and installed with brew because that is how I install everything:',
      '',
      '```bash',
      'brew install siri1410/sdods/sdods',
      '```',
      '',
      'It succeeded, and `sdods --version` works, but there is nothing in Applications and no window anywhere. Did the cask not get installed, or is the app somewhere unusual?',
    ].join('\n'),
    answers: [
      {
        id: 'a1',
        by: 'daniel-oyelaran',
        on: '2026-06-11',
        votes: 8,
        body: [
          'Nothing went wrong — the formula installs the CLI and there is no cask. `sdods --version` working is the install succeeding, not a partial one.',
          '',
          'For the desktop app on macOS, take the installer from [the download page](https://sdods.com/download).',
          '',
          'If what you actually wanted was a UI rather than the packaged app, the CLI already has one and you have it installed:',
          '',
          '```bash',
          'sdods serve',
          '```',
          '',
          'That is the same web UI the app wraps, in your browser, against the projects in the directory you started it from.',
        ].join('\n'),
      },
      {
        id: 'a2',
        by: 'paulo-mendes',
        on: '2026-06-13',
        votes: 3,
        body: [
          'The channel table in the docs marks what each one installs, which is worth a glance before picking one — the CLI, the server image and the desktop app are three different things and every manager only carries one of them.',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'ins-unsupported-architecture-i686',
    title: 'Unsupported architecture: i686 — is 32-bit Linux out entirely?',
    askedBy: 'vikram-r',
    askedOn: '2026-08-24',
    tags: ['install', 'linux'],
    votes: 2,
    views: 118,
    body: [
      'We still have a small fleet of older 32-bit boxes doing one specific job, and I was hoping to run a few API scenarios on them rather than provisioning something new. The installer stops immediately:',
      '',
      '```text',
      'Unsupported architecture: i686',
      '  SDODS needs x86_64 or arm64.',
      '  Docs: https://docs.sdods.com/docs/getting-started/installation/',
      '```',
      '',
      'I understand no browser engine is going to run there. But the API layer needs no browser at all — is the architecture check refusing something that would otherwise work, or is Node itself the blocker on these?',
    ].join('\n'),
    answers: [],
  },
  {
    slug: 'ins-installing-on-a-machine-with-no-internet-access',
    title: 'Installing onto a machine with no outbound internet at all',
    askedBy: 'j-okonkwo',
    askedOn: '2026-09-01',
    tags: ['install', 'ci'],
    votes: 1,
    views: 52,
    body: [
      'Air-gapped test lab. No proxy to configure, no mirror to point at — the machines genuinely have no route out, and files arrive on a reviewed share.',
      '',
      'What I am trying to work out is what the complete set of artifacts is. The packages I can stage. The browser engine cache I assume I can copy from an identical machine, since it is a shared cache keyed per build. What I cannot tell from the docs is whether anything in the install or the first run reaches out on its own beyond those two.',
      '',
      'Has anyone actually done this end to end? I would rather hear it from someone who has than discover the third thing on the day.',
    ].join('\n'),
    answers: [],
  },
];
