// Generated by `sdods load -p shop -e perf browse`. Do not edit: change
// load/browse.yaml and regenerate. Secrets are read from the environment (__ENV)
// when k6 runs and are never written to this file.
import http from 'k6/http';
import { check, fail, sleep } from 'k6';

const BASE_URL = "https://api.perf.example.com";
const REQUIRED_ENV = ["API_TOKEN","OWNER_ID","TENANT_ID"];

export const options = {
  "stages": [
    {
      "duration": "30s",
      "target": 10
    },
    {
      "duration": "1m",
      "target": 25
    },
    {
      "duration": "15s",
      "target": 0
    }
  ],
  "thresholds": {
    "http_req_duration": [
      "p(95)<500"
    ],
    "http_req_failed": [
      "rate<0.01"
    ]
  },
  "tags": {
    "project": "shop",
    "env": "perf",
    "profile": "browse"
  }
};

export function setup() {
  const missing = REQUIRED_ENV.filter((name) => !__ENV[name]);
  if (missing.length) fail("missing environment variables: " + missing.join(", "));
  const data = {};
  return data;
}

export default function (data) {
  const headers = {
    "Accept": "application/json",
    "Authorization": "Bearer " + __ENV.API_TOKEN,
  };
  let res;
  res = http.request("GET", BASE_URL + "/posts?limit=" + (__ENV.PAGE_SIZE || "20"), null, {
    headers: Object.assign({}, headers, {}),
    tags: { name: "list posts" },
  });
  check(res, {
    "list posts: status 200": (r) => [200].includes(r.status),
    "list posts: body contains": (r) => String(r.body).includes("title"),
    "list posts: under 800ms": (r) => r.timings.duration < 800,
  });
  res = http.request("POST", BASE_URL + "/posts", JSON.stringify({
    "title": "load",
    "owner": __ENV.OWNER_ID,
    "tags": [
      "a",
      "b",
    ],
  }), {
    headers: Object.assign({}, headers, { "Content-Type": "application/json", "X-Tenant": __ENV.TENANT_ID }),
    tags: { name: "POST /posts" },
  });
  check(res, {
    "POST /posts: status 200 or 201": (r) => [200,201].includes(r.status),
  });
  sleep(0.5);
}
