/**
 * Emits `packages/mcp/src/browser/shapes.ts` from the checked-in Playwright MCP tool dump.
 *
 * The shapes are committed source, not built at runtime: `sdods mcp --list-tools` must answer the
 * same thing on every machine, without spawning a browser server to find out what it can offer.
 * They are generated rather than typed by hand because the schemas carry details that a careful
 * transcription still gets wrong — `browser_network_request.index` is 1-based, `modifiers` is a
 * five-value enum, `fill_form.fields[].type` is another one.
 *
 * Regenerate after a Playwright bump:
 *   bun run mcp:browser-fixture   # re-dump tools/list from the pinned binary
 *   bun run mcp:browser-shapes    # rewrite this file from the dump
 *
 * `packages/mcp/test/browser-schemas.test.ts` compares the two, so skipping either step fails.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const FIXTURE = join(repoRoot, 'packages/mcp/test/fixtures/playwright-mcp-tools.json');
const OUT = join(repoRoot, 'packages/mcp/src/browser/shapes.ts');

interface JsonSchema {
  type?: string;
  description?: string;
  enum?: string[];
  items?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  minimum?: number;
  default?: unknown;
  additionalProperties?: unknown;
}
interface Dump {
  serverInfo: { name: string; version: string };
  tools: Array<{ name: string; description: string; inputSchema: JsonSchema }>;
}

const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/** One property -> a zod expression. Indent is only for readability of nested objects. */
function zod(schema: JsonSchema, required: boolean, indent = '  '): string {
  let expr: string;
  if (schema.enum?.length) {
    expr = `z.enum([${schema.enum.map(q).join(', ')}])`;
  } else if (schema.type === 'array') {
    expr = `z.array(${zod(schema.items ?? { type: 'string' }, true, indent)})`;
  } else if (schema.type === 'object' && schema.properties) {
    const req = new Set(schema.required ?? []);
    const inner = Object.entries(schema.properties)
      .map(([k, v]) => `${indent}    ${k}: ${zod(v, req.has(k), indent + '  ')},`)
      .join('\n');
    expr = `z.object({\n${inner}\n${indent}  })`;
  } else if (schema.type === 'integer') {
    expr =
      schema.minimum !== undefined ? `z.number().int().min(${schema.minimum})` : 'z.number().int()';
  } else if (schema.type === 'number') {
    expr = 'z.number()';
  } else if (schema.type === 'boolean') {
    expr = 'z.boolean()';
  } else {
    expr = 'z.string()';
  }
  if (schema.description) expr += `.describe(${q(schema.description)})`;
  return required ? expr : `${expr}.optional()`;
}

function main() {
  const dump = JSON.parse(readFileSync(FIXTURE, 'utf8')) as Dump;
  const body = dump.tools
    .map((t) => {
      const props = t.inputSchema.properties ?? {};
      const req = new Set(t.inputSchema.required ?? []);
      const entries = Object.entries(props)
        // Upstream marks a handful of properties required even though they carry a default, so a
        // caller would have to restate the default to make a call at all. They are optional on the
        // SDODS side and the driver fills the default back in before forwarding, which keeps the
        // wire call identical while making the tool pleasant to hold.
        .map(([k, v]) => `    ${k}: ${zod(v, req.has(k) && v.default === undefined)},`)
        .join('\n');
      return `  ${t.name}: {\n${entries}\n  },`;
    })
    .join('\n');

  const defaultsBody = dump.tools
    .map((t) => {
      const req = new Set(t.inputSchema.required ?? []);
      const withDefault = Object.entries(t.inputSchema.properties ?? {}).filter(
        ([k, v]) => v.default !== undefined && req.has(k),
      );
      if (!withDefault.length) return null;
      const inner = withDefault
        .map(([k, v]) => `    ${k}: ${JSON.stringify(v.default)},`)
        .join('\n');
      return `  ${t.name}: {\n${inner}\n  },`;
    })
    .filter(Boolean)
    .join('\n');

  const out = `// GENERATED by scripts/gen-browser-shapes.ts from
// packages/mcp/test/fixtures/playwright-mcp-tools.json (Playwright ${dump.serverInfo.version}).
// Do not edit by hand: \`bun run mcp:browser-shapes\` rewrites it, and
// packages/mcp/test/browser-schemas.test.ts fails if it drifts from the dump.
//
// The tool names, argument names and descriptions below are taken from the Playwright MCP server
// (https://github.com/microsoft/playwright), Copyright (c) Microsoft Corporation, licensed under
// the Apache License, Version 2.0. See NOTICE at the repository root.
import { z } from 'zod';

/** Upstream argument shapes, one per Playwright MCP tool. \`sessionId\` is added by the wrapper. */
export const UPSTREAM_SHAPES = {
${body}
} as const;

export type UpstreamToolName = keyof typeof UPSTREAM_SHAPES;

/**
 * Properties upstream marks required while giving them a default. They are optional on the SDODS
 * side; the driver merges these back in before the call so the wire request is unchanged.
 */
export const UPSTREAM_DEFAULTS: Partial<Record<UpstreamToolName, Record<string, unknown>>> = {
${defaultsBody}
};
`;
  writeFileSync(OUT, out);
  console.log(`gen-browser-shapes — ${dump.tools.length} shape(s) written to ${OUT}`);
}

main();
