/**
 * Writes the roadmap summary in README.md from `@sdods/roadmap`.
 *
 * One source of truth: edit `packages/roadmap/src/` only. The README table used to be a third
 * hand-maintained copy of the phases, which is how it came to disagree with both sites.
 *
 * `bun run roadmap:sync` rewrites the block; `--check` exits non-zero if it is out of date,
 * which is what `tests/roadmap-sync.test.ts` asserts so a data edit cannot land without it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CHECKPOINTS, isChapter, isMonth, VERIFICATION } from '@sdods/roadmap';

export const START = '<!-- roadmap:start — generated by scripts/sync-roadmap.ts. Do not edit. -->';
export const END = '<!-- roadmap:end -->';

const MONTH_STATUS: Record<string, string> = {
  delivered: 'Delivered',
  now: 'In progress',
  planned: 'Planned',
  direction: 'Direction',
};

/** The block between the markers. Deterministic: no clock, no locale, no ordering surprises. */
export function renderReadmeBlock(): string {
  const chapters = CHECKPOINTS.filter(isChapter).sort((a, b) => a.order - b.order);
  const months = CHECKPOINTS.filter(isMonth).sort((a, b) => a.when.localeCompare(b.when));
  const lines: string[] = [];

  lines.push('Delivered, as five chapters. Every phase inside them ends runnable.');
  lines.push('');
  lines.push('| Chapter | Phases | What it delivered |');
  lines.push('|---|---|---|');
  for (const chapter of chapters) {
    const numbers = chapter.phases.map((p) => p.phase).join(', ');
    lines.push(`| ${chapter.label} | ${numbers} | ${chapter.title} |`);
  }
  lines.push('');
  lines.push(
    'The twelve months, in the order they land. A delivered month lists what actually shipped.',
  );
  lines.push('');
  lines.push('| When | Checkpoint | Status |');
  lines.push('|---|---|---|');
  for (const month of months) {
    lines.push(`| ${month.label} | ${month.title} | ${MONTH_STATUS[month.state]} |`);
  }
  lines.push('');
  lines.push(
    `Verified on ${VERIFICATION[0]?.measuredOn ?? 'the date in packages/roadmap'}: ` +
      VERIFICATION.map((row) => `${row.label.toLowerCase()} ${row.result}`).join('; ') +
      '.',
  );
  lines.push('');
  lines.push('The full road — the chapters, the twelve months and the horizon to 2030 — is at');
  lines.push('<https://docs.sdods.com/docs/roadmap/>.');
  return lines.join('\n');
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const readmePath = join(repoRoot, 'README.md');

export function currentBlock(readme: string): string {
  const from = readme.indexOf(START);
  const to = readme.indexOf(END);
  if (from === -1 || to === -1 || to < from) {
    throw new Error(`sync-roadmap — README.md is missing the ${START} / ${END} markers`);
  }
  return readme.slice(from + START.length, to).trim();
}

function main(): void {
  const check = process.argv.includes('--check');
  const readme = readFileSync(readmePath, 'utf8');
  const wanted = renderReadmeBlock();
  const found = currentBlock(readme);

  if (found === wanted) {
    console.log('sync-roadmap — README.md up to date');
    return;
  }
  if (check) {
    console.error('sync-roadmap — README.md is out of date. Run: bun run roadmap:sync');
    process.exit(2);
  }
  const from = readme.indexOf(START);
  const to = readme.indexOf(END);
  writeFileSync(
    readmePath,
    `${readme.slice(0, from + START.length)}\n\n${wanted}\n\n${readme.slice(to)}`,
  );
  console.log('sync-roadmap — README.md rewritten');
}

if (import.meta.url === `file://${process.argv[1]}`) main();
