// GENERATED by scripts/gen-browser-shapes.ts from
// packages/mcp/test/fixtures/playwright-mcp-tools.json (Playwright 1.64.0).
// Do not edit by hand: `bun run mcp:browser-shapes` rewrites it, and
// packages/mcp/test/browser-schemas.test.ts fails if it drifts from the dump.
//
// The tool names, argument names and descriptions below are taken from the Playwright MCP server
// (https://github.com/microsoft/playwright), Copyright (c) Microsoft Corporation, licensed under
// the Apache License, Version 2.0. See NOTICE at the repository root.
import { z } from 'zod';

/** Upstream argument shapes, one per Playwright MCP tool. `sessionId` is added by the wrapper. */
export const UPSTREAM_SHAPES = {
  browser_annotate: {},
  browser_click: {
    element: z
      .string()
      .describe(
        'Human-readable element description used to obtain permission to interact with the element',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      ),
    doubleClick: z
      .boolean()
      .describe('Whether to perform a double click instead of a single click')
      .optional(),
    button: z
      .enum(['left', 'right', 'middle'])
      .describe('Button to click, defaults to left')
      .optional(),
    modifiers: z
      .array(z.enum(['Alt', 'Control', 'ControlOrMeta', 'Meta', 'Shift']))
      .describe('Modifier keys to press')
      .optional(),
  },
  browser_close: {},
  browser_console_messages: {
    level: z
      .enum(['error', 'warning', 'info', 'debug'])
      .describe(
        'Level of the console messages to return. Each level includes the messages of more severe levels. Defaults to "info".',
      )
      .optional(),
    all: z
      .boolean()
      .describe(
        'Return all console messages since the beginning of the session, not just since the last navigation. Defaults to false.',
      )
      .optional(),
    filename: z
      .string()
      .describe(
        'File name to save the console messages to. Relative file names are resolved against the workspace root. If not provided, messages are returned as text.',
      )
      .optional(),
  },
  browser_drag: {
    startElement: z
      .string()
      .describe(
        'Human-readable source element description used to obtain the permission to interact with the element',
      )
      .optional(),
    startTarget: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      ),
    endElement: z
      .string()
      .describe(
        'Human-readable target element description used to obtain the permission to interact with the element',
      )
      .optional(),
    endTarget: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      ),
  },
  browser_drop: {
    element: z
      .string()
      .describe(
        'Human-readable element description used to obtain permission to interact with the element',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      ),
    paths: z
      .array(z.string())
      .describe('Absolute paths to files to drop onto the element.')
      .optional(),
    data: z
      .string()
      .describe(
        'Data to drop, as a map of MIME type to string value (e.g. {"text/plain": "hello", "text/uri-list": "https://example.com"}).',
      )
      .optional(),
  },
  browser_emulate_media: {
    colorScheme: z.string().describe('Emulates the prefers-color-scheme media feature').optional(),
    reducedMotion: z
      .string()
      .describe('Emulates the prefers-reduced-motion media feature')
      .optional(),
    forcedColors: z.string().describe('Emulates the forced-colors media feature').optional(),
    contrast: z.string().describe('Emulates the prefers-contrast media feature').optional(),
    media: z.string().describe('Changes the CSS media type of the page').optional(),
  },
  browser_evaluate: {
    element: z
      .string()
      .describe(
        'Human-readable element description used to obtain permission to interact with the element',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      )
      .optional(),
    function: z
      .string()
      .describe('() => { /* code */ } or (element) => { /* code */ } when element is provided'),
    filename: z
      .string()
      .describe(
        'File name to save the result to. Relative file names are resolved against the workspace root. If not provided, result is returned as text.',
      )
      .optional(),
  },
  browser_file_upload: {
    paths: z
      .array(z.string())
      .describe(
        'The absolute paths to the files to upload. Can be single file or multiple files. If omitted, file chooser is cancelled.',
      )
      .optional(),
  },
  browser_fill_form: {
    fields: z
      .array(
        z.object({
          element: z
            .string()
            .describe(
              'Human-readable element description used to obtain permission to interact with the element',
            )
            .optional(),
          target: z
            .string()
            .describe(
              'Exact target element reference from the page snapshot, or a unique element selector',
            ),
          name: z.string().describe('Human-readable field name'),
          type: z
            .enum(['textbox', 'checkbox', 'radio', 'combobox', 'slider'])
            .describe('Type of the field'),
          value: z
            .string()
            .describe(
              'Value to fill in the field. If the field is a checkbox, the value should be `true` or `false`. If the field is a combobox, the value should be the text of the option.',
            ),
        }),
      )
      .describe('Fields to fill in'),
  },
  browser_find: {
    text: z
      .string()
      .describe(
        'Plain text to search for in the page snapshot (case-insensitive substring match). Provide either text or regex, not both.',
      )
      .optional(),
    regex: z
      .string()
      .describe(
        'Regular expression to search for in the page snapshot. Matching is case-sensitive by default; wrap the pattern in slashes to add flags, e.g. "/error/i" for case-insensitive. Provide either text or regex, not both.',
      )
      .optional(),
    maxResults: z
      .number()
      .describe('Maximum number of matching items to return. Defaults to returning all matches.')
      .optional(),
    filename: z
      .string()
      .describe(
        'Save results to a file instead of returning them in the response. Relative file names are resolved against the workspace root.',
      )
      .optional(),
  },
  browser_handle_dialog: {
    accept: z.boolean().describe('Whether to accept the dialog.'),
    promptText: z
      .string()
      .describe('The text of the prompt in case of a prompt dialog.')
      .optional(),
  },
  browser_hide_highlight: {
    element: z
      .string()
      .describe(
        'Human-readable element description used when adding the highlight; must match the value passed to browser_highlight.',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      )
      .optional(),
  },
  browser_highlight: {
    element: z
      .string()
      .describe(
        'Human-readable element description used to obtain permission to interact with the element',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      ),
    style: z
      .string()
      .describe(
        'Additional inline CSS applied to the highlight overlay, e.g. "outline: 2px dashed red".',
      )
      .optional(),
  },
  browser_hover: {
    element: z
      .string()
      .describe(
        'Human-readable element description used to obtain permission to interact with the element',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      ),
  },
  browser_mouse_click_xy: {
    x: z.number().describe('X coordinate'),
    y: z.number().describe('Y coordinate'),
    button: z
      .enum(['left', 'right', 'middle'])
      .describe('Button to click, defaults to left')
      .optional(),
    clickCount: z.number().describe('Number of clicks, defaults to 1').optional(),
    delay: z
      .number()
      .describe('Time to wait between mouse down and mouse up in milliseconds, defaults to 0')
      .optional(),
  },
  browser_mouse_down: {
    button: z
      .enum(['left', 'right', 'middle'])
      .describe('Button to press, defaults to left')
      .optional(),
  },
  browser_mouse_drag_xy: {
    startX: z.number().describe('Start X coordinate'),
    startY: z.number().describe('Start Y coordinate'),
    endX: z.number().describe('End X coordinate'),
    endY: z.number().describe('End Y coordinate'),
  },
  browser_mouse_move_xy: {
    x: z.number().describe('X coordinate'),
    y: z.number().describe('Y coordinate'),
  },
  browser_mouse_up: {
    button: z
      .enum(['left', 'right', 'middle'])
      .describe('Button to press, defaults to left')
      .optional(),
  },
  browser_mouse_wheel: {
    deltaX: z.number().describe('X delta').optional(),
    deltaY: z.number().describe('Y delta').optional(),
  },
  browser_navigate: {
    url: z.string().describe('The URL to navigate to'),
  },
  browser_navigate_back: {},
  browser_network_request: {
    index: z
      .number()
      .int()
      .min(1)
      .describe('1-based index of the request, as printed by browser_network_requests.'),
    part: z
      .enum(['request-headers', 'request-body', 'response-headers', 'response-body'])
      .describe('Return only this part of the request. Omit to return full details.')
      .optional(),
    filename: z
      .string()
      .describe(
        'File name to save the result to. Relative file names are resolved against the workspace root. If not provided, output is returned as text.',
      )
      .optional(),
  },
  browser_network_requests: {
    static: z
      .boolean()
      .describe(
        'Whether to include successful static resources like images, fonts, scripts, etc. Defaults to false.',
      )
      .optional(),
    filter: z
      .string()
      .describe('Only return requests whose URL matches this regexp (e.g. "/api/.*user").')
      .optional(),
    filename: z
      .string()
      .describe(
        'File name to save the network requests to. Relative file names are resolved against the workspace root. If not provided, requests are returned as text.',
      )
      .optional(),
  },
  browser_pdf_save: {
    filename: z
      .string()
      .describe(
        'File name to save the pdf to. Relative file names are resolved against the workspace root. If not specified, the pdf is saved into the output directory as `page-{timestamp}.pdf`.',
      )
      .optional(),
  },
  browser_press_key: {
    key: z
      .string()
      .describe('Name of the key to press or a character to generate, such as `ArrowLeft` or `a`'),
  },
  browser_resize: {
    width: z.number().describe('Width of the browser window'),
    height: z.number().describe('Height of the browser window'),
  },
  browser_resume: {
    step: z
      .boolean()
      .describe(
        'When true, execution will pause again before the next action, allowing step-by-step debugging.',
      )
      .optional(),
    location: z
      .string()
      .describe('Pause execution at a specific <file>:<line>, e.g. "example.spec.ts:42".')
      .optional(),
  },
  browser_run_code_unsafe: {
    code: z
      .string()
      .describe(
        "A JavaScript function containing Playwright code to execute. It will be invoked with a single argument, page, which you can use for any page interaction. For example: `async (page) => { await page.getByRole('button', { name: 'Submit' }).click(); return await page.title(); }`",
      )
      .optional(),
    filename: z
      .string()
      .describe(
        'Load code from the specified file. Relative file names are resolved against the workspace root. If both code and filename are provided, code will be ignored.',
      )
      .optional(),
  },
  browser_select_option: {
    element: z
      .string()
      .describe(
        'Human-readable element description used to obtain permission to interact with the element',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      ),
    values: z
      .array(z.string())
      .describe(
        'Array of values to select in the dropdown. This can be a single value or multiple values.',
      ),
  },
  browser_snapshot: {
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      )
      .optional(),
    filename: z
      .string()
      .describe(
        'Save snapshot to a file instead of returning it in the response. Relative file names are resolved against the workspace root.',
      )
      .optional(),
    depth: z.number().describe('Limit the depth of the snapshot tree').optional(),
    boxes: z
      .boolean()
      .describe(
        "Include each element's bounding box as [box=x,y,width,height] in the snapshot. Coordinates are viewport-relative, in CSS pixels (Element.getBoundingClientRect)",
      )
      .optional(),
  },
  browser_start_recording: {},
  browser_start_tracing: {},
  browser_start_video: {
    filename: z
      .string()
      .describe(
        'File name to save the video to. Relative file names are resolved against the workspace root. If not specified, the video is saved into the output directory as `video-{timestamp}.webm`.',
      )
      .optional(),
    size: z
      .object({
        width: z.number().describe('Video width'),
        height: z.number().describe('Video height'),
      })
      .describe('Video size')
      .optional(),
    fps: z.number().describe('Video frame rate in frames per second, defaults to 25').optional(),
    cursor: z
      .boolean()
      .describe(
        'Render an animated mouse cursor that travels to each action point. Paces actions by 800ms so that the cursor has time to travel.',
      )
      .optional(),
  },
  browser_stop_recording: {},
  browser_stop_tracing: {},
  browser_stop_video: {},
  browser_tabs: {
    action: z.enum(['list', 'new', 'close', 'select']).describe('Operation to perform'),
    index: z
      .number()
      .describe('Tab index, used for close/select. If omitted for close, current tab is closed.')
      .optional(),
    url: z.string().describe('URL to navigate to in the new tab, used for new.').optional(),
    isolatedContext: z
      .string()
      .describe(
        'Name of an isolated browser context to create the new tab in, used for new. Tabs in the same isolated context share cookies and storage, tabs in different contexts are fully isolated. If omitted or "default", the tab is created in the default context.',
      )
      .optional(),
  },
  browser_take_screenshot: {
    element: z
      .string()
      .describe(
        'Human-readable element description used to obtain permission to interact with the element',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      )
      .optional(),
    type: z
      .enum(['png', 'jpeg', 'webp'])
      .describe(
        'Image format for the screenshot. If unset, inferred from the filename extension, otherwise png.',
      )
      .optional(),
    filename: z
      .string()
      .describe(
        'File name to save the screenshot to. Relative file names are resolved against the workspace root. If not specified, the screenshot is saved into the output directory as `page-{timestamp}.{png|jpeg|webp}`.',
      )
      .optional(),
    fullPage: z
      .boolean()
      .describe(
        'When true, takes a screenshot of the full scrollable page, instead of the currently visible viewport. Cannot be used with element screenshots.',
      )
      .optional(),
    scale: z
      .enum(['css', 'device'])
      .describe(
        'Image resolution scale. "css" produces a screenshot sized in CSS pixels (smaller, consistent across devices). "device" produces a high-resolution screenshot using device pixels (larger, accounts for the device pixel ratio). Default is css.',
      )
      .optional(),
  },
  browser_type: {
    element: z
      .string()
      .describe(
        'Human-readable element description used to obtain permission to interact with the element',
      )
      .optional(),
    target: z
      .string()
      .describe(
        'Exact target element reference from the page snapshot, or a unique element selector',
      ),
    text: z.string().describe('Text to type into the element'),
    submit: z.boolean().describe('Whether to submit entered text (press Enter after)').optional(),
    slowly: z
      .boolean()
      .describe(
        'Whether to type one character at a time. Useful for triggering key handlers in the page. By default entire text is filled in at once.',
      )
      .optional(),
  },
  browser_video_chapter: {
    title: z.string().describe('Chapter title'),
    description: z.string().describe('Chapter description').optional(),
    duration: z.number().describe('Duration in milliseconds to show the chapter card').optional(),
  },
  browser_video_hide_actions: {},
  browser_video_show_actions: {
    duration: z
      .number()
      .describe(
        'How long each action annotation stays on screen, in milliseconds. Defaults to 500.',
      )
      .optional(),
    position: z
      .enum(['top-left', 'top', 'top-right', 'bottom-left', 'bottom', 'bottom-right'])
      .describe('Where to place the action title relative to the page. Defaults to top-right.')
      .optional(),
    cursor: z
      .enum(['none', 'pointer'])
      .describe(
        'Cursor decoration for pointer actions. "pointer" (default) animates a mouse pointer from the previous action point to the next one; "none" disables the cursor decoration.',
      )
      .optional(),
    style: z
      .object({
        point: z
          .string()
          .describe(
            'CSS declarations for the zero-sized marker centered on the action point, e.g. "width: 20px; height: 20px; border-radius: 50%; background: red". Not shown when omitted.',
          )
          .optional(),
        highlight: z
          .string()
          .describe(
            'CSS declarations for the box that covers the target element, e.g. "outline: 2px solid #333". Not shown when omitted.',
          )
          .optional(),
        title: z
          .string()
          .describe('CSS declarations for the action title, e.g. "font-size: 16px".')
          .optional(),
      })
      .describe('Styles of the action decorations.')
      .optional(),
  },
  browser_wait_for: {
    time: z
      .number()
      .describe(
        'The time to wait in seconds, at most 30. When combined with text or textGone, serves as a timeout for them instead of the default action timeout',
      )
      .optional(),
    text: z.string().describe('The text to wait for').optional(),
    textGone: z.string().describe('The text to wait for to disappear').optional(),
  },
} as const;

export type UpstreamToolName = keyof typeof UPSTREAM_SHAPES;

/**
 * Properties upstream marks required while giving them a default. They are optional on the SDODS
 * side; the driver merges these back in before the call so the wire request is unchanged.
 */
export const UPSTREAM_DEFAULTS: Partial<Record<UpstreamToolName, Record<string, unknown>>> = {
  browser_console_messages: {
    level: 'info',
  },
  browser_mouse_wheel: {
    deltaX: 0,
    deltaY: 0,
  },
  browser_network_requests: {
    static: false,
  },
  browser_take_screenshot: {
    scale: 'css',
  },
};
