# Generated by scripts/sync-channels.ts — do not edit by hand.
#
# Lives in the tap repository YarlisAISolutions/homebrew-sdods as Formula/sdods.rb, which makes the install
# `brew install yarlisaisolutions/sdods/sdods`. The tap is public; the source repository is not, and does
# not need to be — this builds from the published npm tarball, not from a clone.
class Sdods < Formula
  desc "BDD test automation for UI, API and hybrid flows"
  homepage "https://sdods.com"
  url "https://registry.npmjs.org/@sdods/cli/-/cli-0.13.0.tgz"
  sha256 "f641f3a289a74dd5a22bce0f293633665e308fc8907c503b25f55847f46fd31e"
  license "Apache-2.0"

  # Not a vendored Node: SDODS spawns Node for the test runner and the server, and a formula that
  # bundled its own would leave the user with two. `depends_on "node"` is the same Node the rest of
  # their toolchain uses.
  depends_on "node"

  def install
    system "npm", "install", *std_npm_args

    # better-sqlite3 ships prebuilt binaries for every platform it supports, and npm installs the
    # lot. Homebrew rejects a keg containing binaries for a foreign architecture, so everything
    # but this machine's own prebuild is removed -- it would never be loaded anyway.
    keep = "#{OS.kernel_name.downcase}-#{Hardware::CPU.intel? ? "x64" : "arm64"}"
    Dir.glob(libexec/"lib/node_modules/**/prebuilds/*").each do |dir|
      rm_r(dir) if File.basename(dir) != keep
    end

    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  def caveats
    <<~EOS
      Browser engines are not installed yet. Chromium is all most suites need:
        sdods browsers install chromium

      Then check the install:
        sdods doctor
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sdods --version")
    # `doctor` exercises the parts a broken install actually breaks: the bundled runner resolving
    # and the native modules loading against Homebrew's Node. `--version` alone passes on a
    # hollow shim.
    #
    # It exits 1 here, and that is the correct answer: brew test runs in an empty directory, so
    # there are no projects to find. Asserting exit 0 would fail every time on a working install.
    assert_match "runner", shell_output("#{bin}/sdods doctor 2>&1", 1)
  end
end
