# Generated by scripts/sync-channels.ts — do not edit by hand.
#
# Lives in the tap repository siri1410/homebrew-sdods as Formula/sdods.rb, which makes the install
# `brew install siri1410/sdods/sdods`. The tap is public; the source repository is not, and does
# not need to be — this builds from the published npm tarball, not from a clone.
class Sdods < Formula
  desc "BDD test automation for UI, API and hybrid flows"
  homepage "https://sdods.com"
  url "https://registry.npmjs.org/@sdods/cli/-/cli-0.2.2.tgz"
  sha256 "21cd0c5aaf97357048444b27a7ef9db5d3c4ef959636a4f9c5a49a00eb97d002"
  license "Apache-2.0"
  version "0.2.2"

  # Not a vendored Node: SDODS spawns Node for the test runner and the server, and a formula that
  # bundled its own would leave the user with two. `depends_on "node"` is the same Node the rest of
  # their toolchain uses.
  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  def caveats
    <<~EOS
      Browser engines are not installed yet. Chromium is all most suites need:
        sdods browsers install chromium

      Then check the install:
        sdods doctor
    EOS
  end

  test do
    assert_match "0.2.2", shell_output("#{bin}/sdods --version")
    # `doctor` exercises the parts a broken install actually breaks: the bundled runner resolving,
    # the config loading and the database opening. `--version` alone would pass on a hollow shim.
    assert_match "projects", shell_output("#{bin}/sdods doctor 2>&1", 0)
  end
end
